YOURPROJECTNAMEGOESHERE: Vehicle Class Reference
Vehicle Class Reference
The base class for all vehicles.
#include <Vehicle.h>
Public Member Functions
Vehicle (GameWorld *world, ngl::Vec3 position, ngl::Vec3 velocity, float rotation, float mass, float max_force, float max_speed, float max_turnrate, float scale)
Vehicle ctor.
~Vehicle ()
Vehicle dtor.
void update (double time_elapsed)
Method to update the vehicle every tick.
virtual bool handleMessage (const Message &_message)
define virtual function to determine how messages should be handled
SteeringBehaviour * Steering ()
Returns steering behaviour class.
double getTimeElapsed () const
Returns the time elapsed since last tick.
ngl::Vec3 findNearestExit (std::vector< ngl::Vec3 > _exits)
Finds the nearest vec3 from a vector of Vec3s.
void followPath ()
Method to go through path and set the crosshair as the next point when current crosshair has been reached.
void findPath (ngl::Vec3 _target)
Method to find a path to the target.
ngl::Vec3 getCrosshair () const
Gets the current crosshair.
void setCrosshair (const ngl::Vec3 v)
Sets the crosshair.
ngl::Vec3 getSquadCrosshair () const
Gets the current squad crosshair.
void setSquadCrosshair (const ngl::Vec3 v)
Sets the squad crosshair.
ngl::Vec3 smoothingUpdate (ngl::Vec3 _recentHeading)
Method to smooth the heading of the vehicle.
int getPathIndex ()
Gets the path index.
void setPathIndex (const int _index)
Sets the path index.
std::vector< ngl::Vec3 > getPath ()
Gets the current path.
void setPath (const std::vector< ngl::Vec3 > _path)
Sets the current path [in] _path: the vector of vec3s to set the path to.
void clearPath ()
Clears the current path.
Protected Attributes
SteeringBehaviour * m_steering
Returns a pointer to the steering class.
double m_timeElapsed
The time elapsed since the last tick.
ngl::Vec3 m_crosshair
The current crosshair.
ngl::Vec3 m_squadCrosshair
The current squad crosshair.
std::vector< ngl::Vec3 > m_path
The current path.
int m_pathIndex
The current path index.
ngl::Vec3 m_smoothHeading
The smoothed heading.
std::vector< ngl::Vec3 > m_headingHistory
Vector to contain the past headings to use to average for smoothing.
int m_nextSlot
Sets the number of the next slot in the heading history.
int m_sampleSize
The number of past headings used to average and smooth.
bool m_smoothingOn
Boolean: true if smoothing is on, false when smoothing is off.
Detailed Description
The base class for all vehicles.
Author:
Faye Butler, Will Herbert
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 25 of file Vehicle.h.
Constructor & Destructor Documentation
Vehicle::Vehicle (GameWorld * world, ngl::Vec3 position, ngl::Vec3 velocity, float rotation, float mass, float max_force, float max_speed, float max_turnrate, float scale)
Vehicle ctor.
Ctor that intialises variables.
Parameters:
[in] world,: Pointer to the gameworld to be used
[in] position,: vector for the starting position of the vehicle
[in] velocity,: vector for the starting velocity of the vehicle
[in] rotation,: float for the starting rotation of the vehicle
[in] mass,: float to set the mass of the vehicle
[in] max_force,: float to set the maximum force
[in] max_speed,: float to set the maximum speed
[in] max_turnrate,: float to set the maximum turn rate
[in] scale,: float to set the scale of the vehicle
Definition at line 15 of file Vehicle.cpp.
References m_crosshair, m_headingHistory, m_nextSlot, m_pathIndex, m_sampleSize, m_smoothingOn, m_squadCrosshair, and m_steering.
                             : MovingEntity(world,
                                            position,
                                            scale,
                                            velocity,
                                            max_speed,
                                            ngl::Vec3(sin(rotation),0,-cos(rotation)),
                                            mass,
                                            max_turnrate,
                                            max_force),
                                m_timeElapsed(0.0)
{
  m_steering =  new SteeringBehaviour(this);
  m_nextSlot = 0;
  m_smoothingOn = true;
  m_sampleSize = 25.0;
  m_pathIndex = 0;
  m_crosshair= ngl::Vec3(0,0,0);
  m_squadCrosshair = ngl::Vec3(0,0,0);
  for(int i =0; i<m_sampleSize; i++)
  {
    ngl::Vec3 zeroValue = ngl::Vec3(0,0,0);
    m_headingHistory.push_back(zeroValue);
  }
}
Vehicle::~Vehicle ()
Vehicle dtor.
Definition at line 50 of file Vehicle.cpp.
References m_steering.
{
  delete m_steering;
}
Member Function Documentation
void Vehicle::clearPath () [inline]
Clears the current path.
Definition at line 146 of file Vehicle.h.
References m_path.
{m_path.clear();}
ngl::Vec3 Vehicle::findNearestExit (std::vector< ngl::Vec3 > _exits)
Finds the nearest vec3 from a vector of Vec3s.
Parameters:
[in] _exits,: vector of Vec3s to search through
Returns:
Vec3: the vector of the nearest exit
Find Exit - given a vector of vectors, this function iterates through and finds the closest point to the vehicle
mainly used for rioters finding their way home
using the returned vector, a path can be found to that point
Definition at line 157 of file Vehicle.cpp.
References BaseGameEntity::getPos().
{
  //find nearest point to current positiong and set that as path thing
  ngl::Vec3 bestExit;
  float dist = 1000000000.0;
  int exitSize = _exits.size();
  for(int i = 0; i<exitSize; i++)
  {
    ngl::Vec3 currentExit = _exits[i];
    float testDist = (currentExit- this->getPos()).lengthSquared();
    if(testDist < dist*dist)
    {
      bestExit = currentExit;
      dist = testDist;
    }
  }
  return bestExit;
}
void Vehicle::findPath (ngl::Vec3 _target)
Method to find a path to the target.
Find Path - sets m_path to be a path to the inputted target, if this path is not zero then the vehicle is set to follow.
Parameters:
[in] _target,: sets the target point to find a path to
Definition at line 180 of file Vehicle.cpp.
References CellGraph::findPath(), GameWorld::getCellGraph(), m_crosshair, m_path, m_pathIndex, and BaseGameEntity::m_world.
{
  m_path.clear();
  m_pathIndex =0;
  std::vector<ngl::Vec3> path;
  path = m_world->getCellGraph()->findPath(this, _target);
  m_path = path;
  m_crosshair = m_path[m_pathIndex];
}
void Vehicle::followPath ()
Method to go through path and set the crosshair as the next point when current crosshair has been reached.
Follow Path - function iterates through the vectors in the path, and once the vehicle has reached the current crosshair, the next one is set as the destination
Definition at line 194 of file Vehicle.cpp.
References BaseGameEntity::getPos(), m_crosshair, m_path, m_pathIndex, and setPathIndex().
{
  //go through each vec3 and set as crosshair to follow the path
  if (m_pathIndex != m_path.size()-1 && (this->getPos() - m_path[m_pathIndex]).lengthSquared()<= 9)
  {
    setPathIndex(m_pathIndex += 1);
    m_crosshair = m_path[m_pathIndex];
  }
  if(m_pathIndex == m_path.size()-1)
  {
    m_path.clear();
    m_pathIndex =0;
  }
}
ngl::Vec3 Vehicle::getCrosshair () const [inline]
Gets the current crosshair.
Returns:
Vec3: returns current crosshair
Definition at line 92 of file Vehicle.h.
References m_crosshair.
{return m_crosshair;}
std::vector<ngl::Vec3> Vehicle::getPath () [inline]
Gets the current path.
Returns:
vector: returns a vector of Vec3s that contains the points for the path
Definition at line 135 of file Vehicle.h.
References m_path.
{return m_path;}
int Vehicle::getPathIndex () [inline]
Gets the path index.
Returns:
Int: returns the path index number
Definition at line 123 of file Vehicle.h.
References m_pathIndex.
{return m_pathIndex;}
ngl::Vec3 Vehicle::getSquadCrosshair () const [inline]
Gets the current squad crosshair.
Returns:
Vec3: returns current squad crosshair
Definition at line 104 of file Vehicle.h.
References m_squadCrosshair.
{return m_squadCrosshair;}
double Vehicle::getTimeElapsed () const [inline]
Returns the time elapsed since last tick.
Returns:
Double: the time elapsed
Definition at line 68 of file Vehicle.h.
References m_timeElapsed.
{return m_timeElapsed;}
bool Vehicle::handleMessage (const Message & _message) [virtual]
define virtual function to determine how messages should be handled
Parameters:
[in] _message,: message recieved by the vehicle
Reimplemented from MovingEntity.
Reimplemented in Agent, Police, Rioter, and Squad.
Definition at line 124 of file Vehicle.cpp.
{
  return MovingEntity::handleMessage(_message);
}
void Vehicle::setCrosshair (const ngl::Vec3 v) [inline]
Sets the crosshair.
Parameters:
[in] v,: vector to set as current crosshair
Definition at line 98 of file Vehicle.h.
References m_crosshair.
{m_crosshair=v;}
void Vehicle::setPath (const std::vector< ngl::Vec3 > _path) [inline]
Sets the current path [in] _path: the vector of vec3s to set the path to.
Definition at line 141 of file Vehicle.h.
References m_path.
{m_path = _path;}
void Vehicle::setPathIndex (const int _index) [inline]
Sets the path index.
Parameters:
[in] _index,: number to set the path index to
Definition at line 129 of file Vehicle.h.
References m_pathIndex.
{m_pathIndex = _index;}
void Vehicle::setSquadCrosshair (const ngl::Vec3 v) [inline]
Sets the squad crosshair.
Parameters:
[in] v,: vector to set as current crosshair
Definition at line 110 of file Vehicle.h.
References m_squadCrosshair.
{m_squadCrosshair=v;}
ngl::Vec3 Vehicle::smoothingUpdate (ngl::Vec3 _recentHeading)
Method to smooth the heading of the vehicle.
Smoothing - calculates the average heading from a set number of past headings (_sampleSize).
Parameters:
[in] _recentHeading,: the current heading to pass in
Returns:
Vec3: returns the average heading from a set number of previous headings
Definition at line 132 of file Vehicle.cpp.
References m_headingHistory, and m_nextSlot.
{
  m_headingHistory[m_nextSlot++] = _recentHeading;
  if(m_nextSlot == m_headingHistory.size())
  {
    m_nextSlot = 0;
  }
  ngl::Vec3 sum = ngl::Vec3(0,0,0);
  std::vector<ngl::Vec3>::iterator it = m_headingHistory.begin();
  for(it; it!=m_headingHistory.end(); it++)
  {
    sum += *it;
  }
  return sum / m_headingHistory.size();
}
SteeringBehaviour* Vehicle::Steering () [inline]
Returns steering behaviour class.
Definition at line 62 of file Vehicle.h.
References m_steering.
{return m_steering;}
void Vehicle::update (double time_elapsed)
Method to update the vehicle every tick.
Parameters:
[in] time_elapsed,: the time elapsed between each tick
Update Function - used to calculate the acceleration, using the steering force and mass, this is multiplied by the time elapsed from the last tick to create the new vehicle position
Smoothing is also added to the heading, so that the jumpy erratic movement is removed
finally if a path has been set the vehicle is set to follow it
Definition at line 61 of file Vehicle.cpp.
References SteeringBehaviour::calculatePrioritizedSum(), followPath(), MovingEntity::getHeading(), MovingEntity::m_heading, MovingEntity::m_mass, MovingEntity::m_maxSpeed, m_path, BaseGameEntity::m_pos, MovingEntity::m_side, m_smoothHeading, m_smoothingOn, m_steering, m_timeElapsed, MovingEntity::m_velocity, and smoothingUpdate().
{
  m_timeElapsed = time_elapsed;
  ngl::Vec3 SteeringForce;
  SteeringForce = m_steering->calculatePrioritizedSum();
  ngl::Vec3 acceleration = SteeringForce / m_mass;
  m_velocity += acceleration * time_elapsed;
  //velocity truncated by maxspeed
  if(m_velocity.lengthSquared() > m_maxSpeed * m_maxSpeed)
  {
    if(m_velocity.lengthSquared() == 0.0f)
    {
      std::cout<<"Velocity in vehicle update equals zero, can't normalise"<<std::endl;
    }
    else
    {
      m_velocity.normalize();
    }
   m_velocity = m_velocity * m_maxSpeed;
  }
  m_pos += m_velocity * time_elapsed;
  if(m_velocity.lengthSquared()>0.000000001)
  {
    ngl::Vec3 tempVel;
    tempVel = m_velocity;
    if(tempVel.lengthSquared() == 0.0f)
    {
      std::cout<<"tempVel in vehicle update equals zero, can't normalise"<<std::endl;
    }
    else
    {
      tempVel.normalize();
    }
    m_heading = tempVel;
    m_side = m_heading.cross(ngl::Vec3(0,1,0));
  }
  //smooth the vehicles heading
  if(m_smoothingOn == true);
  {
    m_smoothHeading = smoothingUpdate(getHeading());
    m_heading = m_smoothHeading;
  }
  // if the path has been set, set the vehicle to follow it
  if(m_path.size() != 0)
  {
    this->followPath();
  }
}
Member Data Documentation
ngl::Vec3 Vehicle::m_crosshair [protected]
The current crosshair.
Definition at line 163 of file Vehicle.h.
std::vector<ngl::Vec3> Vehicle::m_headingHistory [protected]
Vector to contain the past headings to use to average for smoothing.
Definition at line 188 of file Vehicle.h.
int Vehicle::m_nextSlot [protected]
Sets the number of the next slot in the heading history.
Definition at line 193 of file Vehicle.h.
std::vector<ngl::Vec3> Vehicle::m_path [protected]
The current path.
Definition at line 173 of file Vehicle.h.
int Vehicle::m_pathIndex [protected]
The current path index.
Definition at line 178 of file Vehicle.h.
int Vehicle::m_sampleSize [protected]
The number of past headings used to average and smooth.
Definition at line 198 of file Vehicle.h.
ngl::Vec3 Vehicle::m_smoothHeading [protected]
The smoothed heading.
Definition at line 183 of file Vehicle.h.
bool Vehicle::m_smoothingOn [protected]
Boolean: true if smoothing is on, false when smoothing is off.
Definition at line 203 of file Vehicle.h.
ngl::Vec3 Vehicle::m_squadCrosshair [protected]
The current squad crosshair.
Definition at line 168 of file Vehicle.h.
SteeringBehaviour* Vehicle::m_steering [protected]
Returns a pointer to the steering class.
Definition at line 153 of file Vehicle.h.
double Vehicle::m_timeElapsed [protected]
The time elapsed since the last tick.
Definition at line 158 of file Vehicle.h.
The documentation for this class was generated from the following files:
Vehicle.h
Vehicle.cpp