YOURPROJECTNAMEGOESHERE: SteeringBehaviour Class Reference
SteeringBehaviour Class Reference
#include <SteeringBehaviour.h>
Public Member Functions
SteeringBehaviour (Vehicle *_agent)
Steering Behaviour ctor that initializes variables and entity manager.
~SteeringBehaviour ()
Steering Behaviour dtor.
void SeekOn ()
Sets seek to on state.
void SeekOff ()
Sets seek to off state.
bool isSeekOn ()
Returns if seek is on.
void setSeekWeight (const double _newWeight)
Sets the weight of seek.
double getSeekWeight () const
Gets the weight of seek.
void FleeOn ()
Sets flee to on state.
void FleeOff ()
Sets flee to off state.
bool isFleeOn ()
Returns if flee is on.
void setFleeWeight (const double _newWeight)
Sets the weight of flee.
double getFleeWeight () const
Gets the weight of flee.
void ArriveOn ()
Sets arrive to on state.
void ArriveOff ()
Sets arrive to off state.
bool isArriveOn ()
Returns if arrive is on.
void setArriveWeight (const double _newWeight)
Sets the weight of arrive.
double getArriveWeight () const
Gets the weight of arrive.
void WanderOn ()
Sets wander to on state.
void WanderOff ()
Sets wander to off state.
bool isWanderOn ()
Returns if wander is on.
void setWanderWeight (const double _newWeight)
Sets the weight of wander.
double getWanderWeight () const
Gets the weight of wander.
void SeparationOn ()
Sets separation to on state.
void SeparationOff ()
Sets separation to off state.
bool isSeparationOn ()
Returns if separation is on.
void setSeparationWeight (const double _newWeight)
Sets the weight of separation.
double getSeparationWeight () const
Gets the weight of separation.
void AlignmentOn ()
Sets alignment to on state.
void AlignmentOff ()
Sets alignment to off state.
bool isAlignmentOn ()
Returns if alignment is on.
void setAlignmentWeight (const double _newWeight)
Sets the weight of alignment.
double getAlignmentWeight () const
Gets the weight of alignment.
void CohesionOn ()
Sets cohesion to on state.
void CohesionOff ()
Sets cohesion to off state.
bool isCohesionOn ()
Returns if cohesion is on.
void setCohesionWeight (const double _newWeight)
Sets the weight of cohesion.
double getCohesionWeight () const
Gets the weight of cohesion.
void SquadCohesionOn ()
Sets squad cohesion to on state.
void SquadCohesionOff ()
Sets squad cohesion to off state.
bool isSquadCohesionOn ()
Returns if squad cohesion is on.
void setSquadCohesionWeight (const double _newWeight)
Sets the weight of squad cohesion.
double getSquadCohesionWeight () const
Gets the weight of squad cohesion.
void PursuitOn ()
Sets pursuit to on state.
void PursuitOff ()
Sets pursuit to off state.
bool isPursuitOn ()
Returns if pursuit is on.
void setPursuitWeight (const double _newWeight)
Sets the weight of pursuit.
double getPursuitWeight () const
Gets the weight of pursuit.
void EvadeOn ()
Sets evade to on state.
void EvadeOff ()
Sets evade to off state.
bool isEvadeOn ()
Returns if evade is on.
void setEvadeWeight (const double _newWeight)
Sets the weight of evade.
double getEvadeWeight () const
Gets the weight of evade.
void ObstacleAvoidOn ()
Sets obstacle avoidance to on state.
void ObstacleAvoidOff ()
Sets obstacle avoidance to off state.
bool isObstacleAvoidOn ()
Returns if obstacle avoidance is on.
void setObstacleAvoidWeight (const double _newWeight)
Sets the weight of obstacle avoidance.
double getObstacleAvoidWeight () const
Sets obstacle avoidance to on state.
void WallAvoidOn ()
Sets wall avoidance to on state.
void WallAvoidOff ()
Sets wall avoidance to off state.
bool isWallAvoidOn ()
Returns if wall avoidance is on.
void setWallAvoidWeight (const double _newWeight)
Sets the weight of wall avoidance.
double getWallAvoidWeight () const
Gets the weight of wall avoidance.
void setTargetAgent (Vehicle *_agent)
Sets the target agent for pursuit and evade.
void addFriendlyNeighbours (std::vector< int > _neighbours)
Adds IDs of the neighbours to the m_friendlyNeighbours vector.
void clearFriendlyNeighbours ()
Clears the m_friendlyNeighbours vector.
void addAllNeighbours (std::vector< int > _neighbours)
Adds IDs of the neighbours to the m_allNeighbours vector.
void clearAllNeighbours ()
Clears the m_allNeighbours vector.
bool lineIntersection2D (ngl::Vec3 startLineA, ngl::Vec3 endLineA, ngl::Vec3 startLineB, ngl::Vec3 endLineB, double &o_distToIntersect, ngl::Vec3 &o_intersectPoint)
Returns if two lines intersect.
ngl::Vec3 calculatePrioritizedSum ()
Sums together all the steering forces in a prioritized list.
bool accumulateForce (ngl::Vec3 currentTotal, ngl::Vec3 &force)
Used in calculating the steering force to make sure it does not exceed the maximum force.
void ObjectOverlapAvoidance ()
Calculates the overlap for obstacle avoidance.
void WallOverlapAvoidance ()
Calculates the overlap for wall avoidance.
Private Types
enum behaviour_type {
seek = 0x00002, flee = 0x00004, arrive = 0x00008, wander = 0x00010,
cohesion = 0x00020, separation = 0x00040, alignment = 0x00080, obstacle_avoidance = 0x00100,
wall_avoidance = 0x00200, pursuit = 0x00800, evade = 0x01000, squad_cohesion = 0x02000
}
enumerate the list of behaviours
Private Member Functions
bool on (behaviour_type bt)
Returns if a steering behaviour is set to on.
ngl::Vec3 Seek (ngl::Vec3 targetPos)
Seek behaviour type.
ngl::Vec3 Flee (ngl::Vec3 targetPos)
Flee behaviour type.
ngl::Vec3 Arrive (ngl::Vec3 targetPos, int deceleration)
Arrive behaviour type.
ngl::Vec3 Wander ()
Wander behaviour type.
ngl::Vec3 Pursuit (const Vehicle *agent)
Pursuit behaviour type.
ngl::Vec3 Evade (const Vehicle *agent)
Evade behaviour type.
ngl::Vec3 Separation (std::vector< int > neighbours)
Separation behaviour type.
ngl::Vec3 Alignment (std::vector< int > neighbours)
Alignment behaviour type.
ngl::Vec3 Cohesion (std::vector< int > neighbours)
Cohesion behaviour type.
ngl::Vec3 SquadCohesion (ngl::Vec3 squadPos, int deceleration)
Squad Cohesion behaviour type.
ngl::Vec3 ObstacleAvoidance ()
Obstacle Avoidance behaviour.
ngl::Vec3 WallAvoidance ()
Wall Avoidance behaviour.
ngl::Vec3 worldToLocalSpace (ngl::Vec3 pointWorldPos, ngl::Vec3 vehiclePos, ngl::Vec3 vehicleHeading, ngl::Vec3 vehicleSide)
Convert from world to local space.
Private Attributes
EntityManager * m_entityMgr
Pointer to the Entity Manage monostate.
Vehicle * m_vehicle
Pointer to the current vehicle.
int m_activeFlags
Int number of active flags for steering behaviours.
ngl::Vec3 m_steeringForce
Vecs for the accumulation of steering behaviour forces.
Vehicle * m_targetAgent
Vehicle Pointer to the target agent.
float m_wanderDistance
Float for the distance of wander.
float m_wanderRadius
Float for the radius of wander.
float m_wanderJitter
Float for the jitter amount of wander.
int m_deceleration
Int for the amount of deceleration.
ngl::Vec3 m_wanderTarget
Vec3 for the wander target.
std::vector< int > m_friendlyNeighbours
Vector to contain the IDs of the friendly neighbours.
std::vector< int > m_allNeighbours
Vector to contain the IDs of all the neighbours.
double m_weightSeek
The weight of seek.
double m_weightFlee
The weight of flee.
double m_weightArrive
The weight of arrive.
double m_weightWander
The weight of wander.
double m_weightCohesion
The weight of cohesion.
double m_weightSeparation
The weight of separation.
double m_weightAlignment
The weight of alignment.
double m_weightObstacleAvoidance
The weight of obstacle avoidance.
double m_weightWallAvoidance
The weight of wall avoidance.
double m_weightPursuit
The weight of pursuit.
double m_weightEvade
The weight of evade.
double m_weightSquadCohesion
The weight of squad cohesion.
Detailed Description
Definition at line 26 of file SteeringBehaviour.h.
Member Enumeration Documentation
enum SteeringBehaviour::behaviour_type [private]
enumerate the list of behaviours
Enumerator:
seek
flee
arrive
wander
cohesion
separation
alignment
obstacle_avoidance
wall_avoidance
pursuit
evade
squad_cohesion
Definition at line 406 of file SteeringBehaviour.h.
  {
      seek               = 0x00002, //0
      flee               = 0x00004, //1
      arrive             = 0x00008, //2
      wander             = 0x00010, //3
      cohesion           = 0x00020, //4
      separation         = 0x00040, //5
      alignment          = 0x00080, //6
      obstacle_avoidance = 0x00100, //7
      wall_avoidance     = 0x00200, //8
      pursuit            = 0x00800, //9
      evade              = 0x01000, //10
      squad_cohesion     = 0x02000, //11
  };
Constructor & Destructor Documentation
SteeringBehaviour::SteeringBehaviour (Vehicle * _agent)
Steering Behaviour ctor that initializes variables and entity manager.
Parameters:
[in] agent,: pass in the vehicle to utilise the behaviours
Definition at line 13 of file SteeringBehaviour.cpp.
References m_entityMgr, m_targetAgent, m_wanderRadius, and m_wanderTarget.
                                                   :
  m_vehicle(_agent),
  m_activeFlags(0),
  m_wanderDistance(3.0),
  m_wanderRadius(1.0),
  m_wanderJitter(10.0),
  m_weightSeek(1.0),
  m_weightFlee(1.0),
  m_weightArrive(1.0),
  m_weightWander(1.0),
  m_weightCohesion(1.0),
  m_weightSeparation(1.0),
  m_weightAlignment(1.0),
  m_weightObstacleAvoidance(1.0),
  m_weightWallAvoidance(1.0),
  m_weightPursuit(1.0),
  m_weightEvade(1.0)
{
  m_entityMgr = new EntityManager();
  double theta = (float)rand()/RAND_MAX * (M_PI * 2);
  m_wanderTarget = ngl::Vec3(m_wanderRadius * cos(theta), 0, m_wanderRadius * sin(theta));
  m_targetAgent = NULL;
}
SteeringBehaviour::~SteeringBehaviour ()
Steering Behaviour dtor.
Definition at line 40 of file SteeringBehaviour.cpp.
{
  //delete m_entityMgr;
}
Member Function Documentation
bool SteeringBehaviour::accumulateForce (ngl::Vec3 currentTotal, ngl::Vec3 & force)
Used in calculating the steering force to make sure it does not exceed the maximum force.
Adds together steering forces, making sure does not exceed the maximum force.
Parameters:
[in] currentTotal,: the running total of the steering forces
[out] force,: the force to be added, returns maximum amount it can fit within maximum force
Returns:
Boolean: returns true if force can be added, false if it cannot
Definition at line 225 of file SteeringBehaviour.cpp.
References MovingEntity::getMaxForce(), and m_vehicle.
{
  double magnitude = currentTotal.length();
  double forceLeft =  m_vehicle->getMaxForce() - magnitude;
  if(forceLeft < 0.0)
  {
    return false;
  }
  else if(force.lengthSquared() > (forceLeft * forceLeft))
  {
    if(force.lengthSquared() == 0.0f)
    {
      std::cout<<"Force in accumulate force equals zero, can't normalise"<<std::endl;
    }
    else
    {
      force.normalize();
    }
    force *= m_vehicle->getMaxForce();
    return true;
  }
  else
  {
    return true;
  }
}
void SteeringBehaviour::addAllNeighbours (std::vector< int > _neighbours)
Adds IDs of the neighbours to the m_allNeighbours vector.
Parameters:
[in] _neighbours,: vector of ints that stores the IDs of neighbours
Definition at line 724 of file SteeringBehaviour.cpp.
References m_allNeighbours.
{
  for (int i = 0; i < _neighbours.size(); i++)
  {
    m_allNeighbours.push_back(_neighbours[i]);
  }
}
void SteeringBehaviour::addFriendlyNeighbours (std::vector< int > _neighbours)
Adds IDs of the neighbours to the m_friendlyNeighbours vector.
Parameters:
[in] _neighbours,: vector of ints that stores the IDs of neighbours
Definition at line 735 of file SteeringBehaviour.cpp.
References m_friendlyNeighbours.
{
  for (unsigned int i = 0; i < _neighbours.size(); i++)
  {
    m_friendlyNeighbours.push_back(_neighbours[i]);
  }
}
ngl::Vec3 SteeringBehaviour::Alignment (std::vector< int > neighbours) [private]
Alignment behaviour type.
Alignment - finds the average heading of the surrounding neighbours.
Parameters:
[in] neighbours,: vector of ints to contain the IDs of the neighbours
Returns:
Vec3: the steering force
Definition at line 428 of file SteeringBehaviour.cpp.
References EntityManager::getEntityFromID(), MovingEntity::getHeading(), m_entityMgr, and m_vehicle.
{
  if (neighbours.size() > 0)
  {
    ngl::Vec3 averageHeading;
    for (unsigned int i = 0; i < neighbours.size(); i++)
    {
      Vehicle* vehicleNeighbour = dynamic_cast<Vehicle*>(m_entityMgr->getEntityFromID(neighbours[i]));
      if (vehicleNeighbour)
      {
        averageHeading += vehicleNeighbour->getHeading();
      }
    }
    averageHeading /= neighbours.size();
    averageHeading -= m_vehicle->getHeading();
    return averageHeading;
  }
  else
  {
    return ngl::Vec3(0.f, 0.f, 0.f);
  }
}
void SteeringBehaviour::AlignmentOff () [inline]
Sets alignment to off state.
Definition at line 173 of file SteeringBehaviour.h.
References alignment, m_activeFlags, and on().
{if(on(alignment)) m_activeFlags ^= alignment;}
void SteeringBehaviour::AlignmentOn () [inline]
Sets alignment to on state.
Definition at line 169 of file SteeringBehaviour.h.
References alignment, and m_activeFlags.
{m_activeFlags |= alignment;}
ngl::Vec3 SteeringBehaviour::Arrive (ngl::Vec3 targetPos, int deceleration) [private]
Arrive behaviour type.
Parameters:
[in] targetPos,: vector of the target position
[in] deceleration,: the amount to decelerate by
Returns:
Vec3: the steering force
Arrive - returns vector towards the target position, but as it gets closer the forces lowers so the vehicle decelerates
Definition at line 282 of file SteeringBehaviour.cpp.
References MovingEntity::getMaxSpeed(), BaseGameEntity::getPos(), MovingEntity::getVelocity(), and m_vehicle.
{
  ngl::Vec3 toTarget = targetPos - m_vehicle->getPos();
  double dist = toTarget.length();
  if(dist>0.1)
  {
    double decelerationTweak = 0.01;
    double speed = dist/(deceleration*decelerationTweak);
    //make velocity not exceed maxspeed
    if( speed > m_vehicle->getMaxSpeed())
    {
      speed = m_vehicle->getMaxSpeed();
    }
    ngl::Vec3 desiredVelocity = toTarget * speed/dist;
    return(desiredVelocity - m_vehicle->getVelocity());
  }
  else if(dist <= 0.1 )
  {
    return ngl::Vec3(0,0,0);
  }
  return ngl::Vec3(0,0,0);
}
void SteeringBehaviour::ArriveOff () [inline]
Sets arrive to off state.
Definition at line 98 of file SteeringBehaviour.h.
References arrive, m_activeFlags, and on().
{if(on(arrive)) m_activeFlags ^= arrive;}
void SteeringBehaviour::ArriveOn () [inline]
Sets arrive to on state.
Definition at line 94 of file SteeringBehaviour.h.
References arrive, and m_activeFlags.
{m_activeFlags |= arrive;}
ngl::Vec3 SteeringBehaviour::calculatePrioritizedSum ()
Sums together all the steering forces in a prioritized list.
Returns:
Vec3: the steering force vector
Calculates total steering force by ordering behaviours by priority Each force is added to the steering if there is enough max force left over (AccumulateForce function)
Definition at line 49 of file SteeringBehaviour.cpp.
References accumulateForce(), Alignment(), alignment, Arrive(), arrive, Cohesion(), cohesion, Evade(), evade, Flee(), flee, Vehicle::getCrosshair(), Vehicle::getSquadCrosshair(), m_allNeighbours, m_friendlyNeighbours, m_steeringForce, m_targetAgent, m_vehicle, m_weightAlignment, m_weightArrive, m_weightCohesion, m_weightEvade, m_weightFlee, m_weightObstacleAvoidance, m_weightPursuit, m_weightSeek, m_weightSeparation, m_weightSquadCohesion, m_weightWallAvoidance, m_weightWander, obstacle_avoidance, ObstacleAvoidance(), on(), Pursuit(), pursuit, Seek(), seek, Separation(), separation, squad_cohesion, SquadCohesion(), wall_avoidance, WallAvoidance(), Wander(), and wander.
{
  m_steeringForce = ngl::Vec3(0.f, 0.f, 0.f);
  ngl::Vec3 force;
  if(on(wall_avoidance))
  {
    force = WallAvoidance() * m_weightWallAvoidance;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  if(on(obstacle_avoidance))
  {
    force = ObstacleAvoidance() * m_weightObstacleAvoidance;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  if(on(separation))
  {
    force = Separation(m_allNeighbours) * m_weightSeparation;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  if(on(cohesion))
  {
    force = Cohesion(m_friendlyNeighbours) * m_weightCohesion;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  if(on(alignment))
  {
    force = Alignment(m_friendlyNeighbours) * m_weightAlignment;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  if(on(pursuit))
  {
    if (m_targetAgent != NULL)
    {
      force = Pursuit(m_targetAgent) * m_weightPursuit;
      if(!accumulateForce(m_steeringForce, force))
      {
        return m_steeringForce;
      }
      else
      {
        m_steeringForce += force;
      }
    }
  }
  if(on(evade))
  {
    if (m_targetAgent != NULL)
    {
      force = Evade(m_targetAgent) * m_weightEvade;
      if(!accumulateForce(m_steeringForce, force))
      {
        return m_steeringForce;
      }
      else
      {
        m_steeringForce += force;
      }
    }
  }
  if(on(seek))
  {
    force = Seek(m_vehicle->getCrosshair()) * m_weightSeek;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  if(on(flee))
  {
    force = Flee(m_vehicle->getCrosshair()) * m_weightFlee;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  if(on(arrive))
  {
    force = Arrive(m_vehicle->getCrosshair(), 0.1) * m_weightArrive;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  if(on(squad_cohesion))
  {
    force = SquadCohesion(m_vehicle->getSquadCrosshair(), 0.5) * m_weightSquadCohesion;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  if(on(wander))
  {
    force = Wander() * m_weightWander;
    if(!accumulateForce(m_steeringForce, force))
    {
      return m_steeringForce;
    }
    else
    {
      m_steeringForce += force;
    }
  }
  return m_steeringForce;
}
void SteeringBehaviour::clearAllNeighbours () [inline]
Clears the m_allNeighbours vector.
Definition at line 365 of file SteeringBehaviour.h.
References m_allNeighbours.
{ m_allNeighbours.clear(); }
void SteeringBehaviour::clearFriendlyNeighbours () [inline]
Clears the m_friendlyNeighbours vector.
Definition at line 355 of file SteeringBehaviour.h.
References m_friendlyNeighbours.
{ m_friendlyNeighbours.clear(); }
ngl::Vec3 SteeringBehaviour::Cohesion (std::vector< int > neighbours) [private]
Cohesion behaviour type.
Cohesion - finds the average position of the vehicles neighbours and seeks to that point.
Parameters:
[in] neighbours,: vector of ints to contain the IDs of the neighbours
Returns:
Vec3: the steering force
Definition at line 454 of file SteeringBehaviour.cpp.
References EntityManager::getEntityFromID(), BaseGameEntity::getPos(), m_entityMgr, and Seek().
{
  if (neighbours.size() > 0)
  {
    ngl::Vec3 averagePosition;
    ngl::Vec3 cohesionForce;
    for (unsigned int i =0; i < neighbours.size(); i++)
    {
      averagePosition += m_entityMgr->getEntityFromID(neighbours[i])->getPos();
    }
    averagePosition /= neighbours.size();
    cohesionForce = Seek(averagePosition);
    return cohesionForce;
  }
  else
  {
    return ngl::Vec3(0.f, 0.f, 0.f);
  }
}
void SteeringBehaviour::CohesionOff () [inline]
Sets cohesion to off state.
Definition at line 198 of file SteeringBehaviour.h.
References cohesion, m_activeFlags, and on().
{if(on(cohesion)) m_activeFlags ^= cohesion;}
void SteeringBehaviour::CohesionOn () [inline]
Sets cohesion to on state.
Definition at line 194 of file SteeringBehaviour.h.
References cohesion, and m_activeFlags.
{m_activeFlags |= cohesion;}
ngl::Vec3 SteeringBehaviour::Evade (const Vehicle * agent) [private]
Evade behaviour type.
Parameters:
[in] agent,: pointer to the target agent
Returns:
Vec3: the steering force
Evade - uses flee to evade a moving vehicle, but uses heading so it can calculate where the vehicle will be in the future and avoid that point
Definition at line 389 of file SteeringBehaviour.cpp.
References Flee(), MovingEntity::getMaxSpeed(), BaseGameEntity::getPos(), MovingEntity::getSpeed(), MovingEntity::getVelocity(), and m_vehicle.
{
  ngl::Vec3 toAgent = agent->getPos() - m_vehicle->getPos();
  double lookAheadTime = toAgent.length() / (m_vehicle->getMaxSpeed() + agent->getSpeed());
  ngl::Vec3 agentPos = agent->getPos() + (agent->getVelocity() * lookAheadTime);
  return Flee(agentPos);
}
void SteeringBehaviour::EvadeOff () [inline]
Sets evade to off state.
Definition at line 273 of file SteeringBehaviour.h.
References evade, m_activeFlags, and on().
{if(on(evade)) m_activeFlags ^= evade;}
void SteeringBehaviour::EvadeOn () [inline]
Sets evade to on state.
Definition at line 269 of file SteeringBehaviour.h.
References evade, and m_activeFlags.
{m_activeFlags |= evade;}
ngl::Vec3 SteeringBehaviour::Flee (ngl::Vec3 targetPos) [private]
Flee behaviour type.
Flee - returns vector directing away from the target position.
Parameters:
[in] targetPos,: vector of the target position
Returns:
Vec3: the steering force
Definition at line 271 of file SteeringBehaviour.cpp.
References BaseGameEntity::getPos(), MovingEntity::getVelocity(), and m_vehicle.
{
  ngl::Vec3 desiredVelocity = ngl::Vec3(m_vehicle->getPos() - targetPos);
  return desiredVelocity - m_vehicle->getVelocity();
}
void SteeringBehaviour::FleeOff () [inline]
Sets flee to off state.
Definition at line 73 of file SteeringBehaviour.h.
References flee, m_activeFlags, and on().
{if(on(flee)) m_activeFlags ^= flee;}
void SteeringBehaviour::FleeOn () [inline]
Sets flee to on state.
Definition at line 69 of file SteeringBehaviour.h.
References flee, and m_activeFlags.
{m_activeFlags |= flee;}
double SteeringBehaviour::getAlignmentWeight () const [inline]
Gets the weight of alignment.
Returns:
Double: the weight of alignment
Definition at line 188 of file SteeringBehaviour.h.
References m_weightAlignment.
{return m_weightAlignment;}
double SteeringBehaviour::getArriveWeight () const [inline]
Gets the weight of arrive.
Returns:
Double: the weight of arrive
Definition at line 113 of file SteeringBehaviour.h.
References m_weightArrive.
{return m_weightArrive;}
double SteeringBehaviour::getCohesionWeight () const [inline]
Gets the weight of cohesion.
Returns:
Double: the weight of alignment
Definition at line 213 of file SteeringBehaviour.h.
References m_weightCohesion.
{return m_weightCohesion;}
double SteeringBehaviour::getEvadeWeight () const [inline]
Gets the weight of evade.
Returns:
Double: the weight of evade
Definition at line 288 of file SteeringBehaviour.h.
References m_weightEvade.
{return m_weightEvade;}
double SteeringBehaviour::getFleeWeight () const [inline]
Gets the weight of flee.
Returns:
Double: the weight of flee
Definition at line 88 of file SteeringBehaviour.h.
References m_weightFlee.
{return m_weightFlee;}
double SteeringBehaviour::getObstacleAvoidWeight () const [inline]
Sets obstacle avoidance to on state.
Returns:
Double: the weight of obstacle avoidance
Definition at line 313 of file SteeringBehaviour.h.
References m_weightObstacleAvoidance.
{return m_weightObstacleAvoidance;}
double SteeringBehaviour::getPursuitWeight () const [inline]
Gets the weight of pursuit.
Returns:
Double: the weight of pursuit
Definition at line 263 of file SteeringBehaviour.h.
References m_weightPursuit.
{return m_weightPursuit;}
double SteeringBehaviour::getSeekWeight () const [inline]
Gets the weight of seek.
Returns:
Double: the weight of seek
Definition at line 63 of file SteeringBehaviour.h.
References m_weightSeek.
{return m_weightSeek;}
double SteeringBehaviour::getSeparationWeight () const [inline]
Gets the weight of separation.
Returns:
Double: the weight of separation
Definition at line 163 of file SteeringBehaviour.h.
References m_weightSeparation.
{return m_weightSeparation;}
double SteeringBehaviour::getSquadCohesionWeight () const [inline]
Gets the weight of squad cohesion.
Returns:
Double: the weight of alignment
Definition at line 238 of file SteeringBehaviour.h.
References m_weightSquadCohesion.
{return m_weightSquadCohesion;}
double SteeringBehaviour::getWallAvoidWeight () const [inline]
Gets the weight of wall avoidance.
Returns:
Double: the weight of wall avoidance
Definition at line 338 of file SteeringBehaviour.h.
References m_weightWallAvoidance.
{return m_weightWallAvoidance;}
double SteeringBehaviour::getWanderWeight () const [inline]
Gets the weight of wander.
Returns:
Double: the weight of wander
Definition at line 138 of file SteeringBehaviour.h.
References m_weightWander.
{return m_weightWander;}
bool SteeringBehaviour::isAlignmentOn () [inline]
Returns if alignment is on.
Returns:
Boolean: true if alignment is on, false if alignment is off
Definition at line 178 of file SteeringBehaviour.h.
References alignment, and on().
{return on(alignment);}
bool SteeringBehaviour::isArriveOn () [inline]
Returns if arrive is on.
Returns:
Boolean: true if arrive is on, false if arrive is off
Definition at line 103 of file SteeringBehaviour.h.
References arrive, and on().
{return on(arrive);}
bool SteeringBehaviour::isCohesionOn () [inline]
Returns if cohesion is on.
Returns:
Boolean: true if cohesion is on, false if cohesion is off
Definition at line 203 of file SteeringBehaviour.h.
References cohesion, and on().
{return on(cohesion);}
bool SteeringBehaviour::isEvadeOn () [inline]
Returns if evade is on.
Returns:
Boolean: true if evade is on, false if evade is off
Definition at line 278 of file SteeringBehaviour.h.
References evade, and on().
{return on(evade);}
bool SteeringBehaviour::isFleeOn () [inline]
Returns if flee is on.
Returns:
Boolean: true if flee is on, false if flee is off
Definition at line 78 of file SteeringBehaviour.h.
References flee, and on().
{return on(flee);}
bool SteeringBehaviour::isObstacleAvoidOn () [inline]
Returns if obstacle avoidance is on.
Returns:
Boolean: true if obstacle avoidance is on, false if obstacle avoidance is off
Definition at line 303 of file SteeringBehaviour.h.
References obstacle_avoidance, and on().
{ return on(obstacle_avoidance); }
bool SteeringBehaviour::isPursuitOn () [inline]
Returns if pursuit is on.
Returns:
Boolean: true if pursuit is on, false if pursuit is off
Definition at line 253 of file SteeringBehaviour.h.
References on(), and pursuit.
{return on(pursuit);}
bool SteeringBehaviour::isSeekOn () [inline]
Returns if seek is on.
Returns:
Boolean: true if seek is on, false if seek is off
Definition at line 53 of file SteeringBehaviour.h.
References on(), and seek.
{return on(seek);}
bool SteeringBehaviour::isSeparationOn () [inline]
Returns if separation is on.
Returns:
Boolean: true if separation is on, false if separation is off
Definition at line 153 of file SteeringBehaviour.h.
References on(), and separation.
{return on(separation);}
bool SteeringBehaviour::isSquadCohesionOn () [inline]
Returns if squad cohesion is on.
Returns:
Boolean: true if squad cohesion is on, false if squad cohesion is off
Definition at line 228 of file SteeringBehaviour.h.
References on(), and squad_cohesion.
{return on(squad_cohesion);}
bool SteeringBehaviour::isWallAvoidOn () [inline]
Returns if wall avoidance is on.
Returns:
Boolean: true if wall avoidance is on, false if wall avoidance is off
Definition at line 328 of file SteeringBehaviour.h.
References on(), and wall_avoidance.
{ return on(wall_avoidance); }
bool SteeringBehaviour::isWanderOn () [inline]
Returns if wander is on.
Returns:
Boolean: true if wander is on, false if wander is off
Definition at line 128 of file SteeringBehaviour.h.
References on(), and wander.
{return on(wander);}
bool SteeringBehaviour::lineIntersection2D (ngl::Vec3 startLineA, ngl::Vec3 endLineA, ngl::Vec3 startLineB, ngl::Vec3 endLineB, double & o_distToIntersect, ngl::Vec3 & o_intersectPoint)
Returns if two lines intersect.
Parameters:
[in] startLineA,: the start vector of the first line
[in] endLineA,: the end vector of the first line
[in] startLineB,: the start vector of the second line
[in] endLineB,: the end vector of the second line
[out] o_distToIntersect,: the distance to the intersection
[out] o_intersectPoint,: the vector of the point of intersection
Returns:
Boolean: returns true if the two lines intersect, false if they do not
this method uses the equations from http://paulbourke.net/geometry/pointlineplane/ to determin wether two 2D lines intersect. It also calculates the interesection point and the distance to the interesections point.
Definition at line 748 of file SteeringBehaviour.cpp.
{
  double rTop = (startLineA.m_z-startLineB.m_z)*(endLineB.m_x-startLineB.m_x)-(startLineA.m_x-startLineB.m_x)*(endLineB.m_z-startLineB.m_z);
  double rBot = (endLineA.m_x-startLineA.m_x)*(endLineB.m_z-startLineB.m_z)-(endLineA.m_z-startLineA.m_z)*(endLineB.m_x-startLineB.m_x);
  double sTop = (startLineA.m_z-startLineB.m_z)*(endLineA.m_x-startLineA.m_x)-(startLineA.m_x-startLineB.m_x)*(endLineA.m_z-startLineA.m_z);
  double sBot = (endLineA.m_x-startLineA.m_x)*(endLineB.m_z-startLineB.m_z)-(endLineA.m_z-startLineA.m_z)*(endLineB.m_x-startLineB.m_x);
  if ((rBot == 0) || (sBot == 0))
  {
    return false;
  }
  double r = rTop/rBot;
  double s = sTop/sBot;
  if ((r > 0.0) && (r < 1.0) && (s > 0.0) && (s < 1.0))
  {
    ngl::Vec3 lineA = endLineA - startLineA;
    o_distToIntersect = lineA.length() * r;
    o_intersectPoint = startLineA + (r * (endLineA - startLineA));
    return true;
  }
  else
  {
    //dist = 0.0;
    return false;
  }
}
void SteeringBehaviour::ObjectOverlapAvoidance ()
Calculates the overlap for obstacle avoidance.
this object overlap avoidance method stops objects from overalpping by comparing the distance between them against the sum of their radii. If the distance is less than their radii sum then they two entities are moved apart in the direction of the vector between them by a distance equal to the amount of overlap#
Definition at line 784 of file SteeringBehaviour.cpp.
References BaseGameEntity::getBoundingRadius(), EntityManager::getEntityFromID(), BaseGameEntity::getID(), BaseGameEntity::getNeighbourObstacleIDs(), BaseGameEntity::getPos(), m_allNeighbours, m_entityMgr, m_vehicle, and BaseGameEntity::setPos().
{
  int numberOfNeighbours = m_allNeighbours.size();
  for (unsigned int i = 0; i < numberOfNeighbours; i++)
  {
    Vehicle* curEntity = dynamic_cast<Vehicle*>(m_entityMgr->getEntityFromID(m_allNeighbours[i]));
    if (curEntity)
    {
      //make sure we don't check against ourselves
      Vehicle* entity = dynamic_cast<Vehicle*>(m_entityMgr->getEntityFromID(m_vehicle->getID()));
      if (curEntity == entity) continue;
      ngl::Vec3 vecToEntity = m_vehicle->getPos() - curEntity->getPos();
      double distFromEachOther = vecToEntity.length();
      double amountOfOverLap = (m_vehicle->getBoundingRadius() + curEntity->getBoundingRadius()) - distFromEachOther;
      if (amountOfOverLap >= 0)
      {
        m_vehicle->setPos(m_vehicle->getPos() + (vecToEntity/distFromEachOther) * amountOfOverLap);
      }
     }
  }
  for (unsigned int i = 0; i < m_vehicle->getNeighbourObstacleIDs().size(); i++)
  {
    StaticEntity* curEntity = dynamic_cast<StaticEntity*>(m_entityMgr->getEntityFromID(m_vehicle->getNeighbourObstacleIDs()[i]));
    if (curEntity)
    {
      ngl::Vec3 vecToEntity = m_vehicle->getPos() - curEntity->getPos();
      double distFromEachOther = vecToEntity.length();
      double amountOfOverLap = (m_vehicle->getBoundingRadius() + curEntity->getBoundingRadius()) - distFromEachOther;
      if (amountOfOverLap >= 0)
      {
        m_vehicle->setPos(m_vehicle->getPos() + (vecToEntity/distFromEachOther) * amountOfOverLap);
      }
    }
  }
}
ngl::Vec3 SteeringBehaviour::ObstacleAvoidance () [private]
Obstacle Avoidance behaviour.
Returns:
Vec3: the steering force
Obstacle Avoidance - A detection length is generated based on a minimum length plus the ratio between current speed and max entity speed. A detection box is created with length of detection length and width of entity radius multiplied by 2. All other entities that are within the detection box plus their own radius are compared to find the closest entity. The steering force is calculated from the distance to the closest other entity in the local x and z direction. This local force is then converted into world space.
Definition at line 516 of file SteeringBehaviour.cpp.
References BaseGameEntity::getBoundingRadius(), EntityManager::getEntityFromID(), MovingEntity::getHeading(), MovingEntity::getMaxSpeed(), BaseGameEntity::getNeighbourObstacleIDs(), BaseGameEntity::getPos(), MovingEntity::getSide(), MovingEntity::getSpeed(), m_entityMgr, m_vehicle, and worldToLocalSpace().
{
  //const std::vector<BaseGameEntity *> &obstacles
  float minDetectionLength = m_vehicle->getBoundingRadius() * 1.5;
  float detectionLength = minDetectionLength + ((m_vehicle->getSpeed() / m_vehicle->getMaxSpeed()) * minDetectionLength);
  BaseGameEntity* closestIntersectingObstacle = NULL;
  double distanceToCIO = 99999.9;
  ngl::Vec3 localPosOfCIO;
  int numberOfObstacles = m_vehicle->getNeighbourObstacleIDs().size();
  for (unsigned int i = 0; i < numberOfObstacles; ++i)
  {
    StaticEntity* currentObstacle = dynamic_cast<StaticEntity*>(m_entityMgr->getEntityFromID(m_vehicle->getNeighbourObstacleIDs()[i]));
    if (currentObstacle)
    {
      ngl::Vec3 vectorToObstacle = currentObstacle->getPos() - m_vehicle->getPos();
      if (vectorToObstacle.length() < detectionLength)
        {
          ngl::Vec3 localPos = worldToLocalSpace(currentObstacle->getPos(), m_vehicle->getPos(), m_vehicle->getHeading(), m_vehicle->getSide());
          // if obstacle is behind vehicle in local space, discard
          if (localPos.m_x >= 0.f)
          {
            double addedRadius = currentObstacle->getBoundingRadius() + m_vehicle->getBoundingRadius();
            if (fabs(localPos.m_z) < addedRadius)
            {
              // intersection of radius and line z = 0
              // x = cx +- sqrt(addedRadius^2 - cz^2) where cx and cz are centre coordinates
              double sqrtPart = sqrt(addedRadius*addedRadius - localPos.m_z*localPos.m_z);
              double intersectX = localPos.m_x - sqrtPart;
              if (intersectX <= 0)
              {
                intersectX = localPos.m_x + sqrtPart;
              }
              if (intersectX < distanceToCIO)
              {
                distanceToCIO = intersectX;
                closestIntersectingObstacle = currentObstacle;
                localPosOfCIO = localPos;
              }
            }
        }
      }
    }
  }
  if (closestIntersectingObstacle)
  {
    double mult = 1.0 + (detectionLength - localPosOfCIO.m_x) / detectionLength;
    ngl::Vec3 avoidanceForce;
    if (localPosOfCIO.m_z >= 0)
    {
      avoidanceForce.m_z = (-closestIntersectingObstacle->getBoundingRadius() + localPosOfCIO.m_z) * mult;
    }
    else if (localPosOfCIO.m_z < 0)
    {
      avoidanceForce.m_z = (closestIntersectingObstacle->getBoundingRadius() + localPosOfCIO.m_z) * mult;
    }
    //breaking force
    const double weightBreaking = 1.f;
    avoidanceForce.m_x = -(detectionLength - localPosOfCIO.m_x) * weightBreaking;
    // local to world space
    ngl::Vec3 headingNormalise;
    ngl::Vec3 worldNormalise = ngl::Vec3(1,0,0);
    headingNormalise = m_vehicle->getHeading();
    if(headingNormalise.lengthSquared() == 0.0f)
    {
      std::cout<<"headingNormalise in obstacle avoidance equals zero, can't normalise"<<std::endl;
    }
    else
    {
      headingNormalise.normalize();
    }
    double dotProduct = worldNormalise.dot(headingNormalise);
    double magnitude = headingNormalise.length()*worldNormalise.length();
    double temp = dotProduct/magnitude;
    double angle = acos(temp);
    if(headingNormalise.m_z > 0)
    {
      angle = 2*M_PI - angle;
    }
    ngl::Transformation trans;
    trans.setRotation(0, (-angle * 180)/M_PI, 0);
    ngl::Vec3 worldAvoidanceForce;
    worldAvoidanceForce = trans.getMatrix() * avoidanceForce;
    return worldAvoidanceForce;
  }
  return ngl::Vec3(0.f, 0.f, 0.f);
}
void SteeringBehaviour::ObstacleAvoidOff () [inline]
Sets obstacle avoidance to off state.
Definition at line 298 of file SteeringBehaviour.h.
References m_activeFlags, obstacle_avoidance, and on().
{ if(on(obstacle_avoidance)) m_activeFlags ^= obstacle_avoidance; }
void SteeringBehaviour::ObstacleAvoidOn () [inline]
Sets obstacle avoidance to on state.
Definition at line 294 of file SteeringBehaviour.h.
References m_activeFlags, and obstacle_avoidance.
{ m_activeFlags |= obstacle_avoidance; }
bool SteeringBehaviour::on (behaviour_type bt) [inline, private]
Returns if a steering behaviour is set to on.
Parameters:
[in] enum,: the behaviour type
Returns:
Boolean: returns true if the behaviour is on, false if it is not
Definition at line 487 of file SteeringBehaviour.h.
References m_activeFlags.
{return (m_activeFlags & bt) == bt;}
ngl::Vec3 SteeringBehaviour::Pursuit (const Vehicle * agent) [private]
Pursuit behaviour type.
Parameters:
[in] agent,: pointer to the target agent
Returns:
Vec3: the steering force
Pursuit - uses seek to pursue a moving vehicle, but uses heading so it can calculate where the vehicle will be in the future and aim for that point
Definition at line 371 of file SteeringBehaviour.cpp.
References MovingEntity::getHeading(), MovingEntity::getMaxSpeed(), BaseGameEntity::getPos(), MovingEntity::getSpeed(), MovingEntity::getVelocity(), m_vehicle, and Seek().
{
  ngl::Vec3 toAgent = agent->getPos() - m_vehicle->getPos();
  double relativeHeading = m_vehicle->getHeading().dot(agent->getHeading());
  if ((toAgent.dot(m_vehicle->getHeading().dot(agent->getHeading()))) && (relativeHeading < -0.95))
  {
    return Seek(agent->getPos());
  }
  double lookAheadTime = toAgent.length() / (m_vehicle->getMaxSpeed() + agent->getSpeed());
  return Seek(agent->getPos() + agent->getVelocity() * lookAheadTime);
}
void SteeringBehaviour::PursuitOff () [inline]
Sets pursuit to off state.
Definition at line 248 of file SteeringBehaviour.h.
References m_activeFlags, on(), and pursuit.
{if(on(pursuit)) m_activeFlags ^= pursuit;}
void SteeringBehaviour::PursuitOn () [inline]
Sets pursuit to on state.
Definition at line 244 of file SteeringBehaviour.h.
References m_activeFlags, and pursuit.
{m_activeFlags |= pursuit;}
ngl::Vec3 SteeringBehaviour::Seek (ngl::Vec3 targetPos) [private]
Seek behaviour type.
Seek - returns the vector toward to the target position.
Parameters:
[in] targetPos,: vector of the target position
Returns:
Vec3: the steering force
Definition at line 260 of file SteeringBehaviour.cpp.
References BaseGameEntity::getPos(), MovingEntity::getVelocity(), and m_vehicle.
{
  ngl::Vec3 desiredVelocity = ngl::Vec3(targetPos - m_vehicle->getPos());
  return (desiredVelocity - m_vehicle->getVelocity());
}
void SteeringBehaviour::SeekOff () [inline]
Sets seek to off state.
Definition at line 48 of file SteeringBehaviour.h.
References m_activeFlags, on(), and seek.
{if(on(seek)) m_activeFlags ^= seek;} //bitwise XOR
void SteeringBehaviour::SeekOn () [inline]
Sets seek to on state.
Definition at line 44 of file SteeringBehaviour.h.
References m_activeFlags, and seek.
{m_activeFlags |= seek;} //bitwise OR
ngl::Vec3 SteeringBehaviour::Separation (std::vector< int > neighbours) [private]
Separation behaviour type.
Separation - finds the average separation force for the vehicles closest neighbours.
Parameters:
[in] neighbours,: vector of ints to contain the IDs of the neighbours
Returns:
Vec3: the steering force
Definition at line 403 of file SteeringBehaviour.cpp.
References EntityManager::getEntityFromID(), BaseGameEntity::getPos(), m_entityMgr, and m_vehicle.
{
  ngl::Vec3 separationForce;
  for (unsigned int i = 0; i < neighbours.size(); i++)
  {
    ngl::Vec3 vectorToNeighbour = m_entityMgr->getEntityFromID(neighbours[i])->getPos() - m_vehicle->getPos();
    if(vectorToNeighbour.lengthSquared() == 0.0f)
    {
      std::cout<<"VectorToNeighbour in separation equals zero, can't normalise"<<std::endl;
    }
    else
    {
      vectorToNeighbour.normalize();
    }
    vectorToNeighbour /= -(vectorToNeighbour.length());
    separationForce += vectorToNeighbour;
  }
  return separationForce;
}
void SteeringBehaviour::SeparationOff () [inline]
Sets separation to off state.
Definition at line 148 of file SteeringBehaviour.h.
References m_activeFlags, on(), and separation.
{if(on(separation)) m_activeFlags ^= separation;}
void SteeringBehaviour::SeparationOn () [inline]
Sets separation to on state.
Definition at line 144 of file SteeringBehaviour.h.
References m_activeFlags, and separation.
{m_activeFlags |= separation;}
void SteeringBehaviour::setAlignmentWeight (const double _newWeight) [inline]
Sets the weight of alignment.
Parameters:
[in] _newWeight,: pass in the weight to set alignment to
Definition at line 183 of file SteeringBehaviour.h.
References m_weightAlignment.
{m_weightAlignment = _newWeight;}
void SteeringBehaviour::setArriveWeight (const double _newWeight) [inline]
Sets the weight of arrive.
Parameters:
[in] _newWeight,: pass in weight to set arrive to
Definition at line 108 of file SteeringBehaviour.h.
References m_weightArrive.
{m_weightArrive = _newWeight;}
void SteeringBehaviour::setCohesionWeight (const double _newWeight) [inline]
Sets the weight of cohesion.
Parameters:
[in] _newWeight,: pass in the weight to set cohesion to
Definition at line 208 of file SteeringBehaviour.h.
References m_weightCohesion.
{m_weightCohesion = _newWeight;}
void SteeringBehaviour::setEvadeWeight (const double _newWeight) [inline]
Sets the weight of evade.
Parameters:
[in] _newWeight,: pass in the weight to set evade to
Definition at line 283 of file SteeringBehaviour.h.
References m_weightEvade.
{m_weightEvade = _newWeight;}
void SteeringBehaviour::setFleeWeight (const double _newWeight) [inline]
Sets the weight of flee.
Parameters:
[in] _newWeight,: pass in weight to set flee to
Definition at line 83 of file SteeringBehaviour.h.
References m_weightFlee.
{m_weightFlee = _newWeight;}
void SteeringBehaviour::setObstacleAvoidWeight (const double _newWeight) [inline]
Sets the weight of obstacle avoidance.
Parameters:
[in] _newWeight,: pass in the weight to set obstacle avoidance to
Definition at line 308 of file SteeringBehaviour.h.
References m_weightObstacleAvoidance.
{m_weightObstacleAvoidance = _newWeight;}
void SteeringBehaviour::setPursuitWeight (const double _newWeight) [inline]
Sets the weight of pursuit.
Parameters:
[in] _newWeight,: pass in the weight to set pursuit to
Definition at line 258 of file SteeringBehaviour.h.
References m_weightPursuit.
{m_weightPursuit = _newWeight;}
void SteeringBehaviour::setSeekWeight (const double _newWeight) [inline]
Sets the weight of seek.
Parameters:
[in] _newWeight,: pass in the weight to set seek to
Definition at line 58 of file SteeringBehaviour.h.
References m_weightSeek.
{m_weightSeek = _newWeight;}
void SteeringBehaviour::setSeparationWeight (const double _newWeight) [inline]
Sets the weight of separation.
Parameters:
[in] _newWeight,: pass in weight to set separation to
Definition at line 158 of file SteeringBehaviour.h.
References m_weightSeparation.
{m_weightSeparation = _newWeight;}
void SteeringBehaviour::setSquadCohesionWeight (const double _newWeight) [inline]
Sets the weight of squad cohesion.
Parameters:
[in] _newWeight,: pass in the weight to set squad cohesion to
Definition at line 233 of file SteeringBehaviour.h.
References m_weightSquadCohesion.
{m_weightSquadCohesion = _newWeight;}
void SteeringBehaviour::setTargetAgent (Vehicle * _agent) [inline]
Sets the target agent for pursuit and evade.
Parameters:
[in] _agent,: pass in vehicle to use as target
Definition at line 345 of file SteeringBehaviour.h.
References m_targetAgent.
{m_targetAgent = _agent;}
void SteeringBehaviour::setWallAvoidWeight (const double _newWeight) [inline]
Sets the weight of wall avoidance.
Parameters:
[in] _newWeight,: pass in the weight to set obstacle avoidance to
Definition at line 333 of file SteeringBehaviour.h.
References m_weightWallAvoidance.
{m_weightWallAvoidance = _newWeight;}
void SteeringBehaviour::setWanderWeight (const double _newWeight) [inline]
Sets the weight of wander.
Parameters:
[in] _newWeight,: pass in weight to set wander to
Definition at line 133 of file SteeringBehaviour.h.
References m_weightWander.
{m_weightWander = _newWeight;}
ngl::Vec3 SteeringBehaviour::SquadCohesion (ngl::Vec3 squadPos, int deceleration) [private]
Squad Cohesion behaviour type.
Parameters:
[in] squadPos,: vector of the target squad position
[in] deceleration,: the amount to decelerate by
Returns:
Vec3: the steering force
Squad Cohesion - this is the same as arrive, but is used for squads, or protest cohesion only this is so the weight can be altered using alternate variables
Definition at line 479 of file SteeringBehaviour.cpp.
References MovingEntity::getMaxSpeed(), BaseGameEntity::getPos(), MovingEntity::getVelocity(), and m_vehicle.
{
  //arrive
  ngl::Vec3 toTarget = squadPos - m_vehicle->getPos();
  double dist = toTarget.length();
  if(dist>0.1)
  {
    double decelerationTweak = 0.01;
    double speed = dist/(deceleration*decelerationTweak);
    //make velocity not exceed maxspeed
    if( speed > m_vehicle->getMaxSpeed())
    {
      speed = m_vehicle->getMaxSpeed();
    }
    ngl::Vec3 desiredVelocity = toTarget * speed/dist;
    return(desiredVelocity - m_vehicle->getVelocity());
  }
  else if(dist <= 0.1 )
  {
    return ngl::Vec3(0,0,0);
  }
  return ngl::Vec3(0,0,0);
}
void SteeringBehaviour::SquadCohesionOff () [inline]
Sets squad cohesion to off state.
Definition at line 223 of file SteeringBehaviour.h.
References m_activeFlags, on(), and squad_cohesion.
{if(on(squad_cohesion)) m_activeFlags ^= squad_cohesion;}
void SteeringBehaviour::SquadCohesionOn () [inline]
Sets squad cohesion to on state.
Definition at line 219 of file SteeringBehaviour.h.
References m_activeFlags, and squad_cohesion.
{m_activeFlags |= squad_cohesion;}
ngl::Vec3 SteeringBehaviour::WallAvoidance () [private]
Wall Avoidance behaviour.
Returns:
Vec3: the steering force
Wall avoidance - Three feelers are created from the local origin of the entity with forward direction and one 45 degrees either side. Each of the feelers compare against the walls of the current cell and and check for intersections. Whichever feeler has the closest intersection creates a force in the direction of the intersected wall normal, with strength based upon the amount of overlap with the wall.
Definition at line 623 of file SteeringBehaviour.cpp.
References BaseGameEntity::getCurrentCell(), BaseGameEntity::getDetectionRadius(), MovingEntity::getHeading(), BaseGameEntity::getPos(), Cell::getWalls(), lineIntersection2D(), and m_vehicle.
{
  double feelerLength = m_vehicle->getDetectionRadius();
  std::vector<ngl::Vec3> feelers;
  ngl::Vec3 feelerFront = m_vehicle->getPos() + (feelerLength * m_vehicle->getHeading());
  feelers.push_back(feelerFront);
  ngl::Transformation trans;
  trans.setRotation(0.f, 45.f, 0.f);
  ngl::Vec3 feelerLeft = m_vehicle->getPos() + (feelerLength * (m_vehicle->getHeading() * trans.getMatrix()));
  feelers.push_back(feelerLeft);
  trans.setRotation(0.f, -45.f, 0.f);
  ngl::Vec3 feelerRight = m_vehicle->getPos() + (feelerLength * (m_vehicle->getHeading() * trans.getMatrix()));
  feelers.push_back(feelerRight);
  ngl::Vec3 currentIntersectPoint;
  double distToCurrentIntersect = 0.0;
  ngl::Vec3 closestIntersectPoint;
  double distToClosestIntersect = 99999.9;
  ngl::Vec3 currentClosestWallNormal;
  bool feelerTouch = false;
  ngl::Vec3 wallAvoidanceForce = ngl::Vec3(0.f, 0.f, 0.f);
  int numberOfFeelers = feelers.size();
  for (int i = 0; i < numberOfFeelers; ++i)
  {
    // need neighbour walls
    for (int j= 0; j < m_vehicle->getCurrentCell().getWalls().size(); ++j)
    {
      ngl::Vec3 wallStart = m_vehicle->getCurrentCell().getWalls()[j].start;
      ngl::Vec3 wallEnd = m_vehicle->getCurrentCell().getWalls()[j].end;
      ngl::Vec3 wallLine = wallEnd - wallStart;
      ngl::Vec3 wallNormal = wallLine.cross(ngl::Vec3(0.f, 1.f, 0.f));
      if(wallNormal.lengthSquared() == 0.0f)
      {
        std::cout<<"Wall normal in wall avoidance equals zero, can't normalise"<<std::endl;
      }
      else
      {
        wallNormal.normalize();
      }
      if (lineIntersection2D(m_vehicle->getPos(), feelers[i], wallStart, wallEnd, distToCurrentIntersect, currentIntersectPoint))
      {
        if (distToCurrentIntersect < distToClosestIntersect)
        {
          distToClosestIntersect = distToCurrentIntersect;
          feelerTouch = true;
          closestIntersectPoint = currentIntersectPoint;
          currentClosestWallNormal = wallNormal;
        }
      }
    }
    if (feelerTouch == true)
    {
      ngl::Vec3 overShoot = feelers[i] - closestIntersectPoint;
      ngl::Vec3 reverseOverShoot = currentClosestWallNormal * overShoot.length();
      wallAvoidanceForce = reverseOverShoot;
    }
  }
  return wallAvoidanceForce;
}
void SteeringBehaviour::WallAvoidOff () [inline]
Sets wall avoidance to off state.
Definition at line 323 of file SteeringBehaviour.h.
References m_activeFlags, on(), and wall_avoidance.
{ if(on(wall_avoidance)) m_activeFlags ^= wall_avoidance; }
void SteeringBehaviour::WallAvoidOn () [inline]
Sets wall avoidance to on state.
Definition at line 319 of file SteeringBehaviour.h.
References m_activeFlags, and wall_avoidance.
{ m_activeFlags |= wall_avoidance; }
void SteeringBehaviour::WallOverlapAvoidance ()
Calculates the overlap for wall avoidance.
wall overlap avoidance checks the entity against the walls in the current cell. If the distance between the wall location and the entity centre is less than the radius of the entity then the entity is moved in the direction of the wall normal by the amount of overlap with the wall
Definition at line 834 of file SteeringBehaviour.cpp.
References BaseGameEntity::getBoundingRadius(), BaseGameEntity::getCurrentCell(), BaseGameEntity::getPos(), Cell::getWallsInCell(), m_vehicle, and BaseGameEntity::setPos().
{
  for (int j= 0; j < m_vehicle->getCurrentCell().getWallsInCell().size(); ++j)
  {
    ngl::Vec3 wallStart = m_vehicle->getCurrentCell().getWallsInCell()[j].start;
    ngl::Vec3 wallEnd = m_vehicle->getCurrentCell().getWallsInCell()[j].end;
    ngl::Vec3 wallLine = wallEnd - wallStart;
    ngl::Vec3 wallNormal = wallLine.cross(ngl::Vec3(0.f, 1.f, 0.f));
    if(wallNormal.lengthSquared() == 0.0f)
    {
      std::cout<<"wall normal in wall overlap avoidance equals zero, can't normalise"<<std::endl;
    }
    else
    {
      wallNormal.normalize();
    }
    if (wallLine.m_x != 0.f)
    {
      // upper or lower wall
      float zDistToWall = fabs(wallStart.m_z - m_vehicle->getPos().m_z);
      float amountOfOverLap = m_vehicle->getBoundingRadius() - zDistToWall;
      if (amountOfOverLap >= 0)
      {
        m_vehicle->setPos(m_vehicle->getPos() + (wallNormal * amountOfOverLap));
      }
    }
    else if (wallLine.m_z != 0.f)
    {
      // left or right wall
      float xDistToWall = fabs(wallStart.m_x - m_vehicle->getPos().m_x);
      float amountOfOverLap = m_vehicle->getBoundingRadius() - xDistToWall;
      if (amountOfOverLap >= 0)
      {
        m_vehicle->setPos(m_vehicle->getPos() + (wallNormal * amountOfOverLap));
      }
    }
  }
}
ngl::Vec3 SteeringBehaviour::Wander () [private]
Wander behaviour type.
Returns:
Vec3: the steering force
Wander - creates a circle around the entity of radius r. a new point on the circle is found by getting the current point adding a vector to the point, normalising the resulting local position vector and multiplying this vector by the radius. The circle is then moved forward in local space by a distance d and the entity creates a steering force from the vector from the entity origin to the point on the circle
Definition at line 315 of file SteeringBehaviour.cpp.
References MovingEntity::getHeading(), Vehicle::getTimeElapsed(), m_vehicle, m_wanderDistance, m_wanderJitter, m_wanderRadius, and m_wanderTarget.
{
  double jitterTimeSlice = m_wanderJitter * m_vehicle->getTimeElapsed() ;
  float randomClampedX = -1+2*((float)rand())/RAND_MAX;
  float randomClampedZ = -1+2*((float)rand())/RAND_MAX;
  m_wanderTarget += ngl::Vec3(randomClampedX * jitterTimeSlice ,0, randomClampedZ * jitterTimeSlice);
  if(m_wanderTarget.lengthSquared() == 0.0f)
  {
    std::cout<<"Wander Target in wander equals zero, can't normalise"<<std::endl;
  }
  else
  {
    m_wanderTarget.normalize();
  }
  m_wanderTarget *= m_wanderRadius;
  ngl::Vec3 localTarget = m_wanderTarget + ngl::Vec3(m_wanderDistance,0,0);
  // local to world space
  ngl::Vec3 headingNormalise;
  ngl::Vec3 worldNormalise = ngl::Vec3(1,0,0);
  headingNormalise = m_vehicle->getHeading();
  if(headingNormalise.lengthSquared() == 0.0f)
  {
    std::cout<<"heading Normalise in wander equals zero, can't normalise"<<std::endl;
  }
  else
  {
    headingNormalise.normalize();
  }
  double dotProduct = worldNormalise.dot(headingNormalise);
  double magnitude = headingNormalise.length()*worldNormalise.length();
  double temp = dotProduct/magnitude;
  double angle = acos(temp);
  if(headingNormalise.m_z > 0)
  {
    angle = 2*M_PI - angle;
  }
  ngl::Transformation trans;
  trans.setRotation(0, (-angle * 180)/M_PI, 0);
  ngl::Vec3 worldTarget;
  worldTarget = trans.getMatrix() * localTarget;
  return worldTarget;
}
void SteeringBehaviour::WanderOff () [inline]
Sets wander to off state.
Definition at line 123 of file SteeringBehaviour.h.
References m_activeFlags, on(), and wander.
{if(on(wander)) m_activeFlags ^= wander;}
void SteeringBehaviour::WanderOn () [inline]
Sets wander to on state.
Definition at line 119 of file SteeringBehaviour.h.
References m_activeFlags, and wander.
{m_activeFlags |= wander;}
ngl::Vec3 SteeringBehaviour::worldToLocalSpace (ngl::Vec3 pointWorldPos, ngl::Vec3 vehiclePos, ngl::Vec3 vehicleHeading, ngl::Vec3 vehicleSide) [private]
Convert from world to local space.
This method converts points from world space to local space.
Parameters:
[in] pointWorldPos,: the vector of the point in world space
[in] vehiclePos,: vector of the position of the vehicle
[in] vehicleHeading,: vector of the heading of the vehicle
[in] vehicleSide,: vector of the side of the vehicle
Returns:
Vec3: the vector of the point in local space
Definition at line 691 of file SteeringBehaviour.cpp.
{
  if(vehicleHeading.lengthSquared() == 0.0f)
  {
    std::cout<<"Vehicle heading in worldToLocalSpace equals zero, can't normalise"<<std::endl;
  }
  else
  {
    vehicleHeading.normalize();
  }
  if(vehicleSide.lengthSquared() == 0.0f)
  {
    std::cout<<"Vehicle side in worldToLocalSpace equals zero, can't normalise"<<std::endl;
  }
  else
  {
    vehicleSide.normalize();
  }
  double Tx = vehiclePos.dot(vehicleHeading);
  double Tz = vehiclePos.dot(vehicleSide);
  ngl::Mat4 mat;
  mat.m_00 = vehicleHeading.m_x; mat.m_02 = vehicleHeading.m_z; mat.m_03 = -Tx;
  mat.m_20 = vehicleSide.m_x;    mat.m_22 = vehicleSide.m_z;    mat.m_23 = -Tz;
  double tempX = (mat.m_00 * pointWorldPos.m_x) + (mat.m_02 * pointWorldPos.m_z) + mat.m_03;
  double tempZ = (mat.m_20 * pointWorldPos.m_x) + (mat.m_22 * pointWorldPos.m_z) + mat.m_23;
  return ngl::Vec3(tempX, 0, tempZ);
}
Member Data Documentation
int SteeringBehaviour::m_activeFlags [private]
Int number of active flags for steering behaviours.
Definition at line 435 of file SteeringBehaviour.h.
std::vector<int> SteeringBehaviour::m_allNeighbours [private]
Vector to contain the IDs of all the neighbours.
Definition at line 480 of file SteeringBehaviour.h.
int SteeringBehaviour::m_deceleration [private]
Int for the amount of deceleration.
Definition at line 465 of file SteeringBehaviour.h.
EntityManager* SteeringBehaviour::m_entityMgr [private]
Pointer to the Entity Manage monostate.
Definition at line 425 of file SteeringBehaviour.h.
std::vector<int> SteeringBehaviour::m_friendlyNeighbours [private]
Vector to contain the IDs of the friendly neighbours.
Definition at line 475 of file SteeringBehaviour.h.
ngl::Vec3 SteeringBehaviour::m_steeringForce [private]
Vecs for the accumulation of steering behaviour forces.
Definition at line 440 of file SteeringBehaviour.h.
Vehicle* SteeringBehaviour::m_targetAgent [private]
Vehicle Pointer to the target agent.
Definition at line 445 of file SteeringBehaviour.h.
Vehicle* SteeringBehaviour::m_vehicle [private]
Pointer to the current vehicle.
Definition at line 430 of file SteeringBehaviour.h.
float SteeringBehaviour::m_wanderDistance [private]
Float for the distance of wander.
Definition at line 450 of file SteeringBehaviour.h.
float SteeringBehaviour::m_wanderJitter [private]
Float for the jitter amount of wander.
Definition at line 460 of file SteeringBehaviour.h.
float SteeringBehaviour::m_wanderRadius [private]
Float for the radius of wander.
Definition at line 455 of file SteeringBehaviour.h.
ngl::Vec3 SteeringBehaviour::m_wanderTarget [private]
Vec3 for the wander target.
Definition at line 470 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightAlignment [private]
The weight of alignment.
Definition at line 518 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightArrive [private]
The weight of arrive.
Definition at line 502 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightCohesion [private]
The weight of cohesion.
Definition at line 510 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightEvade [private]
The weight of evade.
Definition at line 534 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightFlee [private]
The weight of flee.
Definition at line 498 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightObstacleAvoidance [private]
The weight of obstacle avoidance.
Definition at line 522 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightPursuit [private]
The weight of pursuit.
Definition at line 530 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightSeek [private]
The weight of seek.
Definition at line 494 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightSeparation [private]
The weight of separation.
Definition at line 514 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightSquadCohesion [private]
The weight of squad cohesion.
Definition at line 538 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightWallAvoidance [private]
The weight of wall avoidance.
Definition at line 526 of file SteeringBehaviour.h.
double SteeringBehaviour::m_weightWander [private]
The weight of wander.
Definition at line 506 of file SteeringBehaviour.h.
The documentation for this class was generated from the following files:
SteeringBehaviour.h
SteeringBehaviour.cpp