YOURPROJECTNAMEGOESHERE: Police Class Reference
Police Class Reference
The base class for all policemen.
#include <Police.h>
Public Member Functions
Police (GameWorld *world, ngl::Obj *_mesh)
Police ctor.
~Police ()
Police dtor.
lua_State * getLuaState () const
Gets the lua state of the policeman.
void update (double timeElapsed, double currentTime)
Method to update each policeman at every tick.
void draw (ngl::Camera *cam, ngl::Mat4 mouseGlobalTX)
Method to draw each policeman.
void loadMatricesToShader (ngl::Camera *cam, ngl::Mat4 mouseGlobalTX)
Method to load the matrices of the policeman to the shader.
float getRioterInfluence () const
Gets the influence of the rioters.
void checkValidPursuitRange (float _dist)
Method to check that the policeman is within the pursuit range around the squad.
void findPathHome ()
Method to set the policeman on a path back to the police station.
StateMachine< Police > * getStateMachine () const
Gets the state machine for the policeman.
void findTargetID (float _health)
Method to find a target to pursue.
bool handleMessage (const Message &_message)
Method to define how to handle messages.
void attack ()
Method to send a message to attack (deliver damage to target).
void death ()
Method to send message if a policeman has died.
void registerClass (lua_State *_L)
Method to register class, functions and properties to be used in lua.
ngl::Vec3 getSquadPos () const
Gets the position of the squad.
void setSquadPos (ngl::Vec3 newPos)
Sets the position of the squad.
float getSquadRadius () const
Gets the radius of the policeman's squad.
void setSquadRadius (const float newRad)
Sets the the radius of the policeman's squad.
void squadCohesion (double weight)
Method to set the squad cohesion of the policeman's squad.
int getSquadID () const
Gets the policeman's squad ID.
void setSquadID (const int squadID)
Sets the policeman's squad ID.
bool getIsMoving () const
Gets whether the policeman is moving (move state in lua).
void setIsMoving (const bool _val)
Sets if the policeman is moving (move state in lua).
ngl::Vec3 getBlockadePos () const
Gets the blockade position of the policeman.
void setBlockadePos (const ngl::Vec3 newBlockadePos)
Sets the blockade position of the policeman.
Protected Attributes
StateMachine< Police > * m_stateMachine
Pointer to the state machine.
ngl::Vec3 m_squadPos
vector to contain the current policeman's squad position
float m_squadRadius
float to hold the policeman's squad radius
int m_squadID
number of the policeman's squad ID
bool m_isMoving
Boolean to hold whether the squad is moving or not.
bool m_validPursuit
Boolean to hold whether the policeman is on a valid pursuit.
ngl::Vec3 m_blockadePosition
Vector to hold the policeman's blockade position.
float m_rioterInfluence
Float to hold the amount of rioter influence.
Detailed Description
The base class for all policemen.
Author:
Faye Butler, Will Herbert & Emily Holt
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 20 of file Police.h.
Constructor & Destructor Documentation
Police::Police (GameWorld * world, ngl::Obj * _mesh)
Police ctor.
Parameters:
[in] world,: Pointer to the gameworld
[in] _mesh,: Pointer to the obj mesh used for a policeman
Definition at line 10 of file Police.cpp.
References Agent::L, m_blockadePosition, BaseGameEntity::m_entityType, Agent::m_hopHeight, Agent::m_hopSpeed, m_isMoving, Agent::m_mesh, m_rioterInfluence, m_stateMachine, m_validPursuit, SteeringBehaviour::ObstacleAvoidOn(), registerClass(), Agent::setMaxSpeed(), SteeringBehaviour::setWallAvoidWeight(), Vehicle::Steering(), typePolice, and SteeringBehaviour::WallAvoidOn().
                                              : Agent(world)
{
  m_entityType = typePolice;
  registerClass(L);
  // Set up state machine
  m_stateMachine = new StateMachine<Police>(this);
  // Set initial variables
  m_mesh = _mesh;
  m_isMoving = false;
  m_validPursuit = true;
  m_hopHeight = 0.5;
  m_hopSpeed = 0.0;
  luabridge::LuaRef makePolice = luabridge::getGlobal(L, "makePolice");
  makePolice();
  m_blockadePosition = NULL;
  Vehicle::Steering()->WallAvoidOn();
  Vehicle::Steering()->setWallAvoidWeight(0.4);
  Vehicle::Steering()->ObstacleAvoidOn();
  m_rioterInfluence = 0.0;
  Vehicle::setMaxSpeed(3);
}
Police::~Police ()
Police dtor.
Definition at line 41 of file Police.cpp.
References Agent::L, and m_stateMachine.
{
  lua_close(L);
  delete m_stateMachine;
}
Member Function Documentation
void Police::attack ()
Method to send a message to attack (deliver damage to target).
Definition at line 239 of file Police.cpp.
References BaseGameEntity::getID(), Agent::getTargetID(), Agent::m_damage, BaseGameEntity::m_messageMgr, msgAttack, and MessageManager::sendMessage().
{
  m_messageMgr->sendMessage(this->getID(), this->getTargetID(), msgAttack, m_damage);
}
void Police::checkValidPursuitRange (float _dist)
Method to check that the policeman is within the pursuit range around the squad.
Check Pursuit Range - make sure the policeman hasn't got to far from th squad.
Parameters:
[in] _dist,: the distance away from the squad the police can go
Definition at line 183 of file Police.cpp.
References BaseGameEntity::m_pos, m_squadPos, Agent::m_targetID, and m_validPursuit.
{
  ngl::Vec3 toSquad = m_pos - m_squadPos;
  double distSqFromEachOther = toSquad.lengthSquared();
  // make 2 checks so that the police don't get stuck on the edge of the check
  if (m_validPursuit)
  {
    if(distSqFromEachOther > (_dist * _dist))
    {
      m_targetID = -1;
      m_validPursuit = false;
    }
  }
  else
  {
    m_validPursuit = true;
    if(distSqFromEachOther > (_dist * _dist )- ((_dist* _dist)/4.0))
    {
      m_targetID = -1;
      m_validPursuit = false;
    }
  }
}
void Police::death ()
Method to send message if a policeman has died.
Definition at line 244 of file Police.cpp.
References BaseGameEntity::getID(), GameWorld::getNumberOfRioters(), GameWorld::getRioters(), BaseGameEntity::m_messageMgr, BaseGameEntity::m_pos, BaseGameEntity::m_world, msgPoliceDeath, and MessageManager::sendMessage().
{
  for (int i = 0; i < m_world->getNumberOfRioters(); i++)
  {
    ngl::Vec3 vecToRioter = m_world->getRioters()[i]->getPos() - m_pos;
    double distSqToRioter = vecToRioter.lengthSquared();
    double affectedRadius = 8.0;
    if (distSqToRioter < affectedRadius * affectedRadius)
    {
      m_messageMgr->sendMessage(this->getID(), m_world->getRioters()[i]->getID(), msgPoliceDeath, 0.f);
    }
  }
}
void Police::draw (ngl::Camera * cam, ngl::Mat4 mouseGlobalTX)
Method to draw each policeman.
Parameters:
[in] cam,: the camera used for the scene
[in] mouseGlobalTX,: the global mouse position transformation matrix
Definition at line 100 of file Police.cpp.
References loadMatricesToShader(), and Agent::m_mesh.
{
  loadMatricesToShader(cam, mouseGlobalTX);
  m_mesh->draw();
}
void Police::findPathHome ()
Method to set the policeman on a path back to the police station.
Find Path Home - sets the home position and sets a path to it.
Definition at line 212 of file Police.cpp.
References Vehicle::findPath(), GameWorld::getPoliceStation(), Agent::m_hasPathHome, Agent::m_homePos, and BaseGameEntity::m_world.
{
  m_homePos = m_world->getPoliceStation();
  findPath(m_homePos);
  m_hasPathHome = true;
}
void Police::findTargetID (float _health) [virtual]
Method to find a target to pursue.
Find Target ID - finds a valid target to pursue regarding the target's health.
Parameters:
[in] _health,: the number to limit the search, if an agent is below this _health then it won't be found as a target
Implements Agent.
Definition at line 151 of file Police.cpp.
References EntityManager::getEntityFromID(), Agent::getHealth(), BaseGameEntity::getID(), BaseGameEntity::getNeighbourRioterIDs(), Agent::getRage(), BaseGameEntity::m_entityMgr, and Agent::setTargetID().
{
  std::vector<int> rioters = getNeighbourRioterIDs();
  float currentRage = -1;
  Agent* currentTarget = NULL;
  for (int i=0; i<rioters.size(); i++)
  {
    Agent* rioter = dynamic_cast<Agent*>(m_entityMgr->getEntityFromID(rioters[i]));
    if (rioter)
    {
      if (rioter->getHealth()>_health && rioter->getRage()>currentRage)
      {
        currentRage = rioter->getRage();
        currentTarget = rioter;
      }
    }
  }
  if (currentTarget == NULL)
  {
    setTargetID(-1);
  }
  else
  {
    int target = currentTarget->getID();
    setTargetID(target);
  }
}
ngl::Vec3 Police::getBlockadePos () const [inline]
Gets the blockade position of the policeman.
Returns:
Vec3: vector for the position of the policeman's blockade position
Definition at line 168 of file Police.h.
References m_blockadePosition.
{return m_blockadePosition;}
bool Police::getIsMoving () const [inline]
Gets whether the policeman is moving (move state in lua).
Returns:
Boolean: true if the policeman is in move state, false if it is not
Definition at line 156 of file Police.h.
References m_isMoving.
{ return m_isMoving; }
lua_State* Police::getLuaState () const [inline]
Gets the lua state of the policeman.
Returns:
the current lua state
Definition at line 39 of file Police.h.
References Agent::L.
{ return L ; }
float Police::getRioterInfluence () const [inline]
Gets the influence of the rioters.
Returns:
Float: the amount of rioter influence
Definition at line 66 of file Police.h.
References m_rioterInfluence.
{return m_rioterInfluence;}
int Police::getSquadID () const [inline]
Gets the policeman's squad ID.
Returns:
Int: the number of the policeman's squad ID
Definition at line 144 of file Police.h.
References m_squadID.
{return m_squadID;}
ngl::Vec3 Police::getSquadPos () const [inline]
Gets the position of the squad.
Returns:
Vec3: vector of the position of the squad
Definition at line 116 of file Police.h.
References m_squadPos.
{return m_squadPos;}
float Police::getSquadRadius () const [inline]
Gets the radius of the policeman's squad.
Returns:
Float: the radius of the policeman's squad
Definition at line 127 of file Police.h.
References m_squadRadius.
{return m_squadRadius;}
StateMachine<Police>* Police::getStateMachine () const [inline]
Gets the state machine for the policeman.
Definition at line 82 of file Police.h.
References m_stateMachine.
{ return m_stateMachine; }
bool Police::handleMessage (const Message & _message) [virtual]
Method to define how to handle messages.
Parameters:
[in] _messgae:message recieved by the policeman
Reimplemented from Agent.
Definition at line 220 of file Police.cpp.
References Message::m_extraInfo, Agent::m_health, Message::m_message, Vehicle::m_timeElapsed, and msgAttack.
{
  switch(_message.m_message)
  {
  case msgAttack:
    m_health -= (_message.m_extraInfo * m_timeElapsed);
    return true;
    break;
  default:
    std::cout<<"Police: Message type not defined"<<std::endl;
    return false;
    break;
  }
}
void Police::loadMatricesToShader (ngl::Camera * cam, ngl::Mat4 mouseGlobalTX)
Method to load the matrices of the policeman to the shader.
Parameters:
[in] cam,: the camera used for the scene
[in] mouseGlobalTX,: the global mouse position transformation matrix
Definition at line 107 of file Police.cpp.
References MovingEntity::getHeading(), Agent::getHealth(), BaseGameEntity::getPos(), and Agent::m_hop.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
      (*shader)["Phong"]->use();
  ngl::Material m(ngl::Colour(0.2f,0.2f,0.2f, 1.0), ngl::Colour(0.2775f,0.2775f,0.2775f, 1.0), ngl::Colour(0.77391f,0.77391f,0.77391f, 1.0));
  m.setSpecularExponent(5.f);
  m.setDiffuse(ngl::Colour(0.0f, 0.0f, 1.0f-(1-(getHealth()/100.0f)), 1.0f));
  m.loadToShader("material");
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  ngl::Mat3 normalMatrix;
  ngl::Mat4 M;
  ngl::Transformation trans;
  trans.setPosition(getPos().m_x,m_hop,getPos().m_z);
  ngl::Real rot = atan(getHeading().m_z/getHeading().m_x);
  rot = ((rot * 180)/M_PI);
  if(getHeading().m_x < 0)
  {
    rot = 180 + rot;
  }
  trans.setRotation(0,-rot+90,0);
  M=trans.getMatrix()*mouseGlobalTX;
  MV=  M*cam->getViewMatrix();
  MVP= M*cam->getVPMatrix();
  normalMatrix=MV;
  normalMatrix.inverse();
  shader->setShaderParamFromMat4("MV",MV);
  shader->setShaderParamFromMat4("MVP",MVP);
  shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
  shader->setShaderParamFromMat4("M",M);
}
void Police::registerClass (lua_State * _L)
Method to register class, functions and properties to be used in lua.
Register class - exposes to lua the added functions and properties from Police.h.
Parameters:
[in] _L,: the lua state
Definition at line 286 of file Police.cpp.
References attack(), checkValidPursuitRange(), findPathHome(), getIsMoving(), getRioterInfluence(), Agent::L, Agent::registerLua(), setIsMoving(), and squadCohesion().
{
  // Set up LUA state
  luaL_dofile(L, "lua/Police.lua");
  luaL_openlibs(L);
  registerLua(_L);
  luabridge::getGlobalNamespace(_L)
    .deriveClass<Police, Agent>("Police")
      .addConstructor <void (*) (GameWorld*, ngl::Obj*)> ()
        .addFunction("attack", &Police::attack)
        .addFunction("getRioterInfluence", &Police::getRioterInfluence)
        .addFunction("squadCohesion", &Police::squadCohesion)
        .addFunction("findPathHome", &Police::findPathHome)
        .addProperty("m_isMoving", &Police::getIsMoving, &Police::setIsMoving)
        .addFunction("checkValidPursuitRange", &Police::checkValidPursuitRange)
    .endClass();
  luabridge::push(L, this);
  lua_setglobal(L, "police");
}
void Police::setBlockadePos (const ngl::Vec3 newBlockadePos) [inline]
Sets the blockade position of the policeman.
Parameters:
[in] newBlockadePos,: the vector to set the policeman's blockade position to
Definition at line 174 of file Police.h.
References m_blockadePosition.
{m_blockadePosition = newBlockadePos;}
void Police::setIsMoving (const bool _val) [inline]
Sets if the policeman is moving (move state in lua).
Parameters:
[in] _val,: boolean, set to true if the policeman is moving, false if not
Definition at line 162 of file Police.h.
References m_isMoving.
{ m_isMoving = _val; }
void Police::setSquadID (const int squadID) [inline]
Sets the policeman's squad ID.
Parameters:
[in] squadID,: number to set the policeman's squad ID to
Definition at line 150 of file Police.h.
References m_squadID.
{m_squadID = squadID;}
void Police::setSquadPos (ngl::Vec3 newPos) [inline]
Sets the position of the squad.
Parameters:
[in] newPos,: vector to set the position of the squad
Definition at line 121 of file Police.h.
References m_squadPos.
{m_squadPos = newPos;}
void Police::setSquadRadius (const float newRad) [inline]
Sets the the radius of the policeman's squad.
Parameters:
[in] newRad,: number to set the radius of the policeman's squad to
Definition at line 132 of file Police.h.
References m_squadRadius.
{m_squadRadius = newRad;}
void Police::squadCohesion (double weight)
Method to set the squad cohesion of the policeman's squad.
Squad Cohesion - correlates weight of the cohesion to how far away from the squad the policeman is.
Parameters:
[in] weight,: the weight to set squad cohesion to
Definition at line 261 of file Police.cpp.
References BaseGameEntity::m_pos, m_squadPos, m_squadRadius, SteeringBehaviour::setSquadCohesionWeight(), Vehicle::setSquadCrosshair(), SteeringBehaviour::SquadCohesionOff(), SteeringBehaviour::SquadCohesionOn(), and Vehicle::Steering().
{
  if(weight <= 0.0)
  {
    Vehicle::Steering()->SquadCohesionOff();
  }
  else
  {
    ngl::Vec3 toSquad = m_pos - m_squadPos;
    double distance = fabs(toSquad.length());
    weight = (weight*distance*1.5f)/m_squadRadius;
    Vehicle::setSquadCrosshair(m_squadPos);
    Vehicle::Steering()->setSquadCohesionWeight(weight);
    Vehicle::Steering()->SquadCohesionOn();
  }
}
void Police::update (double timeElapsed, double currentTime) [virtual]
Method to update each policeman at every tick.
Update - updates the police agent by time elapsed from the last tick.
Parameters:
[in] timeElapsed,: the time elapsed between each tick
[in] currentTime,: the current time of the game
Implements Agent.
Definition at line 51 of file Police.cpp.
References SteeringBehaviour::addAllNeighbours(), SteeringBehaviour::addFriendlyNeighbours(), SteeringBehaviour::ArriveOff(), SteeringBehaviour::ArriveOn(), SteeringBehaviour::clearAllNeighbours(), SteeringBehaviour::clearFriendlyNeighbours(), EntityManager::getEntityFromID(), BaseGameEntity::getNeighbourPoliceIDs(), BaseGameEntity::getNeighbourRioterIDs(), BaseGameEntity::getPos(), Agent::getRage(), m_blockadePosition, BaseGameEntity::m_entityMgr, Agent::m_hop, Agent::m_hopHeight, Agent::m_hopSpeed, BaseGameEntity::m_ID, BaseGameEntity::m_neighbourRioterIDs, m_rioterInfluence, m_stateMachine, SteeringBehaviour::ObjectOverlapAvoidance(), Vehicle::setCrosshair(), Vehicle::Steering(), StateMachine< entityType >::update(), and SteeringBehaviour::WallOverlapAvoidance().
{
  //make a friendly and opposing neightbours vector as seperation wants all neighbours bu alignment & cohesion doesn't
  Vehicle::Steering()->clearFriendlyNeighbours();
  Vehicle::Steering()->clearAllNeighbours();
  Vehicle::Steering()->addFriendlyNeighbours(getNeighbourPoliceIDs());
  Vehicle::Steering()->addAllNeighbours(getNeighbourRioterIDs());
  Vehicle::Steering()->addAllNeighbours(getNeighbourPoliceIDs());
  Vehicle::Steering()->WallOverlapAvoidance();
  Vehicle::Steering()->ObjectOverlapAvoidance();
  //call agent and state machine update
  Agent::update(timeElapsed, currentTime);
  m_stateMachine->update();
  // calculate influence of neighbouring rioters based on their rage
  int nearbyRioters = m_neighbourRioterIDs.size();
  m_rioterInfluence = 0.0;
  for (int i=0; i<nearbyRioters; i++)
  {
    Agent* rioter = dynamic_cast<Agent*>(m_entityMgr->getEntityFromID(m_neighbourRioterIDs[i]));
    if (rioter)
    {
      m_rioterInfluence += rioter->getRage();
    }
  }
  m_hopSpeed = 10.f;
  m_hop = (sin((currentTime*m_hopSpeed)+m_ID)*sin((currentTime*m_hopSpeed)+m_ID)*m_hopHeight);
  //if they have a blockade position (Wall State is on) then set this to the crosshair
  if(m_blockadePosition != NULL)
  {
    this->setCrosshair(m_blockadePosition);
    if((this->getPos() - m_blockadePosition).lengthSquared() <= 0.01)
    {
      this->Steering()->ArriveOff();
    }
    else
    {
      this->Steering()->ArriveOn();
    }
  }
}
Member Data Documentation
ngl::Vec3 Police::m_blockadePosition [protected]
Vector to hold the policeman's blockade position.
Definition at line 210 of file Police.h.
bool Police::m_isMoving [protected]
Boolean to hold whether the squad is moving or not.
Definition at line 200 of file Police.h.
float Police::m_rioterInfluence [protected]
Float to hold the amount of rioter influence.
Definition at line 215 of file Police.h.
int Police::m_squadID [protected]
number of the policeman's squad ID
Definition at line 195 of file Police.h.
ngl::Vec3 Police::m_squadPos [protected]
vector to contain the current policeman's squad position
Definition at line 185 of file Police.h.
float Police::m_squadRadius [protected]
float to hold the policeman's squad radius
Definition at line 190 of file Police.h.
StateMachine<Police>* Police::m_stateMachine [protected]
Pointer to the state machine.
Definition at line 180 of file Police.h.
bool Police::m_validPursuit [protected]
Boolean to hold whether the policeman is on a valid pursuit.
Definition at line 205 of file Police.h.
The documentation for this class was generated from the following files:
Police.h
Police.cpp