YOURPROJECTNAMEGOESHERE: Agent Class Reference
Agent Class Reference
The base class for all agents, that can be rioters or police.
#include <Agent.h>
Public Member Functions
Agent (GameWorld *_world)
ctor this will create a valid Lua state and initialise into a valid world
~Agent ()
dtor used to remove agent and close Lua state
virtual void update (double timeElapsed, double currentTime)=0
virtual pure method to update the agent every tick
virtual bool handleMessage (const Message &_message)
determins how any messages received by the agent should be handled
void registerLua (lua_State *_L)
registers the agent's functions and properties with the valid Lua state
void wander (double _weight)
used to expose the function to Lua, so wander steering behaviour can be turned on and off, with a weight
void pursuit (double _weight)
used to expose the function to Lua, so pursuit steering behaviour can be turned on and off, with a weight
void evade (double _weight)
used to expose the function to Lua, so evade steering behaviour can be turned on and off, with a weight
void seek (double _weight)
used to expose the function to Lua, so seek steering behaviour can be turned on and off, with a weight
void arrive (double _weight)
used to expose the function to Lua, so arrive steering behaviour can be turned on and off, with a weight
void cohesion (double _weight)
used to expose the function to Lua, so cohesion steering behaviour can be turned on and off, with a weight
void separation (double _weight)
used to expose the function to Lua, so separation steering behaviour can be turned on and off, with a weight
void alignment (double _weight)
used to expose the function to Lua, so alignment steering behaviour can be turned on and off, with a weight
int getTargetID () const
gets the ID of the agent's current target
void setTargetID (const int _val)
sets the health of the agent
virtual void findTargetID (float _health)=0
pure virtual method to find a target ID with highest rage with minimum health threshold
void checkValidTarget (float _dist, float _health)
checks if the target is valid, are close enough to the agent, and if they have enough health
bool targetWithinReach (float _reach)
determins if the target agent is within reach
ngl::Vec3 getHomePos () const
gets the position of the agent's home
void setHomePos (const ngl::Vec3 _val)
sets the position of the agent's home
bool getHasPathHome () const
gets if the agent has a valid path home
void setHasPathHome (const bool _val)
sets if the agent has a valid path home
float getHealth () const
gets the health of the agent
void setHealth (const float _val)
sets the health of the agent
float getEnergy () const
gets the energy of the agent
void setEnergy (const float _val)
sets the energy of the agent
float getMorale () const
gets the morale of the agent
void setMorale (const float _val)
sets the morale of the agent
float getRage () const
gets the rage of the agent
void setRage (const float _val)
sets the rage of the agent
float getDamage () const
gets the damage of the agent
void setDamage (const float _val)
sets the damage of the agent
float getMaxSpeed () const
gets the maximum speed of the agent
void setMaxSpeed (const float _maxSpeed)
sets the maximum speed of the agent
float getHopHeight () const
gets the height of the agent's hop for drawing
void setHopHeight (const float _val)
sets the height of the agent's hop for drawing
float getHopSpeed () const
gets the speed of the agent's hop
void setHopSpeed (float _val)
sets the speed of the agent's hop
Protected Attributes
lua_State * L
the Lua state registered with the agent
Timer * m_gameTimer
a pointer to the Timer monostate class
ngl::Obj * m_mesh
the mesh used to draw the agent in the world
int m_targetID
the value of the target agent's ID
ngl::Vec3 m_homePos
the position vector of the agent's home
bool m_hasPathHome
if the agent has a valid path home
float m_detectionRadius
the detection radius of the agent
float m_health
the health value of the agent
float m_energy
the energy value of the agent
float m_morale
the morale value of the agent
float m_rage
the rage value of the agent
float m_damage
the damage value of the agent
double m_hop
the current value of the agent's height in it's hop sine cycle
float m_hopHeight
the hop height value of the agent
float m_hopSpeed
the hop frequency of the agent
Detailed Description
The base class for all agents, that can be rioters or police.
Author:
Will Herbert & Emily Holt & Faye Butler
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 30 of file Agent.h.
Constructor & Destructor Documentation
Agent::Agent (GameWorld * _world)
ctor this will create a valid Lua state and initialise into a valid world
Parameters:
[in] _world input world to create the agent in
Definition at line 8 of file Agent.cpp.
References L, m_hasPathHome, and m_targetID.
                             : Vehicle(_world, ngl::Vec3(0,0,0), ngl::Vec3(0,0,0), 0.0f, 1.0f, 10.0f,1.0f, 1.0f, 0.5f)
{
  L = luaL_newstate();
  m_targetID = -1;
  m_hasPathHome = false;
}
Agent::~Agent ()
dtor used to remove agent and close Lua state
Definition at line 17 of file Agent.cpp.
{
}
Member Function Documentation
void Agent::alignment (double _weight)
used to expose the function to Lua, so alignment steering behaviour can be turned on and off, with a weight
Parameters:
[in] _weight input to determin the weight of the alignment steering behaviour, 0 turns off the behaviour
Definition at line 168 of file Agent.cpp.
References SteeringBehaviour::AlignmentOff(), SteeringBehaviour::AlignmentOn(), SteeringBehaviour::setAlignmentWeight(), and Vehicle::Steering().
{
  if(_weight <= 0.0)
  {
    Vehicle::Steering()->AlignmentOff();
  }
  else
  {
    Vehicle::Steering()->AlignmentOn();
    Vehicle::Steering()->setAlignmentWeight(_weight);
  }
}
void Agent::arrive (double _weight)
used to expose the function to Lua, so arrive steering behaviour can be turned on and off, with a weight
Parameters:
[in] _weight input to determin the weight of the arrive steering behaviour, 0 turns off the behaviour
Definition at line 126 of file Agent.cpp.
References SteeringBehaviour::ArriveOff(), SteeringBehaviour::ArriveOn(), SteeringBehaviour::setArriveWeight(), and Vehicle::Steering().
{
  if(_weight <= 0.0)
  {
    Vehicle::Steering()->ArriveOff();
  }
  else
    {
      Vehicle::Steering()->ArriveOn();
      Vehicle::Steering()->setArriveWeight(_weight);
    }
}
void Agent::checkValidTarget (float _dist, float _health)
checks if the target is valid, are close enough to the agent, and if they have enough health
Parameters:
[in] _dist input to determin maximum distance to valid target
[in] _health intput to determin minimum health to consider
Definition at line 196 of file Agent.cpp.
References findTargetID(), EntityManager::getEntityFromID(), EntityManager::getEntityMap(), getHealth(), BaseGameEntity::getPos(), BaseGameEntity::m_boundingRadius, BaseGameEntity::m_entityMgr, BaseGameEntity::m_pos, and m_targetID.
{
  if(m_targetID >= 0)
  {
    std::map<int, BaseGameEntity*>::const_iterator entity = m_entityMgr->getEntityMap().find(m_targetID);
    if(entity->first !=  m_entityMgr->getEntityMap().end()->first)
    {
      Agent* target = dynamic_cast<Agent*>(m_entityMgr->getEntityFromID(m_targetID));
      ngl::Vec3 toEntity = m_pos - target->getPos();
      double distSqFromEachOther = toEntity.lengthSquared();
      // change target
      if(distSqFromEachOther > ((m_boundingRadius * _dist) * (m_boundingRadius * _dist)) || target->getHealth() < _health)
      {
        findTargetID(_health);
      }
    }
    else
    {
      findTargetID(_health);
    }
  }
  else
  {
    // target is not set
    findTargetID(_health);
  }
}
void Agent::cohesion (double _weight)
used to expose the function to Lua, so cohesion steering behaviour can be turned on and off, with a weight
Parameters:
[in] _weight input to determin the weight of the cohesion steering behaviour, 0 turns off the behaviour
Definition at line 140 of file Agent.cpp.
References SteeringBehaviour::CohesionOff(), SteeringBehaviour::CohesionOn(), SteeringBehaviour::setCohesionWeight(), and Vehicle::Steering().
{
  if(_weight <= 0.0)
  {
    Vehicle::Steering()->CohesionOff();
  }
  else
  {
    Vehicle::Steering()->CohesionOn();
    Vehicle::Steering()->setCohesionWeight(_weight);
  }
}
void Agent::evade (double _weight)
used to expose the function to Lua, so evade steering behaviour can be turned on and off, with a weight
Parameters:
[in] _weight input to determin the weight of the evade steering behaviour, 0 turns off the behaviour
Definition at line 98 of file Agent.cpp.
References SteeringBehaviour::EvadeOff(), SteeringBehaviour::EvadeOn(), SteeringBehaviour::setEvadeWeight(), and Vehicle::Steering().
{
  if(_weight <= 0.0)
  {
    Vehicle::Steering()->EvadeOff();
  }
  else
  {
    Vehicle::Steering()->EvadeOn();
    Vehicle::Steering()->setEvadeWeight(_weight);
  }
}
virtual void Agent::findTargetID (float _health) [pure virtual]
pure virtual method to find a target ID with highest rage with minimum health threshold
Parameters:
[in] _health input to determin the minimum health to consider
Implemented in Police, and Rioter.
float Agent::getDamage () const [inline]
gets the damage of the agent
Returns:
float value of agent damage
Definition at line 188 of file Agent.h.
References m_damage.
{ return m_damage; }
float Agent::getEnergy () const [inline]
gets the energy of the agent
Returns:
float value of agent energy
Definition at line 158 of file Agent.h.
References m_energy.
{ return m_energy; }
bool Agent::getHasPathHome () const [inline]
gets if the agent has a valid path home
Returns:
boolean true if it has a valid path, false if it does not have a valid path
Definition at line 138 of file Agent.h.
References m_hasPathHome.
{ return m_hasPathHome; }
float Agent::getHealth () const [inline]
gets the health of the agent
Returns:
float value of agent health
Definition at line 148 of file Agent.h.
References m_health.
{ return m_health; }
ngl::Vec3 Agent::getHomePos () const [inline]
gets the position of the agent's home
Returns:
ngl::Vec3 value of the agent's home
Definition at line 128 of file Agent.h.
References m_homePos.
{ return m_homePos; }
float Agent::getHopHeight () const [inline]
gets the height of the agent's hop for drawing
Returns:
float value of how high the agent's hop is drawn
Definition at line 208 of file Agent.h.
References m_hopHeight.
{ return m_hopHeight; }
float Agent::getHopSpeed () const [inline]
gets the speed of the agent's hop
Returns:
float value of how frequently the agent hops
Definition at line 218 of file Agent.h.
References m_hopSpeed.
{ return m_hopSpeed; }
float Agent::getMaxSpeed () const [inline]
gets the maximum speed of the agent
Returns:
float value of the maximum speed of the agent
Reimplemented from MovingEntity.
Definition at line 198 of file Agent.h.
References MovingEntity::m_maxSpeed.
{return m_maxSpeed;}
float Agent::getMorale () const [inline]
gets the morale of the agent
Returns:
float value of agent morale
Definition at line 168 of file Agent.h.
References m_morale.
{ return m_morale; }
float Agent::getRage () const [inline]
gets the rage of the agent
Returns:
float value of agent rage
Definition at line 178 of file Agent.h.
References m_rage.
{ return m_rage; }
int Agent::getTargetID () const [inline]
gets the ID of the agent's current target
Returns:
int value of the agent's current target
Definition at line 102 of file Agent.h.
References m_targetID.
{ return m_targetID; }
bool Agent::handleMessage (const Message & _message) [virtual]
determins how any messages received by the agent should be handled
Parameters:
[in] _message the message to be received by the agent
Reimplemented from Vehicle.
Reimplemented in Police, and Rioter.
Definition at line 28 of file Agent.cpp.
References Message::m_extraInfo, m_health, Message::m_message, Vehicle::m_timeElapsed, and msgAttack.
{
  switch(_message.m_message)
  {
    case msgAttack:
    {
      m_health -= (_message.m_extraInfo * m_timeElapsed);
      return true;
    }
    default:
    {
      std::cout<<"Agent: Message type not defined"<<std::endl;
      return false;
    }
  }
}
void Agent::pursuit (double _weight)
used to expose the function to Lua, so pursuit steering behaviour can be turned on and off, with a weight
Parameters:
[in] _weight input to determin the weight of the pursuit steering behaviour, 0 turns off the behaviour
Definition at line 84 of file Agent.cpp.
References SteeringBehaviour::PursuitOff(), SteeringBehaviour::PursuitOn(), SteeringBehaviour::setPursuitWeight(), and Vehicle::Steering().
{
  if(_weight <= 0.0)
  {
    Vehicle::Steering()->PursuitOff();
  }
  else
  {
    Vehicle::Steering()->PursuitOn();
    Vehicle::Steering()->setPursuitWeight(_weight);
  }
}
void Agent::registerLua (lua_State * _L)
registers the agent's functions and properties with the valid Lua state
Parameters:
[in] _L input the Lua state to register functions with
Definition at line 45 of file Agent.cpp.
References alignment(), arrive(), checkValidTarget(), cohesion(), evade(), getDamage(), getHealth(), BaseGameEntity::getID(), getMaxSpeed(), getMorale(), getRage(), getTargetID(), pursuit(), seek(), separation(), setDamage(), setHealth(), setMaxSpeed(), setMorale(), setRage(), targetWithinReach(), and wander().
{
  luabridge::getGlobalNamespace(_L)
    .beginClass<Agent>("Agent")
      .addFunction("getID", &Agent::getID)
      .addProperty("m_morale", &Agent::getMorale, &Agent::setMorale)
      .addProperty("m_health", &Agent::getHealth, &Agent::setHealth)
      .addProperty("m_rage", &Agent::getRage, &Agent::setRage)
      .addProperty("m_damage", &Agent::getDamage, &Agent::setDamage)
      .addFunction("getTargetID", &Agent::getTargetID)
      .addFunction("wander", &Agent::wander)
      .addFunction("pursuit", &Agent::pursuit)
      .addFunction("evade", &Agent::evade)
      .addFunction("arrive", &Agent::arrive)
      .addFunction("seek", &Agent::seek)
      .addFunction("cohesion", &Agent::cohesion)
      .addFunction("separation", &Agent::separation)
      .addFunction("alignment", &Agent::alignment)
      .addFunction("checkValidTarget", &Agent::checkValidTarget)
      .addFunction("targetWithinReach", &Agent::targetWithinReach)
      .addProperty("m_maxSpeed", &Agent::getMaxSpeed, &Agent::setMaxSpeed)
    .endClass();
}
void Agent::seek (double _weight)
used to expose the function to Lua, so seek steering behaviour can be turned on and off, with a weight
Parameters:
[in] _weight input to determin the weight of the seek steering behaviour, 0 turns off the behaviour
Definition at line 112 of file Agent.cpp.
References SteeringBehaviour::SeekOff(), SteeringBehaviour::SeekOn(), SteeringBehaviour::setSeekWeight(), and Vehicle::Steering().
{
  if(_weight <= 0.0)
  {
    Vehicle::Steering()->SeekOff();
  }
  else
  {
    Vehicle::Steering()->SeekOn();
    Vehicle::Steering()->setSeekWeight(_weight);
  }
}
void Agent::separation (double _weight)
used to expose the function to Lua, so separation steering behaviour can be turned on and off, with a weight
Parameters:
[in] _weight input to determin the weight of the separation steering behaviour, 0 turns off the behaviour
Definition at line 154 of file Agent.cpp.
References SteeringBehaviour::SeparationOff(), SteeringBehaviour::SeparationOn(), SteeringBehaviour::setSeparationWeight(), and Vehicle::Steering().
{
  if(_weight <= 0.0)
  {
    Vehicle::Steering()->SeparationOff();
  }
  else
  {
    Vehicle::Steering()->SeparationOn();
    Vehicle::Steering()->setSeparationWeight(_weight);
  }
}
void Agent::setDamage (const float _val) [inline]
sets the damage of the agent
Parameters:
[in] _val input to set the damage to
Definition at line 193 of file Agent.h.
References m_damage.
{ m_damage = _val; }
void Agent::setEnergy (const float _val) [inline]
sets the energy of the agent
Parameters:
[in] _val input to set the energy to
Definition at line 163 of file Agent.h.
References m_energy.
{ m_energy = _val; }
void Agent::setHasPathHome (const bool _val) [inline]
sets if the agent has a valid path home
Parameters:
[in] _val if input is true then there is a valid path, if it is false then there is not a valid path
Definition at line 143 of file Agent.h.
References m_hasPathHome.
{ m_hasPathHome = _val; }
void Agent::setHealth (const float _val) [inline]
sets the health of the agent
Parameters:
[in] _val input to set the health to
Definition at line 153 of file Agent.h.
References m_health.
{ m_health = _val; }
void Agent::setHomePos (const ngl::Vec3 _val) [inline]
sets the position of the agent's home
Parameters:
[in] _val input to set the agent's home position
Definition at line 133 of file Agent.h.
References m_homePos.
{ m_homePos = _val; }
void Agent::setHopHeight (const float _val) [inline]
sets the height of the agent's hop for drawing
Parameters:
[in] _val input to set how height the agent hops
Definition at line 213 of file Agent.h.
References m_hopHeight.
{ m_hopHeight = _val; }
void Agent::setHopSpeed (float _val) [inline]
sets the speed of the agent's hop
Parameters:
[in] _val input to set how freqently the agent hops
Definition at line 223 of file Agent.h.
References m_hopSpeed.
{ m_hopSpeed = _val; }
void Agent::setMaxSpeed (const float _maxSpeed) [inline]
sets the maximum speed of the agent
Parameters:
[in] _maxSpeed input to set the maximum speed of the agent
Reimplemented from MovingEntity.
Definition at line 203 of file Agent.h.
References MovingEntity::m_maxSpeed.
{m_maxSpeed = _maxSpeed;}
void Agent::setMorale (const float _val) [inline]
sets the morale of the agent
Parameters:
[in] _val input to set the morale to
Definition at line 173 of file Agent.h.
References m_morale.
{ m_morale = _val; }
void Agent::setRage (const float _val) [inline]
sets the rage of the agent
Parameters:
[in] _val input to set the rage to
Definition at line 183 of file Agent.h.
References m_rage.
{ m_rage = _val; }
void Agent::setTargetID (const int _val)
sets the health of the agent
Parameters:
[in] _val input to set the agent's target ID to
Definition at line 182 of file Agent.cpp.
References EntityManager::getEntityFromID(), BaseGameEntity::m_entityMgr, m_targetID, SteeringBehaviour::setTargetAgent(), and Vehicle::Steering().
{
  m_targetID = _val;
  if (_val < 0)
  {
      Vehicle::Steering()->setTargetAgent(NULL);
  }
  else
  {
    Vehicle::Steering()->setTargetAgent((Vehicle*)m_entityMgr->getEntityFromID(m_targetID));
  }
}
bool Agent::targetWithinReach (float _reach)
determins if the target agent is within reach
Parameters:
[in] _reach the input of how far the agent can reach
Definition at line 226 of file Agent.cpp.
References EntityManager::getEntityFromID(), BaseGameEntity::getPos(), BaseGameEntity::m_entityMgr, BaseGameEntity::m_pos, and m_targetID.
{
  Agent* target = dynamic_cast<Agent*>(m_entityMgr->getEntityFromID(m_targetID));
  if((m_pos - target->getPos()).lengthSquared() <= (_reach * _reach))
  {
    return true;
  }
  else
  {
    return false;
  }
}
void Agent::update (double timeElapsed, double currentTime) [pure virtual]
virtual pure method to update the agent every tick
Parameters:
[in] _timeElapsed the time elapsed between each tick
[in] _currentTime the current time of the level
Implemented in Police, and Rioter.
Definition at line 22 of file Agent.cpp.
{
  Vehicle::update(timeElapsed);
}
void Agent::wander (double _weight)
used to expose the function to Lua, so wander steering behaviour can be turned on and off, with a weight
Parameters:
[in] _weight input to determin the weight of the wander steering behaviour, 0 turns off the behaviour
Definition at line 70 of file Agent.cpp.
References SteeringBehaviour::setWanderWeight(), Vehicle::Steering(), SteeringBehaviour::WanderOff(), and SteeringBehaviour::WanderOn().
{
  if(_weight <= 0.0)
  {
    Vehicle::Steering()->WanderOff();
  }
  else
  {
    Vehicle::Steering()->WanderOn();
    Vehicle::Steering()->setWanderWeight(_weight);
  }
}
Member Data Documentation
lua_State* Agent::L [protected]
the Lua state registered with the agent
Definition at line 229 of file Agent.h.
float Agent::m_damage [protected]
the damage value of the agent
Definition at line 273 of file Agent.h.
float Agent::m_detectionRadius [protected]
the detection radius of the agent
Reimplemented from BaseGameEntity.
Definition at line 253 of file Agent.h.
float Agent::m_energy [protected]
the energy value of the agent
Definition at line 261 of file Agent.h.
Timer* Agent::m_gameTimer [protected]
a pointer to the Timer monostate class
Definition at line 233 of file Agent.h.
bool Agent::m_hasPathHome [protected]
if the agent has a valid path home
Definition at line 249 of file Agent.h.
float Agent::m_health [protected]
the health value of the agent
Definition at line 257 of file Agent.h.
ngl::Vec3 Agent::m_homePos [protected]
the position vector of the agent's home
Definition at line 245 of file Agent.h.
double Agent::m_hop [protected]
the current value of the agent's height in it's hop sine cycle
Definition at line 277 of file Agent.h.
float Agent::m_hopHeight [protected]
the hop height value of the agent
Definition at line 281 of file Agent.h.
float Agent::m_hopSpeed [protected]
the hop frequency of the agent
Definition at line 285 of file Agent.h.
ngl::Obj* Agent::m_mesh [protected]
the mesh used to draw the agent in the world
Definition at line 237 of file Agent.h.
float Agent::m_morale [protected]
the morale value of the agent
Definition at line 265 of file Agent.h.
float Agent::m_rage [protected]
the rage value of the agent
Definition at line 269 of file Agent.h.
int Agent::m_targetID [protected]
the value of the target agent's ID
Definition at line 241 of file Agent.h.
The documentation for this class was generated from the following files:
Agent.h
Agent.cpp