YOURPROJECTNAMEGOESHERE: UIButton Class Reference
UIButton Class Reference
A simple button class that uses SDL TTF text and NGL triangle planes.
#include <UIButton.h>
Public Member Functions
UIButton (eButtonName _name, ngl::Vec2 _windowDimensions)
ctor to create a simple button that does not have any text functionality
UIButton (eButtonName _name, std::string _font, int _fontSize, ngl::Vec2 _windowDimensions)
ctor to create a simple button that has additional text functionality
~UIButton ()
dtor cleans up any text pointeres if necessary
void updateButton (ngl::Vec2 _pos, ngl::Vec2 _dimensions, ngl::Vec4 _colour)
method used to updated the button position, dimensions and colour
void updateText (std::string _text, ngl::Vec3 _colour, ngl::Vec2 _offset)
method used to update the text string, colour and offset from the button centre
void addText (std::string _font, int _fontSize)
if the button does not have text it adds text drawing functionality
bool isClicked (int _x, int _y)
a method to detect if a button has been clicked, based on it's NDC screen position and dimensions
eButtonName getName ()
gets the enum name of the button
void setName (const eButtonName _name)
sets the enum name of the button
bool getIsActive ()
gets if the button is active or not
void setIsActive (const bool _inBool)
sets if the button is active or inactive
ngl::Vec2 getWindowDimensions ()
gets the window dimensions that are used by the button for scaling
void setWindowDimensions (const ngl::Vec2 _windowDimensions)
sets the window dimensions to be used by the button for scaling
ngl::Vec2 getButtonPosition ()
gets the button position in NDC
void setButtonPosition (const ngl::Vec2 _pos)
sets the button position in NDC
ngl::Vec2 getButtonDimension ()
gets the button dimensions in NDC
void setButtonDimension (const ngl::Vec2 _dimensions)
sets the button dimensions in NDC
ngl::Vec4 getButtonColour ()
gets the colour of the button
void setButtonColour (const ngl::Vec4 _colour)
sets the colour of the button
bool getHasText ()
gets if the button has valid text
void setHasText (const bool _inBool)
sets if the button has text or does not have text
std::string getTextString ()
gets the text string that is being displayed
void setTextString (std::string _text)
sets the text string of the button
ngl::Vec2 getTextPos ()
gets the position of the text in NDC
ngl::Vec2 getTextOffset ()
gets the amout of pixel offset applied to the text
void setTextOffset (ngl::Vec2 _offset)
sets the pixel offset of the text from the centre of the button
void setTextColour (ngl::Vec3 _colour)
sets the colour of the text
void draw ()
draws the button, and any text if necessary
void loadMatricesToShader ()
method to load transform data to the shaders
Private Attributes
eButtonName m_name
the enum name used by the button
bool m_isActive
boolean to determin if the button is active
ngl::Vec2 m_windowDimensions
the x and y values of the window dimensions
ngl::Vec2 m_buttonPos
the x and y position of the button in NDC
ngl::Vec2 m_buttonDimensions
the x and y dimensions of the button in NDC
ngl::Vec4 m_buttonColour
the r, g, b, a values of the button colour
Text * m_text
pointer to a text object
bool m_hasText
boolean to determin if the button has text
std::string m_textString
the text string that is displayed on screen
ngl::Vec2 m_textPos
the position of the text in NDC
ngl::Vec2 m_textOffset
the pixel offset of the text from the centre of the button
Detailed Description
A simple button class that uses SDL TTF text and NGL triangle planes.
Author:
Will Herbert
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 39 of file UIButton.h.
Constructor & Destructor Documentation
UIButton::UIButton (eButtonName _name, ngl::Vec2 _windowDimensions)
ctor to create a simple button that does not have any text functionality
Parameters:
[in] _name enum name to set as the name of the button
[in] _windowDimensions width and height of the initial window, used for correct UI scaling
Definition at line 12 of file UIButton.cpp.
References m_hasText, m_isActive, m_name, and m_windowDimensions.
{
  m_name = _name;
  m_windowDimensions = _windowDimensions;
  m_hasText = false;
  m_isActive = true;
}
UIButton::UIButton (eButtonName _name, std::string _font, int _fontSize, ngl::Vec2 _windowDimensions)
ctor to create a simple button that has additional text functionality
Parameters:
[in] _name enum name to set as the name of the button
[in] _font the font of the text, cannot be changed after construction
[in] _fontSize the size of the text, cannot be changed after contruction
[in] _windowDimensions width and height of the initial window, used for correct UI scaling
Definition at line 21 of file UIButton.cpp.
References m_hasText, m_isActive, m_name, m_text, and m_windowDimensions.
{
  m_name = _name;
  m_text = new Text(_font, _fontSize);
  m_windowDimensions = _windowDimensions;
  m_hasText = true;
  m_isActive = true;
}
UIButton::~UIButton ()
dtor cleans up any text pointeres if necessary
Definition at line 31 of file UIButton.cpp.
References m_hasText, and m_text.
{
  if (m_hasText)
  {
    delete m_text;
  }
}
Member Function Documentation
void UIButton::addText (std::string _font, int _fontSize)
if the button does not have text it adds text drawing functionality
Parameters:
[in] _font the font of the text, cannot be changed after addition
[in] _fontSize the size of the text, cannot be changed after addition
Definition at line 66 of file UIButton.cpp.
References m_hasText, and m_text.
{
  if (m_hasText == false)
  {
    m_text = new Text(_font, _fontSize);
    m_hasText = true;
  }
  else
  {
    std::cout<<"Error: This button already has text."<<std::endl;
  }
}
void UIButton::draw ()
draws the button, and any text if necessary
Definition at line 163 of file UIButton.cpp.
References loadMatricesToShader(), m_buttonDimensions, m_hasText, m_text, m_textOffset, m_textPos, m_textString, and Text::renderText().
{
  loadMatricesToShader();
  ngl::VAOPrimitives::instance()->createTrianglePlane("button", m_buttonDimensions.m_x, m_buttonDimensions.m_y, 1, 1, ngl::Vec3(0, 1, 0));
  ngl::VAOPrimitives::instance()->draw("button");
  if (m_hasText == true)
  {
    m_text->renderText(m_textPos.m_x + m_textOffset.m_x, m_textPos.m_y + m_textOffset.m_y, m_textString);
  }
}
ngl::Vec4 UIButton::getButtonColour () [inline]
gets the colour of the button
Returns:
ngl::Vec4 the r, g, b, a values of the button colour
Definition at line 140 of file UIButton.h.
References m_buttonColour.
{ return m_buttonColour; }
ngl::Vec2 UIButton::getButtonDimension () [inline]
gets the button dimensions in NDC
Returns:
ngl::Vec2 the x and y dimensions of the button in NDC
Definition at line 130 of file UIButton.h.
References m_buttonDimensions.
{ return m_buttonDimensions; }
ngl::Vec2 UIButton::getButtonPosition () [inline]
gets the button position in NDC
Returns:
ngl::Vec2 the x and y position of the button in NDC
Definition at line 120 of file UIButton.h.
References m_buttonPos.
{ return m_buttonPos; }
bool UIButton::getHasText () [inline]
gets if the button has valid text
Returns:
bool returns true if the button has text, false if it does not have text
Definition at line 150 of file UIButton.h.
References m_hasText.
{ return m_hasText; }
bool UIButton::getIsActive () [inline]
gets if the button is active or not
Returns:
bool true if the button is active, false if it is inactive
Definition at line 100 of file UIButton.h.
References m_isActive.
{ return m_isActive; }
eButtonName UIButton::getName () [inline]
gets the enum name of the button
Returns:
enum eButtonName the enum value of the name
Definition at line 90 of file UIButton.h.
References m_name.
{ return m_name; }
ngl::Vec2 UIButton::getTextOffset ()
gets the amout of pixel offset applied to the text
Returns:
the x and y pixel offset applied to the text
Definition at line 124 of file UIButton.cpp.
References m_hasText, and m_textOffset.
{
  if (m_hasText)
  {
    return m_textOffset;
  }
  else
  {
    std::cout<<"The button does not have text"<<std::endl;
  }
}
ngl::Vec2 UIButton::getTextPos ()
gets the position of the text in NDC
Returns:
the x and y position of the text in NDC
std::string UIButton::getTextString ()
gets the text string that is being displayed
Returns:
std::string returns the text string that is being displayed
Definition at line 98 of file UIButton.cpp.
References m_hasText, and m_textString.
{
  if (m_hasText)
  {
    return m_textString;
  }
  else
  {
    std::cout<<"The button does not have text"<<std::endl;
  }
}
ngl::Vec2 UIButton::getWindowDimensions () [inline]
gets the window dimensions that are used by the button for scaling
Returns:
ngl::Vec2 the width and height of the window dimensions
Definition at line 110 of file UIButton.h.
References m_windowDimensions.
{ return m_windowDimensions; }
bool UIButton::isClicked (int _x, int _y)
a method to detect if a button has been clicked, based on it's NDC screen position and dimensions
Parameters:
[in] _x the input x pixel position of the mouse click
[in] _y the input y pixel position of the mouse click
Definition at line 80 of file UIButton.cpp.
References m_buttonDimensions, m_buttonPos, and m_windowDimensions.
{
  ngl::Vec2 ndc;
  ndc.m_x = ((2.f * _x) / m_windowDimensions.m_x) - 1.f;
  ndc.m_y = 1.f - ((2.f * _y) / m_windowDimensions.m_y);
  if (ndc.m_x >= (m_buttonPos.m_x - m_buttonDimensions.m_x/2) && ndc.m_x <= (m_buttonPos.m_x + m_buttonDimensions.m_x/2) &&
      ndc.m_y >= (m_buttonPos.m_y - m_buttonDimensions.m_y/2) && ndc.m_y <= (m_buttonPos.m_y + m_buttonDimensions.m_y/2))
  {
    return true;
  }
  else
  {
    return false;
  }
}
void UIButton::loadMatricesToShader ()
method to load transform data to the shaders
Definition at line 175 of file UIButton.cpp.
References m_buttonColour, and m_buttonPos.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  (*shader)["nglColourShader"]->use();
  shader->setShaderParam4f("Colour", m_buttonColour.m_x, m_buttonColour.m_y,m_buttonColour.m_z, 1.f);
  ngl::Transformation t;
  t.setPosition(ngl::Vec3(m_buttonPos.m_x, m_buttonPos.m_y, 0.f));
  t.setRotation(90.f, 0.f, 0.f);
  ngl::Mat4 M;
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  M=t.getMatrix();
  MV=  M*ngl::lookAt(ngl::Vec3(0, 0, 10), ngl::Vec3(0, 0, 0), ngl::Vec3(0, 1, 0));
  MVP= MV*ngl::ortho(-1, 1, -1, 1, 0.1f, 100.f);
  shader->setShaderParamFromMat4("MVP",MVP);
}
void UIButton::setButtonColour (const ngl::Vec4 _colour) [inline]
sets the colour of the button
Parameters:
[in] _colour the r, g, b, a to assign to the button colour
Definition at line 145 of file UIButton.h.
References m_buttonColour.
{ m_buttonColour = _colour; }
void UIButton::setButtonDimension (const ngl::Vec2 _dimensions) [inline]
sets the button dimensions in NDC
Parameters:
[in] _dimensions the x and y dimensions in NDC to set the button to
Definition at line 135 of file UIButton.h.
References m_buttonDimensions.
{ m_buttonDimensions = _dimensions; }
void UIButton::setButtonPosition (const ngl::Vec2 _pos) [inline]
sets the button position in NDC
Parameters:
[in] _pos the x and y position in NDC to set the button to
Definition at line 125 of file UIButton.h.
References m_buttonPos.
{ m_buttonPos = _pos; }
void UIButton::setHasText (const bool _inBool) [inline]
sets if the button has text or does not have text
Parameters:
[in] _inBool the boolean to set if the button has text or does not have text
Definition at line 155 of file UIButton.h.
References m_hasText.
{ m_hasText = _inBool; }
void UIButton::setIsActive (const bool _inBool) [inline]
sets if the button is active or inactive
Parameters:
[in] _inBool the boolean to set if the button is active or inactive
Definition at line 105 of file UIButton.h.
References m_isActive.
{ m_isActive = _inBool; }
void UIButton::setName (const eButtonName _name) [inline]
sets the enum name of the button
Parameters:
[in] _name the input enum name to give to the button
Definition at line 95 of file UIButton.h.
References m_name.
{ m_name = _name; }
void UIButton::setTextColour (ngl::Vec3 _colour)
sets the colour of the text
Parameters:
[in] _colour the r, g, b values to be assigned to the text colour
Definition at line 150 of file UIButton.cpp.
References m_hasText, m_text, and Text::setColour().
{
  if (m_hasText)
  {
    m_text->setColour(_colour.m_x, _colour.m_y, _colour.m_z);
  }
  else
  {
    std::cout<<"The button does not have text"<<std::endl;
  }
}
void UIButton::setTextOffset (ngl::Vec2 _offset)
sets the pixel offset of the text from the centre of the button
Parameters:
[in] _offset the x and y pixel offset to be applied to the button
Definition at line 137 of file UIButton.cpp.
References m_hasText, and m_textOffset.
{
  if (m_hasText)
  {
    m_textOffset = _offset;
  }
  else
  {
    std::cout<<"The button does not have text"<<std::endl;
  }
}
void UIButton::setTextString (std::string _text)
sets the text string of the button
Parameters:
[in] _text the text string input to display
Definition at line 111 of file UIButton.cpp.
References m_hasText, and m_textString.
{
  if (m_hasText)
  {
    m_textString = _text;
  }
  else
  {
    std::cout<<"The button does not have text"<<std::endl;
  }
}
void UIButton::setWindowDimensions (const ngl::Vec2 _windowDimensions) [inline]
sets the window dimensions to be used by the button for scaling
Parameters:
[in] _windowDimensions the width and height to be used by the button for scaling
Definition at line 115 of file UIButton.h.
References m_windowDimensions.
{ m_windowDimensions = _windowDimensions; }
void UIButton::updateButton (ngl::Vec2 _pos, ngl::Vec2 _dimensions, ngl::Vec4 _colour)
method used to updated the button position, dimensions and colour
Parameters:
[in] _pos input NDC position to set as new button position
[in] _dimensions input NDC dimensions to set as new button dimensions
[in] _colour input colour to set as the new button colour
Definition at line 40 of file UIButton.cpp.
References m_buttonColour, m_buttonDimensions, and m_buttonPos.
{
  m_buttonPos = _pos;
  m_buttonDimensions = _dimensions;
  m_buttonColour = _colour;
}
void UIButton::updateText (std::string _text, ngl::Vec3 _colour, ngl::Vec2 _offset)
method used to update the text string, colour and offset from the button centre
Parameters:
[in] _text input std::string to set as the new text string to display
[in] _colour input colour to set as the new text colour
[in] _offset input pixel offset to set as the new text offset from the button centre
Definition at line 48 of file UIButton.cpp.
References m_buttonPos, m_hasText, m_text, m_textOffset, m_textPos, m_textString, m_windowDimensions, and Text::setColour().
{
  if (m_hasText == true)
  {
    m_textString = _text;
    m_text->setColour(_colour.m_x, _colour.m_y, _colour.m_z);
    m_textOffset = _offset;
    m_textPos.m_x = ((m_buttonPos.m_x + 1) * m_windowDimensions.m_x) / 2;
    m_textPos.m_y = ((1 - m_buttonPos.m_y) * m_windowDimensions.m_y) / 2;
  }
  else
  {
    std::cout<<"Error: Text has not been initialised for this button."<<std::endl;
  }
}
Member Data Documentation
ngl::Vec4 UIButton::m_buttonColour [private]
the r, g, b, a values of the button colour
Definition at line 219 of file UIButton.h.
ngl::Vec2 UIButton::m_buttonDimensions [private]
the x and y dimensions of the button in NDC
Definition at line 215 of file UIButton.h.
ngl::Vec2 UIButton::m_buttonPos [private]
the x and y position of the button in NDC
Definition at line 211 of file UIButton.h.
bool UIButton::m_hasText [private]
boolean to determin if the button has text
Definition at line 227 of file UIButton.h.
bool UIButton::m_isActive [private]
boolean to determin if the button is active
Definition at line 203 of file UIButton.h.
eButtonName UIButton::m_name [private]
the enum name used by the button
Definition at line 199 of file UIButton.h.
Text* UIButton::m_text [private]
pointer to a text object
Definition at line 223 of file UIButton.h.
ngl::Vec2 UIButton::m_textOffset [private]
the pixel offset of the text from the centre of the button
Definition at line 239 of file UIButton.h.
ngl::Vec2 UIButton::m_textPos [private]
the position of the text in NDC
Definition at line 235 of file UIButton.h.
std::string UIButton::m_textString [private]
the text string that is displayed on screen
Definition at line 231 of file UIButton.h.
ngl::Vec2 UIButton::m_windowDimensions [private]
the x and y values of the window dimensions
Definition at line 207 of file UIButton.h.
The documentation for this class was generated from the following files:
UIButton.h
UIButton.cpp