YOURPROJECTNAMEGOESHERE: NGLDraw Class Reference
NGLDraw Class Reference
Controls drawing and updating all entities in the game and any UI elements.
#include <NGLDraw.h>
Public Member Functions
NGLDraw ()
ctor this will have a valid OpenGL context so we can create gl stuff
NGLDraw (int _width, int _height)
~NGLDraw ()
dtor used to remove any NGL stuff created
void resize (int _w, int _h)
resize our screen and set the camera aspect ratio
void startGame (int _level)
starts a new level by contructing new GameWorld with level specified by buttons
void endGame ()
ends the current level by calling destructors and resetting the timer
void draw ()
draw the scene
void update (double _timeElapsed, double _currentTime)
update the scene
void mouseMoveEvent (const SDL_MouseMotionEvent &_event)
this method is called every time a mouse is moved
void mousePressEvent (const SDL_MouseButtonEvent &_event)
this method is called every time a mouse button is presses
void mouseReleaseEvent (const SDL_MouseButtonEvent &_event)
this method is called everytime the mouse button is released
void wheelEvent (const SDL_MouseWheelEvent &_event)
this method is called everytime the mouse wheel is moved
void doSelection (const int _x, const int _y)
selectes a squad using colour differences, if there is a valid squad icon below the cursor
void doMovement (const int _x, const int _y)
sets a taget location for the currently selected squad, if there is one
ngl::Vec3 getWorldSpace (const int _x, const int _y)
a method to convert the screen coordinates of the mouse click to world coordinates
void initialiseUI ()
initialises all of the buttons, sliders and text to be used in the user interface and menu
eGameState getGameState () const
gets the current game state
void setGameState (const eGameState _gameState)
sets the current game state
Private Member Functions
void loadMatricesToShader ()
method to load transform data to the shaders
Private Attributes
int m_spinXFace
used to store the x rotation mouse value
int m_spinYFace
used to store the y rotation mouse value
bool m_rotate
flag to indicate if the mouse button is pressed when dragging
bool m_translate
flag to indicate if the Right mouse button is pressed when dragging
int m_origX
the previous x mouse value
int m_origY
the previous y mouse value
int m_origXPos
the previous x mouse value for Position changes
int m_origYPos
the previous y mouse value for Position changes
ngl::Mat4 m_mouseGlobalTX
used to store the global mouse transforms
ngl::Camera * m_cam
Our Camera.
ngl::Camera * m_camOrth
ngl::Vec3 m_modelPos
the model position for mouse movement
ngl::Light * m_light
a simple light use to illuminate the screen
ngl::SpotLight m_spot
a simple spot light used to create the the effect of a light from a helicopter
ngl::Transformation m_trans
a NGL transformation tool
GameWorld * m_gameworld
the game world for all entities to be created in
eGameState m_gameState
the current state of the game
EntityManager * m_entityMgr
a pointer to the entity manager, used to access multiple enitites
Timer m_gameTimer
the timer that contains the current time and time elapsed between each tick
bool m_selected
booleon to determin if a squad has been selected or not
Squad * m_selectedSquad
a pointer to the currently selected squad
int m_selectedSquadID
the ID of the currently selected squad
ngl::Vec3 m_clickPosition
the position of the mouse click in world space
ngl::Colour m_squadCurrentColour
the current squad's current colour
ngl::Colour m_patrolColour
the colour used to represent a squad in the patrol state, and the colour of the patrol button
ngl::Colour m_defensiveColour
the colour used to represent a squad in the defensive state, and the colour of the defensive button
ngl::Colour m_aggressiveColour
the colour used to represent a squad in the aggressive state, and the colour of the aggressive button
ngl::Colour m_wallColour
the colour used to represend a squad in the wall state, and the colour of the wall button
Text * m_textSmall
a pointer to the text class used to display all small text in the UI
Text * m_textMedium
a pointer to the text class used to display all medium text in the UI
Text * m_textLarge
a pointer to the text class used to display all large text in the UI
std::vector< UIButton * > m_buttons
a vector containing all buttons in the UI, allowing for checking against mouse clicks
UIButton * m_buttonPlay
a button that is used to start a new level
UIButton * m_buttonLevel1
a button that is used to toggle the level to start level 1
UIButton * m_buttonLevel2
a button that is used to toggle the level to start level 2
UIButton * m_buttonLevel3
a button that is used to toggle the level to start level 3
UIButton * m_buttonLevel4
a button that is used to toggle the level to start level 4
UIButton * m_buttonLevel5
a button that is used to toggle the level to start level 5
int m_selectedLevel
an integer holding the currently selected level to start
UIButton * m_buttonQuit
a button that is used to quit the game
UIButton * m_buttonPause
a button that is used to pause the game
UIButton * m_buttonMenu
a button that is used to return to the menu
UIButton * m_buttonCreateSquad
a button that is used in game to create a new squad
UIButton * m_buttonSquadPatrol
a button that is used in game to set the squad state to patrol
UIButton * m_buttonSquadAggressive
a button that is used in game to set the squad state to aggressive
UIButton * m_buttonSquadDefensive
a button that is used in game to set the squad state to defensive
UIButton * m_buttonSquadWall
a button that is used in game to set the squad state to wall
UIButton * m_buttonRioterDeadBar
a button to represent the amount of rioters that have been killed
UIButton * m_buttonRioterHomeBar
a button to respresent the amount of rioters that have gone home and left the map
UISlider * m_sliderSquadSize
a slider used to control the number of policemen to assign to the next spawned squad
int m_squadSize
the size of the squad to be spawned when the create squad button is clicked
std::string m_squadSizeString
a conversion of the size of squad to be spawn to a string used for displaying in the UI
std::stringstream m_ss
a string stream used for conversion throughout NGLDraw
float m_width
the width of the window
float m_height
the height of the window
float m_longestSide
the longest side of the screen, used for zooming correctly
Detailed Description
Controls drawing and updating all entities in the game and any UI elements.
Author:
Jon Macey, Will Herbert
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 40 of file NGLDraw.h.
Constructor & Destructor Documentation
NGLDraw::NGLDraw ()
ctor this will have a valid OpenGL context so we can create gl stuff
NGLDraw::NGLDraw (int _width, int _height)
Definition at line 19 of file NGLDraw.cpp.
References cameraHeight, gameMenu, initialiseUI(), m_aggressiveColour, m_cam, m_defensiveColour, m_entityMgr, m_gameState, m_height, m_light, m_patrolColour, m_rotate, m_selectedLevel, m_spinXFace, m_spinYFace, m_spot, m_squadCurrentColour, m_wallColour, and m_width.
{
  m_patrolColour = ngl::Colour(0.0f, 0.25f, 0.6f);
  m_defensiveColour = ngl::Colour(0.5f, 0.4f, 0.5f);
  m_aggressiveColour = ngl::Colour(0.3f, 0.0f, 0.2f);
  m_wallColour = ngl::Colour(0.3f, 0.5f, 0.5f);
  //Mouse rotation values
  m_rotate=false;
  m_spinXFace=0;
  m_spinYFace=0;
  // Grey Background
  // enable depth testing for drawing
  glEnable(GL_DEPTH_TEST);
   // now to load the shader and set the values
  // grab an instance of shader manager
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  // we are creating a shader called Phong
  shader->createShaderProgram("Phong");
  // now we are going to create empty shaders for Frag and Vert
  shader->attachShader("PhongVertex",ngl::VERTEX);
  shader->attachShader("PhongFragment",ngl::FRAGMENT);
  // attach the source
  shader->loadShaderSource("PhongVertex","shaders/PhongVertex.glsl");
  shader->loadShaderSource("PhongFragment","shaders/PhongFragment.glsl");
  // compile the shaders
  shader->compileShader("PhongVertex");
  shader->compileShader("PhongFragment");
  // add them to the program
  shader->attachShaderToProgram("Phong","PhongVertex");
  shader->attachShaderToProgram("Phong","PhongFragment");
  // now bind the shader attributes for most NGL primitives we use the following
  // layout attribute 0 is the vertex data (x,y,z)1
  shader->bindAttribute("Phong",0,"inVert");
  // attribute 1 is the UV data u,v (if present)
  shader->bindAttribute("Phong",1,"inUV");
  // attribute 2 are the normals x,y,z
  shader->bindAttribute("Phong",2,"inNormal");
  // now we have associated this data we can link the shader
  shader->linkProgramObject("Phong");
  // and make it active ready to load values
  (*shader)["Phong"]->use();
  // the shader will use the currently active material and light0 so set them
  ngl::Material m(ngl::POLISHEDSILVER);
  // load our material values to the shader into the structure material (see Vertex shader)
  m.loadToShader("material");
  // Now we will create a basic Camera from the graphics library
  // This is a static camera so it only needs to be set once
  // First create Values for the camera position
  ngl::Vec3 from(0,cameraHeight,0);
  ngl::Vec3 to(0,0,0);
  ngl::Vec3 up(0,0,-1);
  // now load to our new camera
  m_cam= new ngl::Camera(from,to,up);
  // set the shape using FOV 45 Aspect Ratio based on Width and Height
  // The final two are near and far clipping planes of 0.5 and 10
  m_cam->setShape(45,(float)m_width/m_height,0.05,350);
  shader->setShaderParam3f("viewerPos",m_cam->getEye().m_x,m_cam->getEye().m_y,m_cam->getEye().m_z);
  // now create our light this is done after the camera so we can pass the
  // transpose of the projection matrix to the light to do correct eye space
  // transformations
  ngl::Mat4 iv=m_cam->getVPMatrix();
  iv.transpose();
  m_light = new ngl::Light(ngl::Vec3(-20,0,0),ngl::Colour(0.3,0.3,0.4,1),ngl::Colour(1,1,1,1),ngl::POINTLIGHT );
  m_light->setPosition(ngl::Vec3(0,20,50));
  //m_light->setTransform(iv);
  // load these values to the shader as well
  m_light->loadToShader("light");
  //SPOT LIGHT:
  m_spot = ngl::SpotLight(ngl::Vec3(0,0,0),
           ngl::Vec3(0,1,0),ngl::Colour(0.5,0.4,0.4));
  m_spot.aim(ngl::Vec4(0,10,0));
  m_spot.setSpecColour(ngl::Colour(0.4,0.4,0.1,1));
  m_spot.setCutoff(15);
  m_spot.setInnerCutoff(10);
  m_spot.setExponent(2+1);
  m_spot.setAttenuation(1.0,0.0,0.0);
  m_spot.enable();
  m_spot.setTransform(iv);
  m_spot.loadToShader("spotLight");
  m_width = _width;
  m_height = _height;
  m_gameState = gameMenu;
  //Create new instance of entity manager.
  m_entityMgr = new EntityManager();
  initialiseUI();
  m_selectedLevel = 1;
  //Set Squad Circular indicator colour.
  m_squadCurrentColour =ngl::Colour(0.0f,0.5f,0.5f,1.0f);
}
NGLDraw::~NGLDraw ()
dtor used to remove any NGL stuff created
Definition at line 128 of file NGLDraw.cpp.
References m_buttonCreateSquad, m_buttonLevel1, m_buttonLevel2, m_buttonLevel3, m_buttonLevel4, m_buttonLevel5, m_buttonPause, m_buttonPlay, m_buttonQuit, m_buttonSquadWall, m_cam, m_entityMgr, m_light, m_sliderSquadSize, m_textMedium, and m_textSmall.
{
  delete m_entityMgr;
  ngl::NGLInit *Init = ngl::NGLInit::instance();
  std::cout<<"Shutting down NGL, removing VAO's and Shaders\n";
  delete m_light;
  delete m_cam;
  delete m_buttonPlay;
  delete m_buttonLevel1;
  delete m_buttonLevel2;
  delete m_buttonLevel3;
  delete m_buttonLevel4;
  delete m_buttonLevel5;
  delete m_buttonQuit;
  delete m_buttonPause;
  delete m_buttonCreateSquad;
  delete m_buttonSquadWall;
  delete m_sliderSquadSize;
  delete m_textSmall;
  delete m_textMedium;
  Init->NGLQuit();
}
Member Function Documentation
void NGLDraw::doMovement (const int _x, const int _y)
sets a taget location for the currently selected squad, if there is one
Parameters:
[in] _x the x screen position of the mouse
[in] _y the y screen position of the mouse
Definition at line 862 of file NGLDraw.cpp.
References EntityManager::getEntityMap(), getWorldSpace(), m_clickPosition, m_entityMgr, m_gameworld, m_selected, m_selectedSquad, m_selectedSquadID, and GameWorld::squadTarget().
{
    std::map<int, BaseGameEntity*>::const_iterator entity = m_entityMgr->getEntityMap().find(m_selectedSquadID);
    if(entity->first !=  m_entityMgr->getEntityMap().end()->first)
    {
        m_clickPosition = getWorldSpace(_x, _y);
        m_gameworld->squadTarget(m_selectedSquad, m_clickPosition);
        m_selected =false;
    }
}
void NGLDraw::doSelection (const int _x, const int _y)
selectes a squad using colour differences, if there is a valid squad icon below the cursor
Parameters:
[in] _x the x screen position of the mouse
[in] _Y the y screen position of the mouse
Definition at line 797 of file NGLDraw.cpp.
References Squad::checkSelectionColour(), doMovement(), BaseGameEntity::getID(), Squad::getSquadColour(), GameWorld::getSquads(), Squad::getSquadSelectedColour(), m_cam, m_gameworld, m_mouseGlobalTX, m_selected, m_selectedSquad, m_selectedSquadID, Squad::selectionDraw(), and Squad::setSquadDrawColour().
{
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  int numberOfSquads = m_gameworld->getSquads().size();
  for(int i=0; i < numberOfSquads; i++)
  {
    Squad* currentSquad = m_gameworld->getSquads()[i];
    currentSquad->selectionDraw(m_cam, m_mouseGlobalTX);
    currentSquad->setSquadDrawColour(currentSquad->getSquadColour());
  }
  ngl::Vec3 pixel;
  GLint viewport[4];
  glGetIntegerv(GL_VIEWPORT, viewport);
  glReadPixels(_x, viewport[3] - _y , 1, 1, GL_RGB, GL_FLOAT, &pixel);
  bool newSelection = false;
  for(int i=0; i < numberOfSquads; i++)
  {
    Squad* currentSquad = m_gameworld->getSquads()[i];
    if(currentSquad->checkSelectionColour(pixel) == true)
    {
      currentSquad->setSquadDrawColour(currentSquad->getSquadSelectedColour());
      //set selected squad colour
      if(m_selected == true)
      {
        m_selected = true;
        m_selectedSquad = currentSquad;
        m_selectedSquadID = currentSquad->getID();
        newSelection = true;
        break;
      }
      else
      {
        m_selected = true;
        m_selectedSquad = currentSquad;
        m_selectedSquadID = currentSquad->getID();
        newSelection = true;
        break;
      }
    }
  }
  if(newSelection == false && m_selected == true)
  {
    doMovement(_x, _y);
    m_selected = false;
    m_selectedSquad= NULL;
  }
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
}
void NGLDraw::draw ()
draw the scene
Definition at line 225 of file NGLDraw.cpp.
References UISlider::draw(), UIButton::draw(), GameWorld::draw(), gameMenu, gamePause, gamePlay, gameQuit, GameWorld::getAvailablePolice(), GameWorld::getHasLost(), GameWorld::getHasWon(), GameWorld::getNumberOfRiotersDead(), GameWorld::getNumberOfRiotersDeadToLose(), GameWorld::getNumberOfRiotersHome(), GameWorld::getNumberOfRiotersHomeToWin(), Squad::getPreviousState(), Squad::getSquadColour(), Squad::getSquadSelectedColour(), Squad::getSquadState(), m_aggressiveColour, m_buttonCreateSquad, m_buttonLevel1, m_buttonLevel2, m_buttonLevel3, m_buttonLevel4, m_buttonLevel5, m_buttonMenu, m_buttonPause, m_buttonPlay, m_buttonQuit, m_buttonRioterDeadBar, m_buttonRioterHomeBar, m_buttonSquadAggressive, m_buttonSquadDefensive, m_buttonSquadPatrol, m_buttonSquadWall, m_cam, m_defensiveColour, m_gameState, m_gameworld, m_modelPos, m_mouseGlobalTX, m_patrolColour, m_selected, m_selectedLevel, m_selectedSquad, m_sliderSquadSize, m_spinXFace, m_spinYFace, m_spot, m_squadCurrentColour, m_ss, m_textLarge, m_textMedium, m_wallColour, Text::renderText(), UIButton::setButtonColour(), UIButton::setButtonDimension(), UIButton::setButtonPosition(), UIButton::setIsActive(), Squad::setSquadDrawColour(), squadAggressive, squadDefensive, squadMove, squadPatrol, and squadWall.
{
  // clear the screen and depth buffer
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  glClearColor(0.1f, 0.1f, 0.1f, 1.0f);
//  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
//  (*shader)["Phong"]->use();
//  m_spot.setPosition(ngl::Vec3(100000,0,0));
//  m_spot.loadToShader("spotLight");
  switch (m_gameState)
  {
    case gamePlay:
    {
      // grab an instance of the shader manager
      ngl::ShaderLib *shader=ngl::ShaderLib::instance();
      (*shader)["Phong"]->use();
      m_spot.setPosition(ngl::Vec3(100000,0,0));
      m_spot.loadToShader("spotLight");
      // Rotation based on the mouse position for our global transform
      ngl::Mat4 rotX;
      ngl::Mat4 rotY;
      // create the rotation matrices
      rotX.rotateX(m_spinXFace);
      rotY.rotateY(m_spinYFace);
      // multiply the rotations
      m_mouseGlobalTX=rotY*rotX;
      // add the translations
      m_mouseGlobalTX.m_m[3][0] = m_modelPos.m_x;
      m_mouseGlobalTX.m_m[3][1] = m_modelPos.m_y;
      m_mouseGlobalTX.m_m[3][2] = m_modelPos.m_z;
      m_gameworld->draw(m_cam, m_mouseGlobalTX);
      m_buttonPause->draw();
      m_buttonMenu->draw();
      m_buttonCreateSquad->draw();
      if (m_selectedSquad)
      {
        m_squadCurrentColour = m_selectedSquad->getSquadColour();
        if(m_selected == false)
        {
           m_selectedSquad->setSquadDrawColour(m_squadCurrentColour);
        }
        else if(m_selected == true)
        {
           m_selectedSquad->setSquadDrawColour(m_selectedSquad->getSquadSelectedColour());
        }
        eSquadState buttonState;
        if(m_selectedSquad->getSquadState() == squadMove)
        {
          buttonState = m_selectedSquad->getPreviousState();
        }
        else
        {
          buttonState = m_selectedSquad->getSquadState();
        }
        switch (buttonState)
        {
          case squadPatrol :
          {
            m_buttonSquadPatrol->setButtonColour(ngl::Vec4(m_patrolColour.m_r, m_patrolColour.m_g, m_patrolColour.m_b, m_patrolColour.m_a));
            m_buttonSquadAggressive->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            m_buttonSquadDefensive->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            m_buttonSquadWall->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            break;
          }
          case squadAggressive :
          {
            m_buttonSquadPatrol->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            m_buttonSquadAggressive->setButtonColour(ngl::Vec4(m_aggressiveColour.m_r, m_aggressiveColour.m_g, m_aggressiveColour.m_b, m_aggressiveColour.m_a));
            m_buttonSquadDefensive->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            m_buttonSquadWall->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            break;
          }
          case squadDefensive :
          {
            m_buttonSquadPatrol->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            m_buttonSquadAggressive->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            m_buttonSquadDefensive->setButtonColour(ngl::Vec4(m_defensiveColour.m_r, m_defensiveColour.m_g, m_defensiveColour.m_b));
            m_buttonSquadWall->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            break;
          }
          case squadWall :
          {
            m_buttonSquadPatrol->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            m_buttonSquadAggressive->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            m_buttonSquadDefensive->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
            m_buttonSquadWall->setButtonColour(ngl::Vec4(m_wallColour.m_r, m_wallColour.m_g, m_wallColour.m_b));
            break;
          }
          case squadMove :
          {
            break;
          }
          default :
          {
            std::cout<<"Error: Invalid squad state"<<std::endl;
            break;
          }
        }
        m_buttonSquadPatrol->setIsActive(true);
        m_buttonSquadPatrol->draw();
        m_buttonSquadAggressive->setIsActive(true);
        m_buttonSquadAggressive->draw();
        m_buttonSquadDefensive->setIsActive(true);
        m_buttonSquadDefensive->draw();
        m_buttonSquadWall->setIsActive(true);
        m_buttonSquadWall->draw();
      }
      else
      {
        m_buttonSquadPatrol->setIsActive(false);
        m_buttonSquadAggressive->setIsActive(false);
        m_buttonSquadDefensive->setIsActive(false);
        m_buttonSquadWall->setIsActive(false);
      }
      float deadPercent = ((float)m_gameworld->getNumberOfRiotersDead() / (float)m_gameworld->getNumberOfRiotersDeadToLose());
      if (deadPercent > 1.f)
      {
        deadPercent = 1.f;
      }
      m_buttonRioterDeadBar->setButtonColour(ngl::Vec4(0.7f, 0.2f, 0.2, 1.f));
      m_buttonRioterDeadBar->setButtonDimension(ngl::Vec2(0.05f, (1.5f * deadPercent)));
      m_buttonRioterDeadBar->draw();
      m_buttonRioterDeadBar->setButtonColour(ngl::Vec4(0.9f, 0.9f, 0.9, 1.f));
      m_buttonRioterDeadBar->setButtonDimension(ngl::Vec2(0.05f, 1.5f));
      m_buttonRioterDeadBar->draw();
      float homePercent = ((float)m_gameworld->getNumberOfRiotersHome() / (float)m_gameworld->getNumberOfRiotersHomeToWin());
      if (homePercent > 1.f)
      {
        homePercent = 1.f;
      }
      m_buttonRioterHomeBar->setButtonColour(ngl::Vec4(0.2f, 0.7f, 0.2, 1.f));
      m_buttonRioterHomeBar->setButtonDimension(ngl::Vec2(0.05f, (1.5f * homePercent)));
      m_buttonRioterHomeBar->draw();
      m_buttonRioterHomeBar->setButtonPosition(ngl::Vec2(-0.85f, 0.f));
      m_buttonRioterHomeBar->setButtonColour(ngl::Vec4(0.9f, 0.9f, 0.9, 1.f));
      m_buttonRioterHomeBar->setButtonDimension(ngl::Vec2(0.05f, 1.5f));
      m_buttonRioterHomeBar->draw();
      if (m_gameworld->getHasWon() == true)
      {
        m_textLarge->renderText(50.f, 40.f, "You Win!");
      }
      else if (m_gameworld->getHasLost() == true)
      {
        m_textLarge->renderText(50.f, 40.f, "You Lose!");
      }
      m_sliderSquadSize->draw();
      m_ss.str(std::string());
      m_ss << m_gameworld->getAvailablePolice();
      m_textMedium->renderText(740.f, 950.f, m_ss.str());
      break;
    }
    case gameMenu:
    {
      glClearColor(0.0f, 0.3f, 0.3f, 1.0f);
      m_buttonPlay->draw();
      switch (m_selectedLevel)
      {
        case 1 :
        {
          m_buttonLevel1->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.4f));
          m_buttonLevel2->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel3->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel4->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel5->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          break;
        }
        case 2 :
        {
          m_buttonLevel1->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel2->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.4f));
          m_buttonLevel3->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel4->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel5->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          break;
        }
        case 3 :
        {
          m_buttonLevel1->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel2->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel3->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.4f));
          m_buttonLevel4->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel5->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          break;
        }
        case 4 :
        {
          m_buttonLevel1->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel2->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel3->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel4->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.4f));
          m_buttonLevel5->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          break;
        }
        case 5 :
        {
          m_buttonLevel1->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel2->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel3->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel4->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.9f));
          m_buttonLevel5->setButtonColour(ngl::Vec4(0.2f, 0.2f, 0.4f));
          break;
        }
      }
      m_buttonLevel1->draw();
      m_buttonLevel2->draw();
      m_buttonLevel3->draw();
      m_buttonLevel4->draw();
      m_buttonLevel5->draw();
      m_buttonQuit->draw();
      break;
    }
    case gamePause:
    {
      // grab an instance of the shader manager
      ngl::ShaderLib *shader=ngl::ShaderLib::instance();
      (*shader)["Phong"]->use();
      // Rotation based on the mouse position for our global transform
      ngl::Mat4 rotX;
      ngl::Mat4 rotY;
      // create the rotation matrices
      rotX.rotateX(m_spinXFace);
      rotY.rotateY(m_spinYFace);
      // multiply the rotations
      m_mouseGlobalTX=rotY*rotX;
      // add the translations
      m_mouseGlobalTX.m_m[3][0] = m_modelPos.m_x;
      m_mouseGlobalTX.m_m[3][1] = m_modelPos.m_y;
      m_mouseGlobalTX.m_m[3][2] = m_modelPos.m_z;
      m_gameworld->draw(m_cam, m_mouseGlobalTX);
      m_buttonPause->draw();
      m_buttonMenu->draw();
      break;
    }
    case gameQuit:
    {
      break;
    }
    default:
    {
      std::cout<<"Error: Invalid gameState"<<std::endl;
      break;
    }
  }
}
void NGLDraw::endGame ()
ends the current level by calling destructors and resetting the timer
Definition at line 214 of file NGLDraw.cpp.
References m_gameTimer, m_gameworld, and Timer::resetTimer().
{
  //Reset the timer, mouse and delete gameworld when the game session has ended
    m_gameTimer.resetTimer();
    delete m_gameworld;
}
eGameState NGLDraw::getGameState () const [inline]
gets the current game state
Returns:
eGameState returns the current game state enum value
Definition at line 123 of file NGLDraw.h.
References m_gameState.
{ return m_gameState; }
ngl::Vec3 NGLDraw::getWorldSpace (const int _x, const int _y)
a method to convert the screen coordinates of the mouse click to world coordinates
Parameters:
[in] _x the x screen position of the mouse
[in] _y the y screen position of the mouse
Definition at line 876 of file NGLDraw.cpp.
References m_cam, m_height, m_mouseGlobalTX, and m_width.
{
    ngl::Mat4 m;
    m = m*m_mouseGlobalTX;
    ngl::Mat4 t=m_cam->getProjectionMatrix();
    ngl::Mat4 v=m_cam->getViewMatrix();
    // as ngl:: and OpenGL use different formats need to transpose the matrix.
    t.transpose();
    v.transpose();
    m.transpose();
    ngl::Mat4 inverse=(t*v*m).inverse();
    ngl::Vec4 tmp(0,0,-1.0f,1.0f);
    // convert into NDC
    tmp.m_x=(2.0f * _x) / m_width- 1.0f;
    tmp.m_y=1.0f - (2.0f * _y) / m_height;
    // scale by inverse MV * Project transform
    ngl::Vec4 near(tmp.m_x,tmp.m_y,-1.0f,1.0f);
    ngl::Vec4 far(tmp.m_x,tmp.m_y,1.0f,1.0f);
    //get world point on near and far clipping planes
    ngl::Vec4 obj_near=inverse*near;
    ngl::Vec4 obj_far=inverse*far;
    // Scale by w
    obj_near/=obj_near.m_w;
    obj_far/=obj_far.m_w;
    ngl::Vec3 nearPoint(obj_near.m_x,obj_near.m_y,obj_near.m_z);
    ngl::Vec3 farPoint(obj_far.m_x,obj_far.m_y,obj_far.m_z);
    //create ray
    ngl::Vec3 rayDir(farPoint-nearPoint);
    if(rayDir.lengthSquared() == 0.0f)
    {
        std::cout<<"Ray Direction in getWorldSpace equals zero, can't normalise"<<std::endl;
    }
    else
    {
        rayDir.normalize();
    }
    //calculate distance to zx plane
    float dist = (-nearPoint.m_y)/rayDir.m_y;
    //set world space coordinate where y = 0
    ngl::Vec3 obj(nearPoint.m_x + (dist*rayDir.m_x),nearPoint.m_y + (dist*rayDir.m_y),nearPoint.m_z + (dist*rayDir.m_z));
    obj.m_y = 0.0;
    return obj;
}
void NGLDraw::initialiseUI ()
initialises all of the buttons, sliders and text to be used in the user interface and menu
Definition at line 932 of file NGLDraw.cpp.
References buttonCreateSquad, buttonLevel1, buttonLevel2, buttonLevel3, buttonLevel4, buttonLevel5, buttonMenu, buttonPause, buttonPlay, buttonQuit, buttonRioterDeadBar, buttonRioterHomeBar, buttonSquadAggressive, buttonSquadDefensive, buttonSquadPatrol, buttonSquadWall, UISlider::calculateOutput(), m_buttonCreateSquad, m_buttonLevel1, m_buttonLevel2, m_buttonLevel3, m_buttonLevel4, m_buttonLevel5, m_buttonMenu, m_buttonPause, m_buttonPlay, m_buttonQuit, m_buttonRioterDeadBar, m_buttonRioterHomeBar, m_buttons, m_buttonSquadAggressive, m_buttonSquadDefensive, m_buttonSquadPatrol, m_buttonSquadWall, m_height, m_sliderSquadSize, m_squadSize, m_squadSizeString, m_ss, m_textLarge, m_textMedium, m_textSmall, m_width, sliderSquadSize, UIButton::updateButton(), UISlider::updateSlider(), UISlider::updateText(), and UIButton::updateText().
{
  m_textSmall = new Text("font/arial.ttf", 20);
  m_textMedium = new Text("font/arial.ttf", 40);
  m_textLarge = new Text("font/arial.ttf", 60);
  m_buttonPlay = new UIButton(buttonPlay, "font/arial.ttf", 40, ngl::Vec2(m_width, m_height));
  m_buttonPlay->updateButton(ngl::Vec2(0.f, 0.1f), ngl::Vec2(0.5f, 0.2f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonPlay->updateText("New Game", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-98.f, -25.f));
  m_buttons.push_back(m_buttonPlay);
  m_buttonLevel1 = new UIButton(buttonLevel1, "font/arial.ttf", 30, ngl::Vec2(m_width, m_height));
  m_buttonLevel1->updateButton(ngl::Vec2(-0.2f, -0.1f), ngl::Vec2(0.1f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.4f, 1.f));
  m_buttonLevel1->updateText("1", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-9.f, -17.f));
  m_buttons.push_back(m_buttonLevel1);
  m_buttonLevel2 = new UIButton(buttonLevel2, "font/arial.ttf", 30, ngl::Vec2(m_width, m_height));
  m_buttonLevel2->updateButton(ngl::Vec2(-0.1f, -0.1f), ngl::Vec2(0.1f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonLevel2->updateText("2", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-9.f, -17.f));
  m_buttons.push_back(m_buttonLevel2);
  m_buttonLevel3 = new UIButton(buttonLevel3, "font/arial.ttf", 30, ngl::Vec2(m_width, m_height));
  m_buttonLevel3->updateButton(ngl::Vec2(0.f, -0.1f), ngl::Vec2(0.1f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonLevel3->updateText("3", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-9.f, -17.f));
  m_buttons.push_back(m_buttonLevel3);
  m_buttonLevel4 = new UIButton(buttonLevel4, "font/arial.ttf", 30, ngl::Vec2(m_width, m_height));
  m_buttonLevel4->updateButton(ngl::Vec2(0.1f, -0.1f), ngl::Vec2(0.1f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonLevel4->updateText("4", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-9.f, -17.f));
  m_buttons.push_back(m_buttonLevel4);
  m_buttonLevel5 = new UIButton(buttonLevel5, "font/arial.ttf", 30, ngl::Vec2(m_width, m_height));
  m_buttonLevel5->updateButton(ngl::Vec2(0.2f, -0.1f), ngl::Vec2(0.1f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonLevel5->updateText("5", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-9.f, -17.f));
  m_buttons.push_back(m_buttonLevel5);
  m_buttonQuit = new UIButton(buttonQuit,  "font/arial.ttf", 40, ngl::Vec2(m_width, m_height));
  m_buttonQuit->updateButton(ngl::Vec2(0.f, -0.3f), ngl::Vec2(0.5f, 0.2f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonQuit->updateText("Quit", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-40.f, -25.f));
  m_buttons.push_back(m_buttonQuit);
  m_buttonPause = new UIButton(buttonPause, "font/arial.ttf", 40, ngl::Vec2(m_width, m_height));
  m_buttonPause->updateButton(ngl::Vec2(0.9f, 0.95f), ngl::Vec2(0.2f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonPause->updateText("Pause", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-52.f, -25.f));
  m_buttons.push_back(m_buttonPause);
  m_buttonMenu = new UIButton(buttonMenu, "font/arial.ttf", 40, ngl::Vec2(m_width, m_height));
  m_buttonMenu->updateButton(ngl::Vec2(0.9f, 0.83f), ngl::Vec2(0.2f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonMenu->updateText("Menu", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-52.f, -25.f));
  m_buttons.push_back(m_buttonMenu);
  m_buttonCreateSquad = new UIButton(buttonCreateSquad, "font/arial.ttf", 20, ngl::Vec2(m_width, m_height));
  m_buttonCreateSquad->updateButton(ngl::Vec2(0.f, -0.9f), ngl::Vec2(0.3f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonCreateSquad->updateText("Create Squad", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-60.f, -13.f));
  m_buttons.push_back(m_buttonCreateSquad);
  m_buttonSquadPatrol = new UIButton(buttonSquadPatrol, "font/arial.ttf", 20, ngl::Vec2(m_width, m_height));
  m_buttonSquadPatrol->updateButton(ngl::Vec2(0.7f, -0.9f), ngl::Vec2(0.1f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonSquadPatrol->updateText("Patr", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-20.f, -13.f));
  m_buttons.push_back(m_buttonSquadPatrol);
  m_buttonSquadAggressive = new UIButton(buttonSquadAggressive, "font/arial.ttf", 20, ngl::Vec2(m_width, m_height));
  m_buttonSquadAggressive->updateButton(ngl::Vec2(0.5f, -0.9f), ngl::Vec2(0.1f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonSquadAggressive->updateText("Aggr", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-20.f, -13.f));
  m_buttons.push_back(m_buttonSquadAggressive);
  m_buttonSquadDefensive = new UIButton(buttonSquadDefensive, "font/arial.ttf", 20, ngl::Vec2(m_width, m_height));
  m_buttonSquadDefensive->updateButton(ngl::Vec2(0.6f, -0.9f), ngl::Vec2(0.1f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonSquadDefensive->updateText("Def", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-20.f, -13.f));
  m_buttons.push_back(m_buttonSquadDefensive);
  m_buttonSquadWall = new UIButton(buttonSquadWall, "font/arial.ttf", 20, ngl::Vec2(m_width, m_height));
  m_buttonSquadWall->updateButton(ngl::Vec2(0.4f, -0.9f), ngl::Vec2(0.1f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
  m_buttonSquadWall->updateText("Wall", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-20.f, -13.f));
  m_buttons.push_back(m_buttonSquadWall);
  m_buttonRioterDeadBar = new UIButton(buttonRioterDeadBar, "font/arial.ttf", 20, ngl::Vec2(m_width, m_height));
  m_buttonRioterDeadBar->updateButton(ngl::Vec2(-0.95f, 0.f), ngl::Vec2(0.05f, 1.9f), ngl::Vec4(0.7f, 0.2f, 0.2f, 1.f));
  m_buttonRioterDeadBar->updateText("", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(0.f, 0.f));
  m_buttons.push_back(m_buttonRioterDeadBar);
  m_buttonRioterHomeBar = new UIButton(buttonRioterHomeBar, "font/arial.ttf", 20, ngl::Vec2(m_width, m_height));
  m_buttonRioterHomeBar->updateButton(ngl::Vec2(-0.88f, 0.f), ngl::Vec2(0.05f, 1.9f), ngl::Vec4(0.2f, 0.7f, 0.2f, 1.f));
  m_buttonRioterHomeBar->updateText("", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(0.f, 0.f));
  m_buttons.push_back(m_buttonRioterHomeBar);
  m_sliderSquadSize = new UISlider(sliderSquadSize, "font/arial.ttf", 40, ngl::Vec2(m_width, m_height));
  m_sliderSquadSize->updateSlider(ngl::Vec2(-0.5f, -0.9f), ngl::Vec2(0.5f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f), ngl::Vec2(-0.5f, -0.9f), ngl::Vec2(0.02f, 0.1f), ngl::Vec4(1.f, 1.f, 1.f, 1.f), 3, 9);
  m_squadSize = m_sliderSquadSize->calculateOutput();
  m_ss.str(std::string());
  m_ss << m_squadSize;
  m_squadSizeString = m_ss.str();
  m_sliderSquadSize->updateText(m_squadSizeString, ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(177.f, -27.f));
}
void NGLDraw::loadMatricesToShader () [private]
method to load transform data to the shaders
Definition at line 498 of file NGLDraw.cpp.
References m_cam, m_mouseGlobalTX, and m_trans.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  ngl::Mat3 normalMatrix;
  ngl::Mat4 M;
  M=m_trans.getMatrix()*m_mouseGlobalTX;
  MV=  M*m_cam->getViewMatrix();
  MVP= M*m_cam->getVPMatrix();
  normalMatrix=MV;
  normalMatrix.inverse();
  shader->setShaderParamFromMat4("MV",MV);
  shader->setShaderParamFromMat4("MVP",MVP);
  shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
  shader->setShaderParamFromMat4("M",M);
}
void NGLDraw::mouseMoveEvent (const SDL_MouseMotionEvent & _event)
this method is called every time a mouse is moved
Parameters:
_event the SDL mouse event structure containing all mouse info
Definition at line 518 of file NGLDraw.cpp.
References cameraHeight, GameWorld::getCellGraph(), UISlider::getIsSliding(), CellGraph::getMapBounds(), INCREMENT, m_cam, m_gameworld, m_modelPos, m_origXPos, m_origYPos, m_sliderSquadSize, m_squadSize, m_squadSizeString, m_ss, m_translate, UISlider::setTextString(), and UISlider::slideBar().
{
  // right mouse translate code
  if(m_translate && _event.state &SDL_BUTTON_MMASK)
  {
    int diffX = (int)(_event.x - m_origXPos);
    int diffZ = (int)(_event.y - m_origYPos);
    m_origXPos=_event.x;
    m_origYPos=_event.y;
    m_cam->move(INCREMENT * (abs(m_modelPos.m_y-cameraHeight+1)*0.05) * diffX,0,INCREMENT * (abs(m_modelPos.m_y-cameraHeight+1)*0.05) * diffZ);
    float cameraLimitX = (m_gameworld->getCellGraph()->getMapBounds()[1]);
    float cameraLimitZ = (m_gameworld->getCellGraph()->getMapBounds()[3]);
    if(m_cam->getEye().m_x> cameraLimitX)
    {
        m_cam->setEye(ngl::Vec3(cameraLimitX,m_cam->getEye().m_y,m_cam->getEye().m_z));
    }
    if(m_cam->getEye().m_x< -cameraLimitX)
    {
        m_cam->setEye(ngl::Vec3(-cameraLimitX,m_cam->getEye().m_y,m_cam->getEye().m_z));
    }
    if(m_cam->getEye().m_z> cameraLimitZ)
    {
        m_cam->setEye(ngl::Vec3(m_cam->getEye().m_x,m_cam->getEye().m_y,cameraLimitZ));
    }
    if(m_cam->getEye().m_z< -cameraLimitZ)
    {
        m_cam->setEye(ngl::Vec3(m_cam->getEye().m_x,m_cam->getEye().m_y,-cameraLimitZ));
    }
  }
  //Sets the squad size to the amount selected on the slider
  if (m_sliderSquadSize->getIsSliding() == true)
  {
    m_squadSize = m_sliderSquadSize->slideBar(_event.x);
    m_ss.str(std::string());
    m_ss << m_squadSize;
    m_squadSizeString = m_ss.str();
    m_sliderSquadSize->setTextString(m_squadSizeString);
  }
}
void NGLDraw::mousePressEvent (const SDL_MouseButtonEvent & _event)
this method is called every time a mouse button is presses
Parameters:
_event the SDL mouse event structure containing all mouse info
Definition at line 563 of file NGLDraw.cpp.
References buttonCreateSquad, buttonLevel1, buttonLevel2, buttonLevel3, buttonLevel4, buttonLevel5, buttonMenu, buttonPause, buttonPlay, buttonQuit, buttonSquadAggressive, buttonSquadDefensive, buttonSquadPatrol, buttonSquadWall, GameWorld::createSquad(), doSelection(), endGame(), gameMenu, gamePause, gamePlay, gameQuit, UISlider::getIsActive(), Squad::getSquadColour(), UISlider::isClicked(), m_aggressiveColour, m_buttonCreateSquad, m_buttonLevel1, m_buttonLevel2, m_buttonLevel3, m_buttonLevel4, m_buttonLevel5, m_buttonMenu, m_buttonPause, m_buttonPlay, m_buttonQuit, m_buttons, m_defensiveColour, m_gameState, m_gameTimer, m_gameworld, m_origXPos, m_origYPos, m_patrolColour, m_selected, m_selectedLevel, m_selectedSquad, m_selectedSquadID, m_sliderSquadSize, m_squadSize, m_squadSizeString, m_ss, m_translate, m_wallColour, Timer::resetTimer(), UISlider::setIsActive(), UIButton::setIsActive(), UISlider::setIsSliding(), Squad::setSquadColour(), Squad::setSquadDrawColour(), Squad::setSquadSelectedColour(), Squad::setSquadState(), UISlider::setTextString(), UISlider::slideBar(), squadAggressive, squadDefensive, squadPatrol, squadWall, startGame(), UIButton::updateButton(), and UIButton::updateText().
{
  // this method is called when the mouse button is pressed in this case we
  // store the value where the maouse was clicked (x,y) and set the Rotate flag to true
    if(m_gameState != gameMenu && _event.button == SDL_BUTTON_MIDDLE)
    {
      m_origXPos = _event.x;
      m_origYPos = _event.y;
      m_translate=true;
    }
    if(_event.button == SDL_BUTTON_LEFT)
    {
      unsigned int numberOfButtons = m_buttons.size();
      for (unsigned int i = 0; i < numberOfButtons; i++)
      {
        if (m_buttons[i]->isClicked(_event.x, _event.y) && m_buttons[i]->getIsActive() == true)
        {
          switch (m_buttons[i]->getName())
          {
            case buttonPlay:
            {
              startGame(m_selectedLevel);
              m_gameState = gamePlay;
              m_buttonQuit->setIsActive(false);
              m_buttonLevel1->setIsActive(false);
              m_buttonLevel2->setIsActive(false);
              m_buttonLevel3->setIsActive(false);
              m_buttonLevel4->setIsActive(false);
              m_buttonLevel5->setIsActive(false);
              m_buttonPlay->setIsActive(false);
              m_buttonPause->setIsActive(true);
              m_buttonMenu->setIsActive(true);
              m_sliderSquadSize->setIsActive(true);
              m_buttonCreateSquad->setIsActive(true);
              break;
            }
            case buttonLevel1 :
            {
              m_selectedLevel = 1;
              break;
            }
            case buttonLevel2 :
            {
              m_selectedLevel = 2;
              break;
            }
            case buttonLevel3 :
            {
              m_selectedLevel = 3;
              break;
            }
            case buttonLevel4 :
            {
              m_selectedLevel = 4;
              break;
            }
            case buttonLevel5 :
            {
              m_selectedLevel = 5;
              break;
            }
            case buttonQuit :
            {
              m_gameState = gameQuit;
              break;
            }
            case buttonPause :
            {
              if (m_gameState == gamePlay)
              {
                m_gameState = gamePause;
                m_gameTimer.resetTimer();
                m_buttonPause->updateButton(ngl::Vec2(0.9f, 0.95f), ngl::Vec2(0.2f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
                m_buttonPause->updateText("Play", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-32.f, -17.f));
                m_sliderSquadSize->setIsActive(false);
                m_buttonCreateSquad->setIsActive(false);
                break;
              }
              else if (m_gameState == gamePause)
              {
                m_gameState = gamePlay;
                m_gameTimer.resetTimer();
                m_buttonPause->updateButton(ngl::Vec2(0.9f, 0.95f), ngl::Vec2(0.2f, 0.1f), ngl::Vec4(0.2f, 0.2f, 0.9f, 1.f));
                m_buttonPause->updateText("Pause", ngl::Vec3(1.f, 1.f, 1.f), ngl::Vec2(-52.f, -17.f));
                m_sliderSquadSize->setIsActive(true);
                m_buttonCreateSquad->setIsActive(true);
                break;
              }
              break;
            }
            case buttonMenu :
            {
              m_gameState = gameMenu;
              endGame();
              m_buttonQuit->setIsActive(true);
              m_buttonPlay->setIsActive(true);
              m_buttonMenu->setIsActive(false);
              m_buttonPause->setIsActive(false);
              m_sliderSquadSize->setIsActive(false);
              m_buttonCreateSquad->setIsActive(false);
              m_buttonLevel1->setIsActive(true);
              m_buttonLevel2->setIsActive(true);
              m_buttonLevel3->setIsActive(true);
              m_buttonLevel4->setIsActive(true);
              m_buttonLevel5->setIsActive(true);
              break;
            }
            case buttonCreateSquad :
            {
              m_gameworld->createSquad(m_squadSize);
              break;
            }
            case buttonSquadPatrol :
            {
              m_selectedSquad->setSquadState("patrol", squadPatrol);
              m_selectedSquad->setSquadColour(m_patrolColour);
              m_selectedSquad->setSquadSelectedColour(m_patrolColour*2.0);
              break;
            }
            case buttonSquadAggressive :
            {
              m_selectedSquad->setSquadState("aggressive", squadAggressive);
              m_selectedSquad->setSquadColour(m_aggressiveColour);
              m_selectedSquad->setSquadSelectedColour(m_aggressiveColour*2.0);
              break;
            }
            case buttonSquadDefensive :
            {
              m_selectedSquad->setSquadState("defensive", squadDefensive);
              m_selectedSquad->setSquadColour(m_defensiveColour);
              m_selectedSquad->setSquadSelectedColour(m_defensiveColour*2.0);
              break;
            }
            case buttonSquadWall :
            {
              m_selectedSquad->setSquadState("wall", squadWall);
              m_selectedSquad->setSquadColour(m_wallColour);
              m_selectedSquad->setSquadSelectedColour(m_wallColour*2.0);
              break;
            }
            default:
            {
              break;
            }
          }
          return;
        }
      }
      if (m_sliderSquadSize->isClicked(_event.x, _event.y) && m_sliderSquadSize->getIsActive() == true)
      {
        m_sliderSquadSize->setIsSliding(true);
        m_squadSize = m_sliderSquadSize->slideBar(_event.x);
        m_ss.str(std::string());
        m_ss << m_squadSize;
        m_squadSizeString = m_ss.str();
        m_sliderSquadSize->setTextString(m_squadSizeString);
        return;
      }
      if (m_gameState == gamePlay)
      {
         doSelection(_event.x, _event.y);
      }
    }
    if(_event.button == SDL_BUTTON_RIGHT)
    {
        if (m_gameState == gamePlay)
        {
           if (m_selected)
           {
               m_selectedSquad->setSquadDrawColour(m_selectedSquad->getSquadColour());
               m_selected = false;
               m_selectedSquad = NULL;
               m_selectedSquadID = -1;
           }
        }
    }
}
void NGLDraw::mouseReleaseEvent (const SDL_MouseButtonEvent & _event)
this method is called everytime the mouse button is released
Parameters:
_event the SDL mouse event structure containing all mouse info
Definition at line 749 of file NGLDraw.cpp.
References gameMenu, m_gameState, m_rotate, m_sliderSquadSize, m_translate, and UISlider::setIsSliding().
{
  // this event is called when the mouse button is released
  // we then set Rotate to false
  if (_event.button == SDL_BUTTON_LEFT)
  {
    m_sliderSquadSize->setIsSliding(false);
    m_rotate=false;
  }
  // right mouse translate mode
  if (m_gameState != gameMenu && _event.button == SDL_BUTTON_MIDDLE)
  {
    m_translate=false;
  }
}
void NGLDraw::resize (int _w, int _h)
resize our screen and set the camera aspect ratio
Parameters:
[in] _w the new width
[in] _h the new height
Definition at line 153 of file NGLDraw.cpp.
References m_buttons, m_cam, m_height, m_longestSide, m_sliderSquadSize, m_textMedium, m_textSmall, m_width, Text::setScreenSize(), Text::setTransform(), and UISlider::setWindowDimensions().
{
  glViewport(0,0,_w,_h);
  m_height = _h;
  m_width = _w;
  m_longestSide = _h;
  if (_w > _h)
  {
      m_longestSide = _w;
  }
  // now set the camera size values as the screen size has changed
  m_cam->setShape(45,(float)_w/_h,0.05,350);
  //Distort UI buttons
  unsigned int numberOfButtons = m_buttons.size();
  for (unsigned int i = 0; i < numberOfButtons; i++)
  {
    m_buttons[i]->setWindowDimensions(ngl::Vec2(m_width, m_height));
  }
  m_sliderSquadSize->setWindowDimensions(ngl::Vec2(m_width, m_height));
  m_textSmall->setScreenSize(_w, _h);
  m_textMedium->setScreenSize(_w, _h);
  //Distort scrren text
  SDL_Rect s;
  SDL_GetDisplayBounds(0,&s);
  float x,y;
  // now get a scale transform for the text shader
  x=1.0-float(s.w-_w)/s.w;
  y=1.0-float(s.h-_h)/s.h;
  // now set the new transform element for this shader
  m_textSmall->setTransform(x, y);
  m_textMedium->setTransform(x, y);
}
void NGLDraw::setGameState (const eGameState _gameState) [inline]
sets the current game state
Parameters:
[in] _gameState the enum state to set the game to
Definition at line 128 of file NGLDraw.h.
References m_gameState.
{m_gameState = _gameState;}
void NGLDraw::startGame (int _level)
starts a new level by contructing new GameWorld with level specified by buttons
Parameters:
[in] _level the integer ID of the level to load
Definition at line 192 of file NGLDraw.cpp.
References cameraHeight, m_cam, m_gameworld, m_height, m_modelPos, m_mouseGlobalTX, m_selected, m_selectedSquad, m_selectedSquadID, m_spot, and m_width.
{
  //Initialize a gameWorld when the game state is initiated:
    m_gameworld = new GameWorld(_level);
    m_selected = false;
    m_selectedSquad = NULL;
    m_selectedSquadID = -1;  m_spot.setPosition(ngl::Vec3(0,10,10));
    // reset camera
    ngl::Vec3 from(0,cameraHeight,0);
    ngl::Vec3 to(0,0,0);
    ngl::Vec3 up(0,0,-1);
    m_cam = new ngl::Camera(from,to,up);
    m_cam->setShape(45,(float)m_width/m_height,0.05,50);
    m_mouseGlobalTX = ngl::Mat4();
    m_modelPos = ngl::Vec3(0,0,0);
}
void NGLDraw::update (double _timeElapsed, double _currentTime)
update the scene
Parameters:
_timeElapsed the time elapsed between each frame
_currentTime the current time of the current level
Definition at line 492 of file NGLDraw.cpp.
References m_gameworld, and GameWorld::Update().
{
  m_gameworld->Update(_timeElapsed, _currentTime);
}
void NGLDraw::wheelEvent (const SDL_MouseWheelEvent & _event)
this method is called everytime the mouse wheel is moved
Parameters:
_event the SDL mouse event structure containing all mouse info
Definition at line 766 of file NGLDraw.cpp.
References cameraHeight, m_longestSide, m_modelPos, and ZOOM.
{
  // check the diff of the wheel position (0 means no change)
  if(_event.y > 0)
  {
      m_modelPos.m_y+=(ZOOM*(cameraHeight-m_modelPos.m_y)*0.05);
      float nearest = 15.0;
      if(cameraHeight-m_modelPos.m_y < nearest)
      {
        m_modelPos.m_y = cameraHeight - nearest;
      }
  }
  else if(_event.y < 0)
  {
      m_modelPos.m_y-=(ZOOM*(cameraHeight-m_modelPos.m_y)*0.05);
      float furthest = ((49.0*5000.0)/(m_longestSide));
      if(cameraHeight-m_modelPos.m_y > furthest)
      {
        m_modelPos.m_y= cameraHeight - furthest;
      }
  }
}
Member Data Documentation
ngl::Colour NGLDraw::m_aggressiveColour [private]
the colour used to represent a squad in the aggressive state, and the colour of the aggressive button
Definition at line 239 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonCreateSquad [private]
a button that is used in game to create a new squad
Definition at line 303 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonLevel1 [private]
a button that is used to toggle the level to start level 1
Definition at line 267 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonLevel2 [private]
a button that is used to toggle the level to start level 2
Definition at line 271 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonLevel3 [private]
a button that is used to toggle the level to start level 3
Definition at line 275 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonLevel4 [private]
a button that is used to toggle the level to start level 4
Definition at line 279 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonLevel5 [private]
a button that is used to toggle the level to start level 5
Definition at line 283 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonMenu [private]
a button that is used to return to the menu
Definition at line 299 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonPause [private]
a button that is used to pause the game
Definition at line 295 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonPlay [private]
a button that is used to start a new level
Definition at line 263 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonQuit [private]
a button that is used to quit the game
Definition at line 291 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonRioterDeadBar [private]
a button to represent the amount of rioters that have been killed
Definition at line 323 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonRioterHomeBar [private]
a button to respresent the amount of rioters that have gone home and left the map
Definition at line 327 of file NGLDraw.h.
std::vector<UIButton*> NGLDraw::m_buttons [private]
a vector containing all buttons in the UI, allowing for checking against mouse clicks
Definition at line 259 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonSquadAggressive [private]
a button that is used in game to set the squad state to aggressive
Definition at line 311 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonSquadDefensive [private]
a button that is used in game to set the squad state to defensive
Definition at line 315 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonSquadPatrol [private]
a button that is used in game to set the squad state to patrol
Definition at line 307 of file NGLDraw.h.
UIButton* NGLDraw::m_buttonSquadWall [private]
a button that is used in game to set the squad state to wall
Definition at line 319 of file NGLDraw.h.
ngl::Camera* NGLDraw::m_cam [private]
Our Camera.
Definition at line 174 of file NGLDraw.h.
ngl::Camera* NGLDraw::m_camOrth [private]
Definition at line 175 of file NGLDraw.h.
ngl::Vec3 NGLDraw::m_clickPosition [private]
the position of the mouse click in world space
Definition at line 223 of file NGLDraw.h.
ngl::Colour NGLDraw::m_defensiveColour [private]
the colour used to represent a squad in the defensive state, and the colour of the defensive button
Definition at line 235 of file NGLDraw.h.
EntityManager* NGLDraw::m_entityMgr [private]
a pointer to the entity manager, used to access multiple enitites
Definition at line 203 of file NGLDraw.h.
eGameState NGLDraw::m_gameState [private]
the current state of the game
Definition at line 199 of file NGLDraw.h.
Timer NGLDraw::m_gameTimer [private]
the timer that contains the current time and time elapsed between each tick
Definition at line 207 of file NGLDraw.h.
GameWorld* NGLDraw::m_gameworld [private]
the game world for all entities to be created in
Definition at line 195 of file NGLDraw.h.
float NGLDraw::m_height [private]
the height of the window
Definition at line 351 of file NGLDraw.h.
ngl::Light* NGLDraw::m_light [private]
a simple light use to illuminate the screen
Definition at line 183 of file NGLDraw.h.
float NGLDraw::m_longestSide [private]
the longest side of the screen, used for zooming correctly
Definition at line 355 of file NGLDraw.h.
ngl::Vec3 NGLDraw::m_modelPos [private]
the model position for mouse movement
Definition at line 179 of file NGLDraw.h.
ngl::Mat4 NGLDraw::m_mouseGlobalTX [private]
used to store the global mouse transforms
Definition at line 170 of file NGLDraw.h.
int NGLDraw::m_origX [private]
the previous x mouse value
Definition at line 154 of file NGLDraw.h.
int NGLDraw::m_origXPos [private]
the previous x mouse value for Position changes
Definition at line 162 of file NGLDraw.h.
int NGLDraw::m_origY [private]
the previous y mouse value
Definition at line 158 of file NGLDraw.h.
int NGLDraw::m_origYPos [private]
the previous y mouse value for Position changes
Definition at line 166 of file NGLDraw.h.
ngl::Colour NGLDraw::m_patrolColour [private]
the colour used to represent a squad in the patrol state, and the colour of the patrol button
Definition at line 231 of file NGLDraw.h.
bool NGLDraw::m_rotate [private]
flag to indicate if the mouse button is pressed when dragging
Definition at line 146 of file NGLDraw.h.
bool NGLDraw::m_selected [private]
booleon to determin if a squad has been selected or not
Definition at line 211 of file NGLDraw.h.
int NGLDraw::m_selectedLevel [private]
an integer holding the currently selected level to start
Definition at line 287 of file NGLDraw.h.
Squad* NGLDraw::m_selectedSquad [private]
a pointer to the currently selected squad
Definition at line 215 of file NGLDraw.h.
int NGLDraw::m_selectedSquadID [private]
the ID of the currently selected squad
Definition at line 219 of file NGLDraw.h.
UISlider* NGLDraw::m_sliderSquadSize [private]
a slider used to control the number of policemen to assign to the next spawned squad
Definition at line 331 of file NGLDraw.h.
int NGLDraw::m_spinXFace [private]
used to store the x rotation mouse value
Definition at line 138 of file NGLDraw.h.
int NGLDraw::m_spinYFace [private]
used to store the y rotation mouse value
Definition at line 142 of file NGLDraw.h.
ngl::SpotLight NGLDraw::m_spot [private]
a simple spot light used to create the the effect of a light from a helicopter
Definition at line 187 of file NGLDraw.h.
ngl::Colour NGLDraw::m_squadCurrentColour [private]
the current squad's current colour
Definition at line 227 of file NGLDraw.h.
int NGLDraw::m_squadSize [private]
the size of the squad to be spawned when the create squad button is clicked
Definition at line 335 of file NGLDraw.h.
std::string NGLDraw::m_squadSizeString [private]
a conversion of the size of squad to be spawn to a string used for displaying in the UI
Definition at line 339 of file NGLDraw.h.
std::stringstream NGLDraw::m_ss [private]
a string stream used for conversion throughout NGLDraw
Definition at line 343 of file NGLDraw.h.
Text* NGLDraw::m_textLarge [private]
a pointer to the text class used to display all large text in the UI
Definition at line 255 of file NGLDraw.h.
Text* NGLDraw::m_textMedium [private]
a pointer to the text class used to display all medium text in the UI
Definition at line 251 of file NGLDraw.h.
Text* NGLDraw::m_textSmall [private]
a pointer to the text class used to display all small text in the UI
Definition at line 247 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_trans [private]
a NGL transformation tool
Definition at line 191 of file NGLDraw.h.
bool NGLDraw::m_translate [private]
flag to indicate if the Right mouse button is pressed when dragging
Definition at line 150 of file NGLDraw.h.
ngl::Colour NGLDraw::m_wallColour [private]
the colour used to represend a squad in the wall state, and the colour of the wall button
Definition at line 243 of file NGLDraw.h.
float NGLDraw::m_width [private]
the width of the window
Definition at line 347 of file NGLDraw.h.
The documentation for this class was generated from the following files:
NGLDraw.h
NGLDraw.cpp