YOURPROJECTNAMEGOESHERE: UISlider Class Reference
UISlider Class Reference
A simple slider class that uses SDL TTF text and NGL triangle planes.
#include <UISlider.h>
Public Member Functions
UISlider (eSliderName _name, ngl::Vec2 _windowDimensions)
ctor to create a simple slider that does not have any text functionality
UISlider (eSliderName _name, std::string _font, int _fontSize, ngl::Vec2 _windowDimensions)
ctor to create a simple slider that has additional text functionality
~UISlider ()
dtor cleans up any text pointeres if necessary
void updateSlider (ngl::Vec2 _pos, ngl::Vec2 _dimensions, ngl::Vec4 _colour, ngl::Vec2 _barPos, ngl::Vec2 _barDimensions, ngl::Vec4 _barColour, int _outputMin, int _outputMax)
method used to updated the button position, dimensions and colour
void updateText (std::string _text, ngl::Vec3 _colour, ngl::Vec2 _offset)
method used to update the text string, colour and offset from the button centre
void addText (std::string _font, int _fontSize)
if the button does not have text it adds text drawing functionality
bool isClicked (int _x, int _y)
a method to detect if a button has been clicked, based on it's NDC screen position and dimensions
int slideBar (int _x)
method called while the slider is being clicked to update the position of the slider bar
int calculateOutput ()
method used to calculate the output of the slider, based on the ouput min, max and slider bar position
eSliderName getName ()
gets the enum name of the button
void setName (eSliderName _name)
sets the enum name of the button
bool getIsActive ()
gets if the button is active or not
void setIsActive (const bool _inBool)
sets if the button is active or inactive
bool getIsSliding ()
gets if the slider is sliding or not
void setIsSliding (const bool _inBool)
sets if the slider is sliding or not
ngl::Vec2 getWindowDimensions ()
gets the window dimensions that are used by the button for scaling
void setWindowDimensions (const ngl::Vec2 _windowDimensions)
sets the window dimensions to be used by the button for scaling
ngl::Vec2 getSliderPosition ()
gets the slider position in NDC
void setSliderPosition (const ngl::Vec2 _pos)
sets the slider position in NDC
ngl::Vec2 getSliderDimension ()
gets the slider dimensions in NDC
void setSliderDimension (const ngl::Vec2 _dimensions)
sets the slider dimensions in NDC
ngl::Vec4 getSliderColour ()
gets the colour of the slider
void setSliderColour (const ngl::Vec4 _colour)
sets the colour of the slider
ngl::Vec2 getSliderBarPosition ()
gets the slider bar position in NDC
void setSliderBarPosition (const ngl::Vec2 _pos)
sets the slider bar position in NDC
ngl::Vec2 getSliderBarDimension ()
gets the slider bar dimensions in NDC
void setSliderBarDimension (const ngl::Vec2 _dimensions)
sets the slider bar dimensions in NDC
ngl::Vec4 getSliderBarColour ()
gets the colour of the slider bar
void setSliderBarColour (const ngl::Vec4 _colour)
sets the colour of the slider bar
bool getHasText ()
gets if the button has valid text
void setHasText (const bool _inBool)
sets if the button has text or does not have text
std::string getTextString ()
gets the text string that is being displayed
void setTextString (const std::string _text)
sets the text string of the button
ngl::Vec2 getTextPos ()
gets the position of the text in NDC
ngl::Vec2 getTextOffset ()
gets the amout of pixel offset applied to the text
void setTextOffset (const ngl::Vec2 _offset)
sets the pixel offset of the text from the centre of the button
void setTextColour (const ngl::Vec3 _colour)
sets the colour of the text
void draw ()
draws the button, and any text if necessary
void loadMatricesToShader (ngl::Vec2 _pos, ngl::Vec4 _colour)
method to load transform data to the shaders
Private Attributes
eSliderName m_name
the enum name used by the button
bool m_isActive
boolean to determin if the button is active
bool m_isSliding
boolean to determin if the button is sliding
ngl::Vec2 m_windowDimensions
the x and y values of the window dimensions
ngl::Vec2 m_sliderPos
the x and y position of the slider in NDC
ngl::Vec2 m_sliderDimensions
the x and y dimensions of the slider in NDC
ngl::Vec4 m_sliderColour
the r, g, b, a values of the slider colour
ngl::Vec2 m_sliderBarPos
the x and y position of the slider bar in NDC
ngl::Vec2 m_sliderBarDimensions
the x and y dimensions of the slider bar in NDC
ngl::Vec4 m_sliderBarColour
the r, g, b, a values of the slider bar colour
int m_output
the output integer value produced by the slider
int m_outputMin
the inclusive minimum integer output that can be produced by the button
int m_outputMax
the inclusive maximum integer output that can be produced by the slider
Text * m_text
pointer to a text object
bool m_hasText
boolean to determin if the button has text
std::string m_textString
the text string that is displayed on screen
ngl::Vec2 m_textPos
the position of the text in NDC
ngl::Vec2 m_textOffset
the pixel offset of the text from the centre of the button
Detailed Description
A simple slider class that uses SDL TTF text and NGL triangle planes.
Author:
Will Herbert
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 24 of file UISlider.h.
Constructor & Destructor Documentation
UISlider::UISlider (eSliderName _name, ngl::Vec2 _windowDimensions)
ctor to create a simple slider that does not have any text functionality
Parameters:
[in] _name enum name to set as the name of the slider
[in] _windowDimensions width and height of the initial window, used for correct UI scaling
Definition at line 11 of file UISlider.cpp.
References m_hasText, m_isActive, m_isSliding, m_name, and m_windowDimensions.
{
  m_name = _name;
  m_windowDimensions = _windowDimensions;
  m_hasText = false;
  m_isActive = true;
  m_isSliding = false;
}
UISlider::UISlider (eSliderName _name, std::string _font, int _fontSize, ngl::Vec2 _windowDimensions)
ctor to create a simple slider that has additional text functionality
Parameters:
[in] _name enum name to set as the name of the slider
[in] _font the font of the text, cannot be changed after construction
[in] _fontSize the size of the text, cannot be changed after contruction
[in] _windowDimensions width and height of the initial window, used for correct UI scaling
Definition at line 21 of file UISlider.cpp.
References m_hasText, m_isActive, m_isSliding, m_name, m_text, and m_windowDimensions.
{
  m_name = _name;
  m_text = new Text(_font, _fontSize);
  m_windowDimensions = _windowDimensions;
  m_hasText = true;
  m_isActive = true;
  m_isSliding = false;
}
UISlider::~UISlider ()
dtor cleans up any text pointeres if necessary
Definition at line 32 of file UISlider.cpp.
References m_hasText, and m_text.
{
  if (m_hasText)
  {
    delete m_text;
  }
}
Member Function Documentation
void UISlider::addText (std::string _font, int _fontSize)
if the button does not have text it adds text drawing functionality
Parameters:
[in] _font the font of the text, cannot be changed after addition
[in] _fontSize the size of the text, cannot be changed after addition
Definition at line 41 of file UISlider.cpp.
References m_hasText, and m_text.
{
  if (m_hasText == false)
  {
    m_text = new Text(_font, _fontSize);
    m_hasText = true;
  }
  else
  {
    std::cout<<"Error: This slider already has text."<<std::endl;
  }
}
int UISlider::calculateOutput ()
method used to calculate the output of the slider, based on the ouput min, max and slider bar position
Definition at line 117 of file UISlider.cpp.
References m_output, m_outputMax, m_outputMin, m_sliderBarPos, m_sliderDimensions, and m_sliderPos.
{
  double sliderParam = (m_sliderBarPos.m_x - (m_sliderPos.m_x - m_sliderDimensions.m_x/2)) / ((m_sliderPos.m_x + m_sliderDimensions.m_x/2) - (m_sliderPos.m_x - m_sliderDimensions.m_x/2));
  double outputDivisions = 1.0 / ((m_outputMax - m_outputMin) + 1);
  int outputSection = (sliderParam / outputDivisions);
  m_output = m_outputMin + outputSection;
  return m_output;
}
void UISlider::draw ()
draws the button, and any text if necessary
Definition at line 192 of file UISlider.cpp.
References loadMatricesToShader(), m_hasText, m_sliderBarColour, m_sliderBarDimensions, m_sliderBarPos, m_sliderColour, m_sliderDimensions, m_sliderPos, m_text, m_textOffset, m_textPos, m_textString, and Text::renderText().
{
  loadMatricesToShader(m_sliderBarPos, m_sliderBarColour);
  ngl::VAOPrimitives::instance()->createTrianglePlane("sliderBar", m_sliderBarDimensions.m_x, m_sliderBarDimensions.m_y, 1, 1, ngl::Vec3(0, 1, 0));
  ngl::VAOPrimitives::instance()->draw("sliderBar");
  loadMatricesToShader(m_sliderPos, m_sliderColour);
  ngl::VAOPrimitives::instance()->createTrianglePlane("slider", m_sliderDimensions.m_x, m_sliderDimensions.m_y, 1, 1, ngl::Vec3(0, 1, 0));
  ngl::VAOPrimitives::instance()->draw("slider");
  if (m_hasText == true)
  {
    m_text->renderText(m_textPos.m_x + m_textOffset.m_x, m_textPos.m_y + m_textOffset.m_y, m_textString);
  }
}
bool UISlider::getHasText ()
gets if the button has valid text
Returns:
bool returns true if the button has text, false if it does not have text
bool UISlider::getIsActive () [inline]
gets if the button is active or not
Returns:
bool true if the button is active, false if it is inactive
Definition at line 101 of file UISlider.h.
References m_isActive.
{ return m_isActive; }
bool UISlider::getIsSliding () [inline]
gets if the slider is sliding or not
Returns:
bool true if the slider is sliding, false if it is not sliding
Definition at line 111 of file UISlider.h.
References m_isSliding.
{ return m_isSliding; }
eSliderName UISlider::getName () [inline]
gets the enum name of the button
Returns:
enum eSliderName the enum value of the name
Definition at line 91 of file UISlider.h.
References m_name.
{ return m_name; }
ngl::Vec4 UISlider::getSliderBarColour () [inline]
gets the colour of the slider bar
Returns:
ngl::Vec4 the r, g, b, a values of the slider bar colour
Definition at line 181 of file UISlider.h.
References m_sliderBarColour.
{ return m_sliderBarColour; }
ngl::Vec2 UISlider::getSliderBarDimension () [inline]
gets the slider bar dimensions in NDC
Returns:
ngl::Vec2 the x and y dimensions of the slider bar in NDC
Definition at line 171 of file UISlider.h.
References m_sliderBarDimensions.
{ return m_sliderBarDimensions; }
ngl::Vec2 UISlider::getSliderBarPosition () [inline]
gets the slider bar position in NDC
Returns:
ngl::Vec2 the x and y position of the slider bar in NDC
Definition at line 161 of file UISlider.h.
References m_sliderBarPos.
{ return m_sliderBarPos; }
ngl::Vec4 UISlider::getSliderColour () [inline]
gets the colour of the slider
Returns:
ngl::Vec4 the r, g, b, a values of the slider colour
Definition at line 151 of file UISlider.h.
References m_sliderColour.
{ return m_sliderColour; }
ngl::Vec2 UISlider::getSliderDimension () [inline]
gets the slider dimensions in NDC
Returns:
ngl::Vec2 the x and y dimensions of the slider in NDC
Definition at line 141 of file UISlider.h.
References m_sliderDimensions.
{ return m_sliderDimensions; }
ngl::Vec2 UISlider::getSliderPosition () [inline]
gets the slider position in NDC
Returns:
ngl::Vec2 the x and y position of the slider in NDC
Definition at line 131 of file UISlider.h.
References m_sliderPos.
{ return m_sliderPos; }
ngl::Vec2 UISlider::getTextOffset ()
gets the amout of pixel offset applied to the text
Returns:
the x and y pixel offset applied to the text
Definition at line 153 of file UISlider.cpp.
References m_hasText, and m_textOffset.
{
  if (m_hasText)
  {
    return m_textOffset;
  }
  else
  {
    std::cout<<"The slider does not have text"<<std::endl;
  }
}
ngl::Vec2 UISlider::getTextPos ()
gets the position of the text in NDC
Returns:
the x and y position of the text in NDC
std::string UISlider::getTextString ()
gets the text string that is being displayed
Returns:
std::string returns the text string that is being displayed
Definition at line 127 of file UISlider.cpp.
References m_hasText, and m_textString.
{
  if (m_hasText)
  {
    return m_textString;
  }
  else
  {
    std::cout<<"The slider does not have text"<<std::endl;
  }
}
ngl::Vec2 UISlider::getWindowDimensions () [inline]
gets the window dimensions that are used by the button for scaling
Returns:
ngl::Vec2 the width and height of the window dimensions
Definition at line 121 of file UISlider.h.
References m_windowDimensions.
{ return m_windowDimensions; }
bool UISlider::isClicked (int _x, int _y)
a method to detect if a button has been clicked, based on it's NDC screen position and dimensions
Parameters:
[in] _x the input x pixel position of the mouse click
[in] _y the input y pixel position of the mouse click
Definition at line 89 of file UISlider.cpp.
References m_sliderDimensions, m_sliderPos, and m_windowDimensions.
{
  ngl::Vec2 ndc;
  ndc.m_x = ((2.f * _x) / m_windowDimensions.m_x) - 1.f;
  ndc.m_y = 1.f - ((2.f * _y) / m_windowDimensions.m_y);
  if (ndc.m_x >= (m_sliderPos.m_x - m_sliderDimensions.m_x/2) && ndc.m_x <= (m_sliderPos.m_x + m_sliderDimensions.m_x/2) &&
      ndc.m_y >= (m_sliderPos.m_y - m_sliderDimensions.m_y/2) && ndc.m_y <= (m_sliderPos.m_y + m_sliderDimensions.m_y/2))
  {
    return true;
  }
  else
  {
    return false;
  }
}
void UISlider::loadMatricesToShader (ngl::Vec2 _pos, ngl::Vec4 _colour)
method to load transform data to the shaders
Parameters:
[in] _pos the position of the slider or bar to be rendered
[in] _colour the colour of the slider or bar to be rendered
Definition at line 208 of file UISlider.cpp.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  (*shader)["nglColourShader"]->use();
  shader->setShaderParam4f("Colour", _colour.m_x, _colour.m_y,_colour.m_z, 1.f);
  ngl::Transformation t;
  t.setPosition(ngl::Vec3(_pos.m_x, _pos.m_y, 0.f));
  t.setRotation(90.f, 0.f, 0.f);
  ngl::Mat4 M;
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  M=t.getMatrix();
  MV=  M*ngl::lookAt(ngl::Vec3(0, 0, 10), ngl::Vec3(0, 0, 0), ngl::Vec3(0, 1, 0));
  MVP= MV*ngl::ortho(-1, 1, -1, 1, 0.1f, 100.f);
  shader->setShaderParamFromMat4("MVP",MVP);
}
void UISlider::setHasText (const bool _inBool) [inline]
sets if the button has text or does not have text
Parameters:
[in] _inBool the boolean to set if the button has text or does not have text
Definition at line 196 of file UISlider.h.
References m_hasText.
{ m_hasText = _inBool; }
void UISlider::setIsActive (const bool _inBool) [inline]
sets if the button is active or inactive
Parameters:
[in] _inBool the boolean to set if the button is active or inactive
Definition at line 106 of file UISlider.h.
References m_isActive.
{ m_isActive = _inBool; }
void UISlider::setIsSliding (const bool _inBool) [inline]
sets if the slider is sliding or not
Parameters:
[in] _inBool the boolean to set if the slider is sliding or not sliding
Definition at line 116 of file UISlider.h.
References m_isSliding.
{ m_isSliding = _inBool; }
void UISlider::setName (eSliderName _name) [inline]
sets the enum name of the button
Parameters:
[in] _name the input enum name to give to the button
Definition at line 96 of file UISlider.h.
References m_name.
{ m_name = _name; }
void UISlider::setSliderBarColour (const ngl::Vec4 _colour) [inline]
sets the colour of the slider bar
Parameters:
[in] _colour the r, g, b, a to assign to the slider bar colour
Definition at line 186 of file UISlider.h.
References m_sliderBarColour.
{ m_sliderBarColour = _colour; }
void UISlider::setSliderBarDimension (const ngl::Vec2 _dimensions) [inline]
sets the slider bar dimensions in NDC
Parameters:
[in] _dimensions the x and y dimensions in NDC to set the slider bar to
Definition at line 176 of file UISlider.h.
References m_sliderBarDimensions.
{ m_sliderBarDimensions = _dimensions; }
void UISlider::setSliderBarPosition (const ngl::Vec2 _pos) [inline]
sets the slider bar position in NDC
Parameters:
[in] _pos the x and y position in NDC to set the slider bar to
Definition at line 166 of file UISlider.h.
References m_sliderBarPos.
{ m_sliderBarPos = _pos; }
void UISlider::setSliderColour (const ngl::Vec4 _colour) [inline]
sets the colour of the slider
Parameters:
[in] _colour the r, g, b, a to assign to the slider colour
Definition at line 156 of file UISlider.h.
References m_sliderColour.
{ m_sliderColour = _colour; }
void UISlider::setSliderDimension (const ngl::Vec2 _dimensions) [inline]
sets the slider dimensions in NDC
Parameters:
[in] _dimensions the x and y dimensions in NDC to set the slider to
Definition at line 146 of file UISlider.h.
References m_sliderDimensions.
{ m_sliderDimensions = _dimensions; }
void UISlider::setSliderPosition (const ngl::Vec2 _pos) [inline]
sets the slider position in NDC
Parameters:
[in] _pos the x and y position in NDC to set the slider to
Definition at line 136 of file UISlider.h.
References m_sliderPos.
{ m_sliderPos = _pos; }
void UISlider::setTextColour (const ngl::Vec3 _colour)
sets the colour of the text
Parameters:
[in] _colour the r, g, b values to be assigned to the text colour
Definition at line 179 of file UISlider.cpp.
References m_hasText, m_text, and Text::setColour().
{
  if (m_hasText)
  {
    m_text->setColour(_colour.m_x, _colour.m_y, _colour.m_z);
  }
  else
  {
    std::cout<<"The slider does not have text"<<std::endl;
  }
}
void UISlider::setTextOffset (const ngl::Vec2 _offset)
sets the pixel offset of the text from the centre of the button
Parameters:
[in] _offset the x and y pixel offset to be applied to the button
Definition at line 166 of file UISlider.cpp.
References m_hasText, and m_textOffset.
{
  if (m_hasText)
  {
    m_textOffset = _offset;
  }
  else
  {
    std::cout<<"The slider does not have text"<<std::endl;
  }
}
void UISlider::setTextString (const std::string _text)
sets the text string of the button
Parameters:
[in] _text the text string input to display
Definition at line 140 of file UISlider.cpp.
References m_hasText, and m_textString.
{
  if (m_hasText)
  {
    m_textString = _text;
  }
  else
  {
    std::cout<<"The slider does not have text"<<std::endl;
  }
}
void UISlider::setWindowDimensions (const ngl::Vec2 _windowDimensions) [inline]
sets the window dimensions to be used by the button for scaling
Parameters:
[in] _windowDimensions the width and height to be used by the button for scaling
Definition at line 126 of file UISlider.h.
References m_windowDimensions.
{ m_windowDimensions = _windowDimensions; }
int UISlider::slideBar (int _x)
method called while the slider is being clicked to update the position of the slider bar
Parameters:
[in] _x the input x pixel position of the mouse
Definition at line 106 of file UISlider.cpp.
References calculateOutput(), m_sliderBarPos, m_sliderDimensions, m_sliderPos, and m_windowDimensions.
{
  double ndc_x = ((2.f * _x) / m_windowDimensions.m_x) - 1.f;
  if (ndc_x > (m_sliderPos.m_x - m_sliderDimensions.m_x/2) && ndc_x < (m_sliderPos.m_x + m_sliderDimensions.m_x/2))
  {
    m_sliderBarPos.m_x = ndc_x;
  }
  return calculateOutput();
}
void UISlider::updateSlider (ngl::Vec2 _pos, ngl::Vec2 _dimensions, ngl::Vec4 _colour, ngl::Vec2 _barPos, ngl::Vec2 _barDimensions, ngl::Vec4 _barColour, int _outputMin, int _outputMax)
method used to updated the button position, dimensions and colour
Parameters:
[in] _pos input NDC position to set as new button position
[in] _dimensions input NDC dimensions to set as new button dimensions
[in] _colour input colour to set as the new button colour
[in] _barPos input NDC position to set as new slider bar position
[in] _barDimensions input NDC dimensions to set as new slider bar dimensions
[in] _barColour input colour to set as the new slider bar colour
[in] _outputMin the minimum integer value that the slider can output
[in] _outputMax the maximum integer value taht the slider can ouput
Definition at line 55 of file UISlider.cpp.
References calculateOutput(), m_outputMax, m_outputMin, m_sliderBarColour, m_sliderBarDimensions, m_sliderBarPos, m_sliderColour, m_sliderDimensions, and m_sliderPos.
{
  m_sliderPos = _pos;
  m_sliderDimensions = _dimensions;
  m_sliderColour = _colour;
  m_sliderBarPos = _barPos;
  m_sliderBarDimensions = _barDimensions;
  m_sliderBarColour = _barColour;
  m_outputMin = _outputMin;
  m_outputMax = _outputMax;
  calculateOutput();
}
void UISlider::updateText (std::string _text, ngl::Vec3 _colour, ngl::Vec2 _offset)
method used to update the text string, colour and offset from the button centre
Parameters:
[in] _text input std::string to set as the new text string to display
[in] _colour input colour to set as the new text colour
[in] _offset input pixel offset to set as the new text offset from the button centre
Definition at line 71 of file UISlider.cpp.
References m_hasText, m_sliderPos, m_text, m_textOffset, m_textPos, m_textString, m_windowDimensions, and Text::setColour().
{
  if (m_hasText == true)
  {
    m_textString = _text;
    m_text->setColour(_colour.m_x, _colour.m_y, _colour.m_z);
    m_textOffset = _offset;
    m_textPos.m_x = ((m_sliderPos.m_x + 1) * m_windowDimensions.m_x) / 2;
    m_textPos.m_y = ((1 - m_sliderPos.m_y) * m_windowDimensions.m_y) / 2;
  }
  else
  {
    std::cout<<"Error: Text has not been initialised for this slider."<<std::endl;
  }
}
Member Data Documentation
bool UISlider::m_hasText [private]
boolean to determin if the button has text
Definition at line 298 of file UISlider.h.
bool UISlider::m_isActive [private]
boolean to determin if the button is active
Definition at line 246 of file UISlider.h.
bool UISlider::m_isSliding [private]
boolean to determin if the button is sliding
Definition at line 250 of file UISlider.h.
eSliderName UISlider::m_name [private]
the enum name used by the button
Definition at line 242 of file UISlider.h.
int UISlider::m_output [private]
the output integer value produced by the slider
Definition at line 282 of file UISlider.h.
int UISlider::m_outputMax [private]
the inclusive maximum integer output that can be produced by the slider
Definition at line 290 of file UISlider.h.
int UISlider::m_outputMin [private]
the inclusive minimum integer output that can be produced by the button
Definition at line 286 of file UISlider.h.
ngl::Vec4 UISlider::m_sliderBarColour [private]
the r, g, b, a values of the slider bar colour
Definition at line 278 of file UISlider.h.
ngl::Vec2 UISlider::m_sliderBarDimensions [private]
the x and y dimensions of the slider bar in NDC
Definition at line 274 of file UISlider.h.
ngl::Vec2 UISlider::m_sliderBarPos [private]
the x and y position of the slider bar in NDC
Definition at line 270 of file UISlider.h.
ngl::Vec4 UISlider::m_sliderColour [private]
the r, g, b, a values of the slider colour
Definition at line 266 of file UISlider.h.
ngl::Vec2 UISlider::m_sliderDimensions [private]
the x and y dimensions of the slider in NDC
Definition at line 262 of file UISlider.h.
ngl::Vec2 UISlider::m_sliderPos [private]
the x and y position of the slider in NDC
Definition at line 258 of file UISlider.h.
Text* UISlider::m_text [private]
pointer to a text object
Definition at line 294 of file UISlider.h.
ngl::Vec2 UISlider::m_textOffset [private]
the pixel offset of the text from the centre of the button
Definition at line 310 of file UISlider.h.
ngl::Vec2 UISlider::m_textPos [private]
the position of the text in NDC
Definition at line 306 of file UISlider.h.
std::string UISlider::m_textString [private]
the text string that is displayed on screen
Definition at line 302 of file UISlider.h.
ngl::Vec2 UISlider::m_windowDimensions [private]
the x and y values of the window dimensions
Definition at line 254 of file UISlider.h.
The documentation for this class was generated from the following files:
UISlider.h
UISlider.cpp