YOURPROJECTNAMEGOESHERE: GameWorld Class Reference
GameWorld Class Reference
The class that creates the world an encompasses all base game entities.
#include <GameWorld.h>
Public Member Functions
GameWorld (int _level)
ctor this will create a new world to spawn entities inside
~GameWorld ()
dtor cleans up all entities in the world and closes the Lua state associated with the level
void registerLua (lua_State *_L)
registers all the necessary functions and members with Lua so that they can be edited in our script file
void Update (double _timeElapsed, double _currentTime)
updates all of the entities in the world, the cells in the cell graph and checks for change in state
void draw (ngl::Camera *_cam, ngl::Mat4 _mouseGlobalTX)
method to draw the game world and contained entities
void loadMatricesToShader (ngl::Camera *_cam, ngl::Mat4 _mouseGlobalTX)
method to load the matrices of the game world to the shader
bool getHasWon () const
gets if the player has achieved the win conditions
void setHasWon (const bool _inBool)
sets that the player has achieved the win state or not
bool getHasLost () const
gets if the player has achieved the lose conditions
void setHasLost (const bool _inBool)
sets that the play has achieved the lose state or not
bool getResetID () const
gets if the reset ID is true or false
void setResetID (const bool _resetID)
sets if the reset ID is true or false
std::vector< Rioter * > getRioters () const
gets the vector of all rioters in the current game world
int getNumberOfRioters () const
gest the number of rioters in the game world
int getInitialNumberOfRioters () const
gets the initial number of rioters that were spawned in the level
void setInitialNumberOfRioters (const int _number)
sets the initial number of rioters that were spawned in the level
int getNumberOfRiotersDead () const
gets the number of rioters who have died during this level
void setNumberOfRiotersDead (const int _number)
sets the number of rioters who have died during this level
int getNumberOfRiotersHome () const
gets the number of rioters who have gone home during this level
void setNumberOfRiotersHome (const int _number)
sets the number of rioters that have gone home during this level
int getNumberOfRiotersDeadToLose () const
gets the number of rioters needed for the lose state to be achieved
void setNumberOfRiotersDeadToLose (const int _number)
sets the number of rioters needed for the lose state to be achieved
int getNumberOfRiotersHomeToWin () const
gets the number of rioters needed for the win state to be achieved
void setNumberOfRiotersHomeToWin (const int _number)
sets the number of rioters needed for the win state to be achieved
void createSquad (int _size)
creates a squad of a specific size
std::vector< Squad * > getSquads ()
gets the vector of all squads in the current level
void squadTarget (Squad *_selectedSquad, ngl::Vec3 _target)
sets the target position for the currently selected squad
int getAvailablePolice () const
gets the number of available police during the current level
void setAvailablePolice (const int _availablePolice)
sets the number of available police during the current level
CellGraph * getCellGraph () const
the cell graph generated for the current level
const char * getCellGraphFile () const
gets the file used for generating the cell graph
void setCellGraphFile (const char *_file)
sets the file to be used for generating the cell graph
std::string getStreetMeshFile () const
gets the file used for the street mesh
void setStreetMeshFile (const std::string _file)
sets the file to be used for the street mesh
std::string getBuildingMeshFile () const
gets the file used for the building mesh
void setBuildingMeshFile (const std::string _file)
sets the file to be used for the building mesh
void addProtestPosition (float _x, float _y, float _z)
method exposed to Lua to add a protest position for rioters to gather around
std::vector< ngl::Vec3 > getProtestPositions () const
gets the vector that stores all the protests positions that have been added
ngl::Vec3 getPoliceStation () const
gets the world position of the police station
void setPoliceStation (const float _x, const float _y, const float _z)
method exposed to Lua that sets the world position of the police state
int getNumberOfTrees () const
gets the number of trees spawned in the level
void setNumberOfTrees (const int _number)
sets the number of trees spawned in the level
int getNumberOfStreetLights () const
gets the number of street lights spawned in the level
void setNumberOfStreetLights (const int _number)
sets the number of street lights spawned in the level
Private Attributes
EntityManager * m_entityMgr
a pointer to the entity manager monostate
lua_State * L
the Lua state that is registers with the game world
bool m_resetID
a boolean that is set to true when the game is reset
bool m_win
a boolean to determin if the win state has been achieved
bool m_lose
a boolean to determin if the lose state has been achieved
std::vector< int > m_dynamicEntities
a vector containing all of the dynamic entites found within the world
ngl::Obj * m_rioterMesh
a pointer to the mesh that will be used by all rioters in the world
std::vector< Rioter * > m_rioters
a vector containing all of the rioters found within the world
int m_initialNumberOfRioters
the value of the initial number of rioters spawned at the start of the level
int m_numberOfRioters
the value of the number of rioters currently in the level
std::vector< Rioter * > m_deadRioters
a vector containing all the dead rioters to be used later or discarded
int m_numberOfRiotersDead
the number of dead rioters in the world
int m_numberOfRiotersHome
the number of rioters who have gone home during the game
int m_numberOfRiotersDeadToLose
the number of rioters who have to die for the player to lose
int m_numberOfRiotersHomeToWin
the number of rioters who have to go home for the player to win
std::vector< Squad * > m_squads
a vector containing all of the squads currently in the level
int m_numberOfSquads
the number of squads currently in the level
std::vector< Squad * > m_deadSquads
the number of dead squads in currently in the level
ngl::Obj * m_policeMesh
a pointer to the mesh that will be used by all police in the world
int m_availablePolice
the number of available police in the level
int m_activePolice
the number of active police in the level
ngl::Obj * m_treeMesh
a pointer to the mesh that will be used by all trees in the world
ngl::Obj * m_streetLightMesh
a pointer to the mesh that will be used by all street lights in the world
std::vector< StaticEntity * > m_obstacles
a vector containing all of the obstacles currently in the level
int m_numberOfObstacles
the number of obstacles currently in the level
int m_numberOfTrees
the number of trees currently in the level
int m_numberOfStreetLights
the number of street lights currently in the level
CellGraph * m_cellGraph
a pointer to the cell graph used by the world to generate the cell space partitioning
const char * m_cellGraphFile
the char* location and name of the file to be used by the cell graph
ngl::Obj * m_streetMesh
a pointer to the mesh to be used by the street in the level
std::string m_streetMeshFile
the string location and name of the street mesh
ngl::Obj * m_buildingMesh
a pointer to the mesh to be used by the building in the level
std::string m_buildingMeshFile
the string location and name of the building mesh
ngl::Vec3 m_policeStation
the location of the police station where new squads are spawned
std::vector< ngl::Vec3 > m_protestPositions
a vector containing all of the position where rioters gather when protesting
Detailed Description
The class that creates the world an encompasses all base game entities.
Author:
Will Herbert
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 29 of file GameWorld.h.
Constructor & Destructor Documentation
GameWorld::GameWorld (int _level)
ctor this will create a new world to spawn entities inside
Parameters:
[in] _level the level to start as specified by the UI button and Lua script
Definition at line 11 of file GameWorld.cpp.
References CellGraph::generateWalls(), BaseGameEntity::getCurrentCellID(), EntityManager::getEntityFromID(), BaseGameEntity::getID(), CellGraph::getWallCentres(), CellGraph::getWallNormals(), CellGraph::getWallRotations(), CellGraph::initializeCells(), L, m_activePolice, m_buildingMesh, m_buildingMeshFile, m_cellGraph, m_cellGraphFile, m_entityMgr, m_initialNumberOfRioters, m_lose, m_numberOfObstacles, m_numberOfRioters, m_numberOfRiotersDead, m_numberOfRiotersHome, m_numberOfStreetLights, m_numberOfTrees, m_obstacles, m_policeMesh, m_resetID, m_rioterMesh, m_rioters, m_streetLightMesh, m_streetMesh, m_streetMeshFile, m_treeMesh, m_win, obstacleStreetLight, obstacleTree, registerLua(), BaseGameEntity::setBoudingRadius(), BaseGameEntity::setDetectionRadius(), MovingEntity::setHeading(), and BaseGameEntity::setPos().
{
  L = luaL_newstate();
  registerLua(L);
  m_entityMgr = new EntityManager();
  m_win = 0;
  m_lose = 0;
  m_numberOfRiotersDead = 0;
  m_numberOfRiotersHome = 0;
  m_activePolice = 0;
  m_resetID = 1;
  // get a different lua level based in input level
  switch (_level)
  {
    case 1 :
    {
     luabridge::LuaRef startLevel = luabridge::getGlobal(L, "level1");
     startLevel();
     break;
    }
    case 2 :
    {
     luabridge::LuaRef startLevel = luabridge::getGlobal(L, "level2");
     startLevel();
     break;
    }
    case 3 :
    {
     luabridge::LuaRef startLevel = luabridge::getGlobal(L, "level3");
     startLevel();
     break;
    }
    case 4 :
    {
     luabridge::LuaRef startLevel = luabridge::getGlobal(L, "level4");
     startLevel();
     break;
    }
    case 5 :
    {
     luabridge::LuaRef startLevel = luabridge::getGlobal(L, "level5");
     startLevel();
     break;
    }
    default :
    {
     std::cout<<"Error: Invalid level"<<std::endl;
     break;
    }
  }
  // load in the meshes
  m_streetMesh = new ngl::Obj(m_streetMeshFile); //Obj for roads, should be tris
  m_buildingMesh = new ngl::Obj(m_buildingMeshFile); //Obj for buildings, should be tris
  m_streetMesh->createVAO();
  m_buildingMesh->createVAO();
  m_cellGraph = new CellGraph(m_cellGraphFile, 1); //Obj for cell graph, must be quads
  m_cellGraph->generateWalls();
  m_policeMesh = new ngl::Obj("models/policeMan.obj");
  m_rioterMesh = new ngl::Obj("models/rioterMan.obj");
  m_treeMesh = new ngl::Obj("models/tree.obj");
  m_streetLightMesh = new ngl::Obj("models/streetLight.obj");
  std::vector<ngl::Vec3> wallCentres = m_cellGraph->getWallCentres();
  std::vector<ngl::Vec3> wallNormals = m_cellGraph->getWallNormals();
  std::vector<int> wallRotations = m_cellGraph->getWallRotations();
  m_policeMesh->createVAO();
  m_rioterMesh->createVAO();
  m_treeMesh->createVAO();
  m_streetLightMesh->createVAO();
  //initialise rioters
  for (int i = 0; i < m_initialNumberOfRioters ; ++i)
  {
  Rioter* newRioter = new Rioter(this, m_rioterMesh);
  newRioter->setBoudingRadius(0.5f);
  newRioter->setDetectionRadius(3.5f);
  newRioter->setHeading(ngl::Vec3(-1+2*((float)rand())/RAND_MAX, 0.f, -1+2*((float)rand())/RAND_MAX));
  newRioter->setPos(ngl::Vec3(-25+50*((float)rand())/RAND_MAX, 0.f, -25+50*((float)rand())/RAND_MAX));
  m_cellGraph->initializeCells(m_entityMgr->getEntityFromID(newRioter->getID()));
  while (newRioter->getCurrentCellID() < 0)
  {
    newRioter->setPos(ngl::Vec3(-50+100*((float)rand())/RAND_MAX, 0.f, -50+100*((float)rand())/RAND_MAX));
    m_cellGraph->initializeCells(m_entityMgr->getEntityFromID(newRioter->getID()));
  }
  m_rioters.push_back(newRioter);
  }
  m_numberOfRioters = m_rioters.size();
  // initialise trees
  for (int i = 0; i < m_numberOfTrees ; ++i)
  {
  StaticEntity* newTree = new StaticEntity(this, ngl::Vec3(0,0,0),ngl::Vec3(0.0f,360*((float)rand()/RAND_MAX),0.0f),1.0,obstacleTree,m_treeMesh);
  newTree->setPos(ngl::Vec3(-25+50*((float)rand())/RAND_MAX, 0.f, -25+50*((float)rand())/RAND_MAX));
  m_cellGraph->initializeCells(m_entityMgr->getEntityFromID(newTree->getID()));
  while (newTree->getCurrentCellID() < 0)
  {
    newTree->setPos(ngl::Vec3(-50+100*((float)rand())/RAND_MAX, 0.f, -50+100*((float)rand())/RAND_MAX));
    m_cellGraph->initializeCells(m_entityMgr->getEntityFromID(newTree->getID()));
  }
  m_obstacles.push_back(newTree);
  }
  int numberOfWalls = wallCentres.size();
  //pick random streetlight positions
  int sample[m_numberOfStreetLights];
  std::vector<int> choices;
  int choice;
  for (int i=0; i<numberOfWalls; i++)
  {
    choices.push_back(i);
  }
  srand (time(NULL));
  assert (m_numberOfStreetLights<=numberOfWalls && "too many streetlights for the map size!");
  for(int i=0;i<m_numberOfStreetLights;i++)
  {
  do
  {
    choice = rand() % numberOfWalls;
  }
  while((choices[choice]==-1));
  choices[choice]=-1; // prevents duplicate choices
  sample[i] = choice;
  }
  for (int i = 0; i < m_numberOfStreetLights ; i++)
  {
  StaticEntity* newStreetLight = new StaticEntity(this, wallCentres[sample[i]]+(0.3*wallNormals[sample[i]]), ngl::Vec3(0.0f,wallRotations[sample[i]],0.0f), 0.2, obstacleStreetLight, m_streetLightMesh);
  m_cellGraph->initializeCells(m_entityMgr->getEntityFromID(newStreetLight->getID()));
  m_obstacles.push_back(newStreetLight);
  }
  m_numberOfObstacles = m_obstacles.size();
}
GameWorld::~GameWorld ()
dtor cleans up all entities in the world and closes the Lua state associated with the level
Definition at line 168 of file GameWorld.cpp.
References EntityManager::clearMap(), L, m_buildingMesh, m_deadRioters, m_deadSquads, m_entityMgr, m_obstacles, m_rioters, m_squads, and m_streetMesh.
{
  lua_close(L);
  BOOST_FOREACH(Rioter *r, m_rioters)
  {
    delete r;
  }
  m_rioters.clear();
  BOOST_FOREACH(Squad *s, m_squads)
  {
    delete s;
  }
  m_squads.clear();
  BOOST_FOREACH(StaticEntity *o, m_obstacles)
  {
    delete o;
  }
  m_obstacles.clear();
  BOOST_FOREACH(Rioter *r, m_deadRioters)
  {
    delete r;
  }
  m_deadRioters.clear();
  BOOST_FOREACH(Squad *s, m_deadSquads)
  {
    delete s;
  }
  m_deadSquads.clear();
  delete m_streetMesh;
  delete m_buildingMesh;
  m_entityMgr->clearMap();
  delete m_entityMgr;
}
Member Function Documentation
void GameWorld::addProtestPosition (float _x, float _y, float _z)
method exposed to Lua to add a protest position for rioters to gather around
Parameters:
[in] _x input x world position for the protest position
[in] _y input y world position for the protest position
[in] _z input z world position for the protest position
Definition at line 405 of file GameWorld.cpp.
References m_protestPositions.
{
  m_protestPositions.push_back(ngl::Vec3(_x,_y,_z));
}
void GameWorld::createSquad (int _size)
creates a squad of a specific size
Parameters:
[in] _size the input size of the squad
Definition at line 380 of file GameWorld.cpp.
References m_activePolice, m_availablePolice, m_policeMesh, m_policeStation, and m_squads.
{
    if (m_availablePolice - _size < 0)
    {
      std::cout<<"Not enough police available!"<<std::endl;
    }
    else
    {
      Squad* newSquad = new Squad(this, _size, m_policeStation, 0.5f, m_policeMesh);
      m_squads.push_back(newSquad);
      m_activePolice += _size;
      m_availablePolice -= _size;
    }
}
void GameWorld::draw (ngl::Camera * _cam, ngl::Mat4 _mouseGlobalTX)
method to draw the game world and contained entities
Parameters:
[in] _cam the camera used for the scene
[in] _mouseGlobalTX the global mouse position transformation matrix
Definition at line 338 of file GameWorld.cpp.
References Squad::draw(), Rioter::draw(), StaticEntity::draw(), Squad::drawTarget(), Squad::getSquadState(), loadMatricesToShader(), m_buildingMesh, m_numberOfObstacles, m_numberOfRioters, m_numberOfSquads, m_obstacles, m_rioters, m_squads, m_streetMesh, and squadMove.
{
  ngl::Material a(ngl::Colour(0.2f,0.2f,0.2f, 1.0), ngl::Colour(0.32f,0.31f,0.3f, 1.), ngl::Colour(0.77391f,0.77391f,0.77391f, 1.0));
  a.setSpecularExponent(20.f);
  a.loadToShader("material");
  loadMatricesToShader(_cam, _mouseGlobalTX);
  m_streetMesh->draw();
  ngl::Material b(ngl::Colour(0.2f,0.2f,0.2f, 1.0), ngl::Colour(0.45f,0.45f,0.45f, 1.), ngl::Colour(0.77391f,0.77391f,0.77391f, 1.0));
  b.setSpecularExponent(20.f);
  b.loadToShader("material");
  loadMatricesToShader(_cam, _mouseGlobalTX);
  m_buildingMesh->draw();
  for(unsigned int a=0; a<m_numberOfObstacles; ++a)
  {
    StaticEntity* currentObstacle = m_obstacles[a];
    currentObstacle->draw(_cam, _mouseGlobalTX);
  }
  for(unsigned int a=0; a<m_numberOfRioters; ++a)
  {
    Rioter* currentRioter = m_rioters[a];
    currentRioter->draw(_cam, _mouseGlobalTX);
  }
  m_numberOfSquads = m_squads.size();
  for(unsigned int a=0; a<m_numberOfSquads; ++a)
  {
    Squad* currentSquad = m_squads[a];
    currentSquad->draw(_cam, _mouseGlobalTX);
    if(currentSquad->getSquadState() == squadMove)
    {
      currentSquad->drawTarget(_cam, _mouseGlobalTX);
    }
  }
}
int GameWorld::getAvailablePolice () const [inline]
gets the number of available police during the current level
Returns:
int returns the number of available police during the current level
Definition at line 175 of file GameWorld.h.
References m_availablePolice.
{ return m_availablePolice; }
std::string GameWorld::getBuildingMeshFile () const [inline]
gets the file used for the building mesh
Returns:
std::string returns the file used for the building mesh
Definition at line 210 of file GameWorld.h.
References m_buildingMeshFile.
{ return m_buildingMeshFile; }
CellGraph* GameWorld::getCellGraph () const [inline]
the cell graph generated for the current level
Returns:
CellGraph* returns the cell graph generated for the current level
Definition at line 185 of file GameWorld.h.
References m_cellGraph.
{ return m_cellGraph; }
const char* GameWorld::getCellGraphFile () const [inline]
gets the file used for generating the cell graph
Returns:
char* returns the file used for generating the cell graph
Definition at line 190 of file GameWorld.h.
References m_cellGraphFile.
{ return m_cellGraphFile; }
bool GameWorld::getHasLost () const [inline]
gets if the player has achieved the lose conditions
Returns:
bool returns if the lose state has been achieved (true) or not (false)
Definition at line 79 of file GameWorld.h.
References m_lose.
{ return m_lose; }
bool GameWorld::getHasWon () const [inline]
gets if the player has achieved the win conditions
Returns:
bool returns if the win state has been achieved (true) or not (false)
Definition at line 69 of file GameWorld.h.
References m_win.
{ return m_win; }
int GameWorld::getInitialNumberOfRioters () const [inline]
gets the initial number of rioters that were spawned in the level
Returns:
int returns the initial number of rioters that were spawned in the level
Definition at line 109 of file GameWorld.h.
References m_initialNumberOfRioters.
{ return m_initialNumberOfRioters; }
int GameWorld::getNumberOfRioters () const [inline]
gest the number of rioters in the game world
Returns:
int returns the number of rioters in the game world
Definition at line 104 of file GameWorld.h.
References m_numberOfRioters.
{ return m_numberOfRioters; }
int GameWorld::getNumberOfRiotersDead () const [inline]
gets the number of rioters who have died during this level
Returns:
int returns the number of rioters who have died during this level
Definition at line 119 of file GameWorld.h.
References m_numberOfRiotersDead.
{ return m_numberOfRiotersDead; }
int GameWorld::getNumberOfRiotersDeadToLose () const [inline]
gets the number of rioters needed for the lose state to be achieved
Returns:
int returns the number of rioters needed for the lose state to be achieved
Definition at line 139 of file GameWorld.h.
References m_numberOfRiotersDeadToLose.
{ return m_numberOfRiotersDeadToLose; }
int GameWorld::getNumberOfRiotersHome () const [inline]
gets the number of rioters who have gone home during this level
Returns:
int returns the number of rioters who have gone home during this level
Definition at line 129 of file GameWorld.h.
References m_numberOfRiotersHome.
{ return m_numberOfRiotersHome; }
int GameWorld::getNumberOfRiotersHomeToWin () const [inline]
gets the number of rioters needed for the win state to be achieved
Returns:
int returns the number of rioters needed for the win staete to achieved
Definition at line 149 of file GameWorld.h.
References m_numberOfRiotersHomeToWin.
{ return m_numberOfRiotersHomeToWin; }
int GameWorld::getNumberOfStreetLights () const [inline]
gets the number of street lights spawned in the level
Returns:
in returns the number of street lights spawned in the level
Definition at line 254 of file GameWorld.h.
References m_numberOfStreetLights.
{ return m_numberOfStreetLights; }
int GameWorld::getNumberOfTrees () const [inline]
gets the number of trees spawned in the level
Returns:
int returns the number of trees spawn in the level
Definition at line 244 of file GameWorld.h.
References m_numberOfTrees.
{ return m_numberOfTrees; }
ngl::Vec3 GameWorld::getPoliceStation () const [inline]
gets the world position of the police station
Returns:
ngl::Vec3 returns the world prosition of the police station
Definition at line 232 of file GameWorld.h.
References m_policeStation.
{ return m_policeStation; }
std::vector<ngl::Vec3> GameWorld::getProtestPositions () const [inline]
gets the vector that stores all the protests positions that have been added
Returns:
std::vector<ngl::Vec3> returns the vector that stores the protest positions
Definition at line 227 of file GameWorld.h.
References m_protestPositions.
{ return m_protestPositions; }
bool GameWorld::getResetID () const [inline]
gets if the reset ID is true or false
Returns:
bool returns the value of of the reset ID
Definition at line 89 of file GameWorld.h.
References m_resetID.
{ return m_resetID; }
std::vector<Rioter*> GameWorld::getRioters () const [inline]
gets the vector of all rioters in the current game world
Returns:
std::vector<Rioter*> returns a vector of rioters in game world
Definition at line 99 of file GameWorld.h.
References m_rioters.
{ return m_rioters; }
std::vector<Squad*> GameWorld::getSquads () [inline]
gets the vector of all squads in the current level
Returns:
std::vector<Squad*> returns the vector of all squads in the level
Definition at line 164 of file GameWorld.h.
References m_squads.
{ return m_squads; }
std::string GameWorld::getStreetMeshFile () const [inline]
gets the file used for the street mesh
Returns:
std::string returns the file used for the street mesh
Definition at line 200 of file GameWorld.h.
References m_streetMeshFile.
{ return m_streetMeshFile; }
void GameWorld::loadMatricesToShader (ngl::Camera * _cam, ngl::Mat4 _mouseGlobalTX)
method to load the matrices of the game world to the shader
Parameters:
[in] _cam the camera used for the scene
[in] _mouseGlobalTX the global mouse position transformation matrix
Definition at line 317 of file GameWorld.cpp.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  ngl::Mat3 normalMatrix;
  ngl::Mat4 M;
  M=_mouseGlobalTX;
  MV=  M*_cam->getViewMatrix();
  MVP= M*_cam->getVPMatrix();
  normalMatrix=MV;
  normalMatrix.inverse();
  shader->setShaderParamFromMat4("MV",MV);
  shader->setShaderParamFromMat4("MVP",MVP);
  shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
  shader->setShaderParamFromMat4("M",M);
}
void GameWorld::registerLua (lua_State * _L)
registers all the necessary functions and members with Lua so that they can be edited in our script file
Parameters:
[in] _L the Lua state to register with
Definition at line 410 of file GameWorld.cpp.
References addProtestPosition(), getAvailablePolice(), getBuildingMeshFile(), getCellGraphFile(), getInitialNumberOfRioters(), getNumberOfRiotersDeadToLose(), getNumberOfRiotersHomeToWin(), getNumberOfStreetLights(), getNumberOfTrees(), getStreetMeshFile(), L, setAvailablePolice(), setBuildingMeshFile(), setCellGraphFile(), setInitialNumberOfRioters(), setNumberOfRiotersDeadToLose(), setNumberOfRiotersHomeToWin(), setNumberOfStreetLights(), setNumberOfTrees(), setPoliceStation(), and setStreetMeshFile().
{
  // Set up LUA state
  luaL_dofile(_L, "lua/GameWorld.lua");
  luaL_openlibs(_L);
  luabridge::getGlobalNamespace(_L)
    .beginClass<GameWorld>("GameWorld")
      .addProperty("m_initialNumberOfRioters", &GameWorld::getInitialNumberOfRioters, &GameWorld::setInitialNumberOfRioters)
      .addProperty("m_availablePolice", &GameWorld::getAvailablePolice, &GameWorld::setAvailablePolice)
      .addProperty("m_numberOfTrees", &GameWorld::getNumberOfTrees, &GameWorld::setNumberOfTrees)
      .addProperty("m_numberOfStreetLights", &GameWorld::getNumberOfStreetLights, &GameWorld::setNumberOfStreetLights)
      .addProperty("m_cellGraphFile", &GameWorld::getCellGraphFile, &GameWorld::setCellGraphFile)
      .addProperty("m_numberOfRiotersDeadToLose", &GameWorld::getNumberOfRiotersDeadToLose, &GameWorld::setNumberOfRiotersDeadToLose)
      .addProperty("m_numberOfRiotersHomeToWin", &GameWorld::getNumberOfRiotersHomeToWin, &GameWorld::setNumberOfRiotersHomeToWin)
      .addProperty("m_streetMeshFile", &GameWorld::getStreetMeshFile, &GameWorld::setStreetMeshFile)
      .addProperty("m_buildingMeshFile", &GameWorld::getBuildingMeshFile, &GameWorld::setBuildingMeshFile)
      .addFunction("setPoliceStation", &GameWorld::setPoliceStation)
      .addFunction("addProtestPosition", &GameWorld::addProtestPosition)
    .endClass();
  luabridge::push(L, this);
  lua_setglobal(L, "gameWorld");
}
void GameWorld::setAvailablePolice (const int _availablePolice) [inline]
sets the number of available police during the current level
Parameters:
[in] _availablePolice value to set as the number of available police
Definition at line 180 of file GameWorld.h.
References m_availablePolice.
{ m_availablePolice = _availablePolice; }
void GameWorld::setBuildingMeshFile (const std::string _file) [inline]
sets the file to be used for the building mesh
Parameters:
[in] _file the input file to be used for the building mesh
Definition at line 215 of file GameWorld.h.
References m_buildingMeshFile.
{ m_buildingMeshFile = _file; }
void GameWorld::setCellGraphFile (const char * _file) [inline]
sets the file to be used for generating the cell graph
Parameters:
[in] _file the input file to be used for generating the cell graph
Definition at line 195 of file GameWorld.h.
References m_cellGraphFile.
{ m_cellGraphFile = _file;}
void GameWorld::setHasLost (const bool _inBool) [inline]
sets that the play has achieved the lose state or not
Parameters:
[in] _inBool the boolean to assign to the lose state
Definition at line 84 of file GameWorld.h.
References m_lose.
{ m_lose = _inBool; }
void GameWorld::setHasWon (const bool _inBool) [inline]
sets that the player has achieved the win state or not
Parameters:
[in] _inBool the boolean to assign to the win state
Definition at line 74 of file GameWorld.h.
References m_win.
{ m_win = _inBool; }
void GameWorld::setInitialNumberOfRioters (const int _number) [inline]
sets the initial number of rioters that were spawned in the level
Parameters:
[in] _number amount to set as the initial number of rioters
Definition at line 114 of file GameWorld.h.
References m_initialNumberOfRioters.
{ m_initialNumberOfRioters = _number; }
void GameWorld::setNumberOfRiotersDead (const int _number) [inline]
sets the number of rioters who have died during this level
Parameters:
[in] _number amount to set as the number of dead rioters
Definition at line 124 of file GameWorld.h.
References m_numberOfRiotersDead.
{ m_numberOfRiotersDead = _number; }
void GameWorld::setNumberOfRiotersDeadToLose (const int _number) [inline]
sets the number of rioters needed for the lose state to be achieved
Parameters:
[in] _number value to set as the number of dead rioters needed to achieve the lose state
Definition at line 144 of file GameWorld.h.
References m_numberOfRiotersDeadToLose.
{ m_numberOfRiotersDeadToLose = _number; }
void GameWorld::setNumberOfRiotersHome (const int _number) [inline]
sets the number of rioters that have gone home during this level
Parameters:
[in] _number amount to set as the number of rioters who have gone home
Definition at line 134 of file GameWorld.h.
References m_numberOfRiotersHome.
{ m_numberOfRiotersHome = _number; }
void GameWorld::setNumberOfRiotersHomeToWin (const int _number) [inline]
sets the number of rioters needed for the win state to be achieved
Parameters:
[in] _number value to set as the number of rioter needed to have gone home to achieve the win state
Definition at line 154 of file GameWorld.h.
References m_numberOfRiotersHomeToWin.
{ m_numberOfRiotersHomeToWin = _number; }
void GameWorld::setNumberOfStreetLights (const int _number) [inline]
sets the number of street lights spawned in the level
Parameters:
[in] _number input number to assign to the number of spawned street lights
Definition at line 259 of file GameWorld.h.
References m_numberOfStreetLights.
{m_numberOfStreetLights = _number; }
void GameWorld::setNumberOfTrees (const int _number) [inline]
sets the number of trees spawned in the level
Parameters:
[in] _number input number to assign to number of spawned trees
Definition at line 249 of file GameWorld.h.
References m_numberOfTrees.
{m_numberOfTrees = _number; }
void GameWorld::setPoliceStation (const float _x, const float _y, const float _z)
method exposed to Lua that sets the world position of the police state
Parameters:
[in] _x input x world position for the police station
[in] _y input y world position for the police station
[in] _z input z world position for the police station
Definition at line 162 of file GameWorld.cpp.
References m_policeStation.
{
  ngl::Vec3 pos = ngl::Vec3(_x,_y,_z);
  m_policeStation = pos;
}
void GameWorld::setResetID (const bool _resetID) [inline]
sets if the reset ID is true or false
Parameters:
[in] _resetID the boolean to assign to the reset ID
Definition at line 94 of file GameWorld.h.
References m_resetID.
{ m_resetID = _resetID; }
void GameWorld::setStreetMeshFile (const std::string _file) [inline]
sets the file to be used for the street mesh
Parameters:
[in] _file the input file to be used for generating the street mesh
Definition at line 205 of file GameWorld.h.
References m_streetMeshFile.
{ m_streetMeshFile = _file; }
void GameWorld::squadTarget (Squad * _selectedSquad, ngl::Vec3 _target)
sets the target position for the currently selected squad
Parameters:
[in] _selectedSquad the currently selected squad
[in] _the target position to be given to the squad
Definition at line 397 of file GameWorld.cpp.
References m_cellGraph, CellGraph::posIsInCell(), and Squad::setTarget().
{
  if(m_cellGraph->posIsInCell(_target))
  {
    _selectedSquad->setTarget(_target);
  }
}
void GameWorld::Update (double _timeElapsed, double _currentTime)
updates all of the entities in the world, the cells in the cell graph and checks for change in state
Parameters:
[in] _timeElapsed the time elapsed since last tick
[in] _currentTime the current time of the level
Definition at line 205 of file GameWorld.cpp.
References CellGraph::addEntities(), CellGraph::clearCells(), Rioter::death(), EntityManager::getEntityMap(), Agent::getHealth(), CellGraph::getMapBounds(), BaseGameEntity::getPos(), Squad::getSquadSize(), m_activePolice, m_availablePolice, m_cellGraph, m_deadRioters, m_deadSquads, m_entityMgr, m_lose, m_numberOfRioters, m_numberOfRiotersDead, m_numberOfRiotersDeadToLose, m_numberOfRiotersHome, m_numberOfRiotersHomeToWin, m_numberOfSquads, m_rioters, m_squads, m_win, EntityManager::removeEntity(), Squad::update(), Rioter::update(), and CellGraph::updateCells().
{
  //check for deaths/homes
  m_numberOfSquads = m_squads.size();
  m_numberOfRioters = m_rioters.size();
  for(int i=0; i<m_numberOfRioters; i++)
  {
    Rioter* currentRioter = m_rioters[i];
    std::vector<float> map_bounds = m_cellGraph->getMapBounds();
    //check for rioter deaths
    if(currentRioter->getHealth()<=0.f)
    {
      currentRioter->death();
      m_entityMgr->removeEntity(dynamic_cast<BaseGameEntity*>(currentRioter));
      m_deadRioters.push_back(currentRioter);
      m_rioters.erase(m_rioters.begin()+i);
      m_numberOfRioters--;
      m_numberOfRiotersDead ++;
      i--;
    }
    //check for when rioters have left the map
    else if(currentRioter->getPos().m_z <= map_bounds[0] ||
            currentRioter->getPos().m_z >= map_bounds[1] ||
            currentRioter->getPos().m_x <= map_bounds[2] ||
            currentRioter->getPos().m_x >= map_bounds[3])
    {
      m_entityMgr->removeEntity(dynamic_cast<BaseGameEntity*>(currentRioter));
      m_deadRioters.push_back(currentRioter);
      m_rioters.erase(m_rioters.begin()+i);
      m_numberOfRioters--;
      m_numberOfRiotersHome++;
      i--;
    }
  }
  //check for squad deaths
  for(int i = 0; i < m_numberOfSquads; i++)
  {
    Squad* currentSquad = m_squads[i];
    if (currentSquad->getSquadSize() <= 0)
    {
      m_deadSquads.push_back(currentSquad);
      m_entityMgr->removeEntity(currentSquad);
      m_squads.erase(m_squads.begin()+i);
      m_numberOfSquads--;
      i--;
    }
    else
    {
      m_activePolice -= m_squads[i]->checkDeaths();
    }
  }
  // update cells
  m_cellGraph->clearCells();
  std::map<int,BaseGameEntity*> myMap = m_entityMgr->getEntityMap();
  for (std::map<int,BaseGameEntity*>::const_iterator it = myMap.begin(); it != myMap.end(); ++it)
  {
    //Adds entities to cells and cell ID to entities
    m_cellGraph->updateCells(it->second);
  }
  for (std::map<int,BaseGameEntity*>::const_iterator it = myMap.begin(); it != myMap.end(); ++it)
  {
    //Adds entity neighbours:
    if (it->second->getCurrentCellID() >= 0)
    {
      m_cellGraph->addEntities(it->second);
    }
  }
  // call rioter and squad updates
  m_numberOfRioters = m_rioters.size();
  for(unsigned int a=0; a<m_numberOfRioters; ++a)
  {
    Rioter* currentRioter = m_rioters[a];
    currentRioter->update(_timeElapsed, _currentTime);
  }
  m_numberOfSquads = m_squads.size();
  for(unsigned int a=0; a<m_numberOfSquads; ++a)
  {
    Squad* currentSquad = m_squads[a];
    currentSquad->update(_timeElapsed, _currentTime);
  }
  // check for win/lose states
  if(m_numberOfRiotersHome >= m_numberOfRiotersHomeToWin)
  {
    m_win = 1;
  }
  if(m_numberOfRiotersDead >= m_numberOfRiotersDeadToLose)
  {
    m_lose = 1;
  }
  if(m_availablePolice <= 0 && m_activePolice <= 0)
  {
    m_lose = 1;
  }
}
Member Data Documentation
lua_State* GameWorld::L [private]
the Lua state that is registers with the game world
Definition at line 270 of file GameWorld.h.
int GameWorld::m_activePolice [private]
the number of active police in the level
Definition at line 346 of file GameWorld.h.
int GameWorld::m_availablePolice [private]
the number of available police in the level
Definition at line 342 of file GameWorld.h.
ngl::Obj* GameWorld::m_buildingMesh [private]
a pointer to the mesh to be used by the building in the level
Definition at line 390 of file GameWorld.h.
std::string GameWorld::m_buildingMeshFile [private]
the string location and name of the building mesh
Definition at line 394 of file GameWorld.h.
CellGraph* GameWorld::m_cellGraph [private]
a pointer to the cell graph used by the world to generate the cell space partitioning
Definition at line 374 of file GameWorld.h.
const char* GameWorld::m_cellGraphFile [private]
the char* location and name of the file to be used by the cell graph
Definition at line 378 of file GameWorld.h.
std::vector<Rioter*> GameWorld::m_deadRioters [private]
a vector containing all the dead rioters to be used later or discarded
Definition at line 306 of file GameWorld.h.
std::vector<Squad*> GameWorld::m_deadSquads [private]
the number of dead squads in currently in the level
Definition at line 334 of file GameWorld.h.
std::vector<int> GameWorld::m_dynamicEntities [private]
a vector containing all of the dynamic entites found within the world
Definition at line 286 of file GameWorld.h.
EntityManager* GameWorld::m_entityMgr [private]
a pointer to the entity manager monostate
Definition at line 266 of file GameWorld.h.
int GameWorld::m_initialNumberOfRioters [private]
the value of the initial number of rioters spawned at the start of the level
Definition at line 298 of file GameWorld.h.
bool GameWorld::m_lose [private]
a boolean to determin if the lose state has been achieved
Definition at line 282 of file GameWorld.h.
int GameWorld::m_numberOfObstacles [private]
the number of obstacles currently in the level
Definition at line 362 of file GameWorld.h.
int GameWorld::m_numberOfRioters [private]
the value of the number of rioters currently in the level
Definition at line 302 of file GameWorld.h.
int GameWorld::m_numberOfRiotersDead [private]
the number of dead rioters in the world
Definition at line 310 of file GameWorld.h.
int GameWorld::m_numberOfRiotersDeadToLose [private]
the number of rioters who have to die for the player to lose
Definition at line 318 of file GameWorld.h.
int GameWorld::m_numberOfRiotersHome [private]
the number of rioters who have gone home during the game
Definition at line 314 of file GameWorld.h.
int GameWorld::m_numberOfRiotersHomeToWin [private]
the number of rioters who have to go home for the player to win
Definition at line 322 of file GameWorld.h.
int GameWorld::m_numberOfSquads [private]
the number of squads currently in the level
Definition at line 330 of file GameWorld.h.
int GameWorld::m_numberOfStreetLights [private]
the number of street lights currently in the level
Definition at line 370 of file GameWorld.h.
int GameWorld::m_numberOfTrees [private]
the number of trees currently in the level
Definition at line 366 of file GameWorld.h.
std::vector<StaticEntity*> GameWorld::m_obstacles [private]
a vector containing all of the obstacles currently in the level
Definition at line 358 of file GameWorld.h.
ngl::Obj* GameWorld::m_policeMesh [private]
a pointer to the mesh that will be used by all police in the world
Definition at line 338 of file GameWorld.h.
ngl::Vec3 GameWorld::m_policeStation [private]
the location of the police station where new squads are spawned
Definition at line 398 of file GameWorld.h.
std::vector<ngl::Vec3> GameWorld::m_protestPositions [private]
a vector containing all of the position where rioters gather when protesting
Definition at line 402 of file GameWorld.h.
bool GameWorld::m_resetID [private]
a boolean that is set to true when the game is reset
Definition at line 274 of file GameWorld.h.
ngl::Obj* GameWorld::m_rioterMesh [private]
a pointer to the mesh that will be used by all rioters in the world
Definition at line 290 of file GameWorld.h.
std::vector<Rioter*> GameWorld::m_rioters [private]
a vector containing all of the rioters found within the world
Definition at line 294 of file GameWorld.h.
std::vector<Squad*> GameWorld::m_squads [private]
a vector containing all of the squads currently in the level
Definition at line 326 of file GameWorld.h.
ngl::Obj* GameWorld::m_streetLightMesh [private]
a pointer to the mesh that will be used by all street lights in the world
Definition at line 354 of file GameWorld.h.
ngl::Obj* GameWorld::m_streetMesh [private]
a pointer to the mesh to be used by the street in the level
Definition at line 382 of file GameWorld.h.
std::string GameWorld::m_streetMeshFile [private]
the string location and name of the street mesh
Definition at line 386 of file GameWorld.h.
ngl::Obj* GameWorld::m_treeMesh [private]
a pointer to the mesh that will be used by all trees in the world
Definition at line 350 of file GameWorld.h.
bool GameWorld::m_win [private]
a boolean to determin if the win state has been achieved
Definition at line 278 of file GameWorld.h.
The documentation for this class was generated from the following files:
GameWorld.h
GameWorld.cpp