YOURPROJECTNAMEGOESHERE: MessageManager Class Reference
MessageManager Class Reference
A manager monostate class that helps handle the sending and receiving of messages between entities.
#include <MessageManager.h>
Public Member Functions
MessageManager ()
ctor contrsucts the message manager and gives it access to the entity manager
~MessageManager ()
void sendMessage (int _senderID, int _receiverID, int _message, float _extraInfo)
method to send a message from a sender to a reciever with any additional information
Private Member Functions
void send (BaseGameEntity *_receiver, const Message &_message)
a method that ensures that messages are handled successfully
Detailed Description
A manager monostate class that helps handle the sending and receiving of messages between entities.
Author:
Will Herbert & Emily Holt
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 31 of file MessageManager.h.
Constructor & Destructor Documentation
MessageManager::MessageManager ()
ctor contrsucts the message manager and gives it access to the entity manager
Definition at line 9 of file MessageManager.cpp.
{
}
MessageManager::~MessageManager ()
Definition at line 12 of file MessageManager.cpp.
{
}
Member Function Documentation
void MessageManager::send (BaseGameEntity * _receiver, const Message & _message) [private]
a method that ensures that messages are handled successfully
Definition at line 33 of file MessageManager.cpp.
References BaseGameEntity::handleMessage().
{
  if (_receiver->handleMessage(_message) == false)
  {
    std::cout<<"MessageManager::discharge: message could not be handled"<<std::endl;
  }
}
void MessageManager::sendMessage (int _senderID, int _receiverID, int _message, float _extraInfo)
method to send a message from a sender to a reciever with any additional information
Parameters:
[in] _senderID the ID of the entity that wants to send a message
[in] _recieverID the ID of the entity that will receive the message
[in] _message the message type that will be sent
[in] _extraInfo information that is used by the reciever in a way specified by the message type
Definition at line 17 of file MessageManager.cpp.
References EntityManager::getEntityFromID(), and send().
{
  EntityManager* entityMgr;
  entityMgr = new EntityManager();
  BaseGameEntity* receiver = (BaseGameEntity*)entityMgr->getEntityFromID(_receiverID);
  if (receiver == NULL)
  {
    std::cout<<"Error: No receiver with ID of "<<_receiverID<<" found"<<std::endl;
    return;
  }
  Message message(_senderID, _receiverID, _message, _extraInfo);
  send(receiver, message);
  delete entityMgr;
}
The documentation for this class was generated from the following files:
MessageManager.h
MessageManager.cpp