YOURPROJECTNAMEGOESHERE: BaseGameEntity Class Reference
BaseGameEntity Class Reference
The base class for all entities in the game, static or moving.
#include <BaseGameEntity.h>
Public Member Functions
BaseGameEntity (GameWorld *_world, entityType _entityType, ngl::Vec3 _pos, float _r)
ctor this will create a base game entitiy in a valid world, with a type, position and radius, and register
~BaseGameEntity ()
dtor used to clean up the base game entity
virtual bool handleMessage (const Message &_message)=0
virtual pure function to determin how any messages received by the base game entity should be handled
int getID () const
gets the ID of the base game entity
entityType getEntityType () const
gets the entity type of the base game entity
void setEntityType (const entityType _newType)
sets the entity type of the base game entity
ngl::Vec3 getPos () const
gets the position of the base game enitity in world space
void setPos (const ngl::Vec3 _newPos)
sets the position of the base game enitity in world space
float getBoundingRadius () const
gets the bounding radius of the base game entity
void setBoudingRadius (const float _r)
sets the bounding radius of the base game entitity
float getDetectionRadius () const
gets the detection radius of the base game entity
void setDetectionRadius (const float _r)
sets the detection radius of the base game entity
void addDetectedDynamicEntityID (int _ID)
adds the detected entity's ID to the vector of detected entity IDs
void clearDetectedDynamicEntityID ()
clears all the IDs stored within the detected dynamic entity IDs vector
std::vector< int > getDetectedEntityIDs ()
gets the vector of all detected dynamic entitys IDs
std::vector< int > getNeighbourPoliceIDs ()
gets the vector of all neighbour police IDs
std::vector< int > getNeighbourRioterIDs ()
gets the vector of all neighbour rioter IDs
std::vector< int > getNeighbourObstacleIDs ()
gets the vector of all neighbour obstacle IDs
void addPoliceID (int _ID)
adds the input police ID to the vector of neighbour police IDs
void addRioterID (int _ID)
adds the input police ID to the vector of neighbour rioter IDs
void addObstacleID (int _ID)
adds the input police ID to the vector of neighbour obstacle IDs
void clearAgentIDs ()
clears all of the vectors of neighbour police/rioter/obstacle IDs
Cell getCurrentCell ()
gets the current cell that the base game entity in located in
void setCurrentCell (const Cell _inCell)
sets the current cell that the base game enitity is located in
int getCurrentCellID ()
gets the ID of the current cell for the base game entity
void setCurrentCellID (const int _ID)
sets the current cell ID for the base game entity
Protected Member Functions
void setID (int _val)
a method to set the ID of the base game entity for the entity manager
Protected Attributes
GameWorld * m_world
a pointer to the world that the base game entity is contained in
EntityManager * m_entityMgr
a pointer to the entity manager that the base game entity is registered with
MessageManager * m_messageMgr
a pointer to the message manager that the base game entity uses to send messages
int m_ID
the value of the base game entity's ID
bool m_resetID
used to reset the IDs when the game is restarted
entityType m_entityType
the entity type of the base game entity
ngl::Vec3 m_pos
the position vector in world space of the base game entity
float m_boundingRadius
the bouding radius of the base game entity
float m_detectionRadius
the detection radius of the base game entity
std::vector< int > m_detectedDynamicEntityIDs
a vector of integer IDs for detected dynamic entities
std::vector< int > m_neighbourPoliceIDs
a vector of integer IDs for neighbour police IDs
std::vector< int > m_neighbourRioterIDs
a vector of integer IDs for neighbour rioters IDs
std::vector< int > m_neighbourObstacleIDs
a vector of ineteger IDs for neighbour obstacles
Cell m_currentCell
the current cell that the base game entity is located in
int m_currentCellID
the integer ID of the current cell that the base game entity is located in
Static Protected Attributes
static int m_nextValidID = 0
the value of the next valid ID to be used by the entity manager
Detailed Description
The base class for all entities in the game, static or moving.
Author:
Will Herbert & Faye Butler & Emily Holt
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 38 of file BaseGameEntity.h.
Constructor & Destructor Documentation
BaseGameEntity::BaseGameEntity (GameWorld * _world, entityType _entityType, ngl::Vec3 _pos, float _r)
ctor this will create a base game entitiy in a valid world, with a type, position and radius, and register
it's unique ID with the Entity Manager
Parameters:
[in] _world input world to create the base game entity in
[in] _entityType input entity type to set for base game entity
[in] _pos input world position vector to spawn the base game entity at
[in] _r input radius to set as the bounding radius of the base game entity
Definition at line 15 of file BaseGameEntity.cpp.
References GameWorld::getCellGraph(), GameWorld::getResetID(), CellGraph::initializeCells(), m_boundingRadius, m_detectionRadius, m_entityMgr, m_entityType, m_messageMgr, m_nextValidID, m_pos, m_world, EntityManager::registerEntity(), setID(), and GameWorld::setResetID().
{
  m_world = _world;
  if(m_world->getResetID()==1)
  {
    m_nextValidID = 0;
    m_world->setResetID(0);
  }
  setID(m_nextValidID);
  m_nextValidID++;
  m_entityMgr = new EntityManager();
  m_entityMgr->registerEntity(this);
  m_messageMgr = new MessageManager();
  m_pos = _pos;
  m_boundingRadius = _r;
  m_entityType = _entityType;
  m_detectionRadius = _r * 3;
  m_world->getCellGraph()->initializeCells(this);
}
BaseGameEntity::~BaseGameEntity ()
dtor used to clean up the base game entity
Definition at line 40 of file BaseGameEntity.cpp.
References m_entityMgr, and m_messageMgr.
{
  delete m_entityMgr;
  delete m_messageMgr;
}
Member Function Documentation
void BaseGameEntity::addDetectedDynamicEntityID (int _ID) [inline]
adds the detected entity's ID to the vector of detected entity IDs
Parameters:
[in] _ID the input ID of the detected entity to add
Definition at line 108 of file BaseGameEntity.h.
References m_detectedDynamicEntityIDs.
{ m_detectedDynamicEntityIDs.push_back(_ID); }
void BaseGameEntity::addObstacleID (int _ID) [inline]
adds the input police ID to the vector of neighbour obstacle IDs
Parameters:
[in] _ID input ID to add to vector of neighbour obstacle IDs
Definition at line 147 of file BaseGameEntity.h.
References m_neighbourObstacleIDs.
{ m_neighbourObstacleIDs.push_back(_ID); }
void BaseGameEntity::addPoliceID (int _ID) [inline]
adds the input police ID to the vector of neighbour police IDs
Parameters:
[in] _ID input ID to add to vector of neighbour police IDs
Definition at line 137 of file BaseGameEntity.h.
References m_neighbourPoliceIDs.
{ m_neighbourPoliceIDs.push_back(_ID); }
void BaseGameEntity::addRioterID (int _ID) [inline]
adds the input police ID to the vector of neighbour rioter IDs
Parameters:
[in] _ID input ID to add to vector of neighbour rioter IDs
Definition at line 142 of file BaseGameEntity.h.
References m_neighbourRioterIDs.
{ m_neighbourRioterIDs.push_back(_ID); }
void BaseGameEntity::clearAgentIDs () [inline]
clears all of the vectors of neighbour police/rioter/obstacle IDs
Definition at line 151 of file BaseGameEntity.h.
References m_neighbourObstacleIDs, m_neighbourPoliceIDs, and m_neighbourRioterIDs.
                       {     m_neighbourPoliceIDs.clear();
                             m_neighbourRioterIDs.clear();
                             m_neighbourObstacleIDs.clear(); }
void BaseGameEntity::clearDetectedDynamicEntityID () [inline]
clears all the IDs stored within the detected dynamic entity IDs vector
Definition at line 112 of file BaseGameEntity.h.
References m_detectedDynamicEntityIDs.
{ m_detectedDynamicEntityIDs.clear(); }
float BaseGameEntity::getBoundingRadius () const [inline]
gets the bounding radius of the base game entity
Returns:
float the bounding radius of the base game enitity
Definition at line 88 of file BaseGameEntity.h.
References m_boundingRadius.
{ return m_boundingRadius; }
Cell BaseGameEntity::getCurrentCell () [inline]
gets the current cell that the base game entity in located in
Returns:
Cell the object of the cell that the base game entity is located in
Definition at line 158 of file BaseGameEntity.h.
References m_currentCell.
{ return m_currentCell; }
int BaseGameEntity::getCurrentCellID () [inline]
gets the ID of the current cell for the base game entity
Returns:
int the ID of the current cell for the base game entity
Definition at line 168 of file BaseGameEntity.h.
References m_currentCellID.
{ return m_currentCellID; }
std::vector<int> BaseGameEntity::getDetectedEntityIDs () [inline]
gets the vector of all detected dynamic entitys IDs
Returns:
std::vector<int> the vector of all detected dynamic entity IDs
Definition at line 117 of file BaseGameEntity.h.
References m_detectedDynamicEntityIDs.
{ return m_detectedDynamicEntityIDs; }
float BaseGameEntity::getDetectionRadius () const [inline]
gets the detection radius of the base game entity
Returns:
float the detection radius of the base game entity
Definition at line 98 of file BaseGameEntity.h.
References m_detectionRadius.
{return m_detectionRadius; }
entityType BaseGameEntity::getEntityType () const [inline]
gets the entity type of the base game entity
Returns:
enum entityType the enum type of the base game entity
Definition at line 68 of file BaseGameEntity.h.
References m_entityType.
{ return m_entityType; }
int BaseGameEntity::getID () const [inline]
gets the ID of the base game entity
Returns:
int the value of the base game entity's ID
Definition at line 63 of file BaseGameEntity.h.
References m_ID.
{ return m_ID; }
std::vector<int> BaseGameEntity::getNeighbourObstacleIDs () [inline]
gets the vector of all neighbour obstacle IDs
Returns:
std::vector<int> the vector of all neighbour obstacle IDs
Definition at line 132 of file BaseGameEntity.h.
References m_neighbourObstacleIDs.
{ return m_neighbourObstacleIDs; }
std::vector<int> BaseGameEntity::getNeighbourPoliceIDs () [inline]
gets the vector of all neighbour police IDs
Returns:
std::vector<int> the vector of all neighbour police IDs
Definition at line 122 of file BaseGameEntity.h.
References m_neighbourPoliceIDs.
{ return m_neighbourPoliceIDs; }
std::vector<int> BaseGameEntity::getNeighbourRioterIDs () [inline]
gets the vector of all neighbour rioter IDs
Returns:
std::vector<int> the vector of all neighbour rioter IDs
Definition at line 127 of file BaseGameEntity.h.
References m_neighbourRioterIDs.
{ return m_neighbourRioterIDs; }
ngl::Vec3 BaseGameEntity::getPos () const [inline]
gets the position of the base game enitity in world space
Returns:
ngl::Vec3 the vector position of the base game entity
Definition at line 78 of file BaseGameEntity.h.
References m_pos.
{ return m_pos; }
bool BaseGameEntity::handleMessage (const Message & _message) [pure virtual]
virtual pure function to determin how any messages received by the base game entity should be handled
Parameters:
[in] _message the message to be received by the base game entitiy
Implemented in Agent, MovingEntity, Police, Rioter, Squad, StaticEntity, and Vehicle.
Definition at line 47 of file BaseGameEntity.cpp.
References Message::m_message.
{
  switch(_message.m_message)
  {
    default:
    {
      std::cout<<"BaseGameEntity: Message type not defined"<<std::endl;
      return false;
    }
  }
}
void BaseGameEntity::setBoudingRadius (const float _r) [inline]
sets the bounding radius of the base game entitity
Parameters:
[in] _r the new bouding radius of the base game entity
Definition at line 93 of file BaseGameEntity.h.
References m_boundingRadius.
{ m_boundingRadius = _r; }
void BaseGameEntity::setCurrentCell (const Cell _inCell) [inline]
sets the current cell that the base game enitity is located in
Parameters:
[in] _inCell the cell to set as the current cell
Definition at line 163 of file BaseGameEntity.h.
References m_currentCell.
{ m_currentCell = _inCell; }
void BaseGameEntity::setCurrentCellID (const int _ID) [inline]
sets the current cell ID for the base game entity
Parameters:
[in] _ID the ID of the input cell to set as current
Definition at line 173 of file BaseGameEntity.h.
References m_currentCellID.
{ m_currentCellID = _ID; }
void BaseGameEntity::setDetectionRadius (const float _r) [inline]
sets the detection radius of the base game entity
Parameters:
[in] _r the new detection radius of the base game entity
Definition at line 103 of file BaseGameEntity.h.
References m_detectionRadius.
{ m_detectionRadius = _r; }
void BaseGameEntity::setEntityType (const entityType _newType) [inline]
sets the entity type of the base game entity
Parameters:
[in] _newType input to set the new type of the base game entity
Definition at line 73 of file BaseGameEntity.h.
References m_entityType.
{ m_entityType = _newType; }
void BaseGameEntity::setID (int _val) [inline, protected]
a method to set the ID of the base game entity for the entity manager
Definition at line 199 of file BaseGameEntity.h.
References m_ID.
{ m_ID = _val; }
void BaseGameEntity::setPos (const ngl::Vec3 _newPos) [inline]
sets the position of the base game enitity in world space
Parameters:
[in] _newPos input to set the new position of the base game entity in world space
Definition at line 83 of file BaseGameEntity.h.
References m_pos.
{ m_pos = _newPos; }
Member Data Documentation
float BaseGameEntity::m_boundingRadius [protected]
the bouding radius of the base game entity
Definition at line 215 of file BaseGameEntity.h.
Cell BaseGameEntity::m_currentCell [protected]
the current cell that the base game entity is located in
Definition at line 239 of file BaseGameEntity.h.
int BaseGameEntity::m_currentCellID [protected]
the integer ID of the current cell that the base game entity is located in
Definition at line 243 of file BaseGameEntity.h.
std::vector<int> BaseGameEntity::m_detectedDynamicEntityIDs [protected]
a vector of integer IDs for detected dynamic entities
Definition at line 223 of file BaseGameEntity.h.
float BaseGameEntity::m_detectionRadius [protected]
the detection radius of the base game entity
Reimplemented in Agent.
Definition at line 219 of file BaseGameEntity.h.
EntityManager* BaseGameEntity::m_entityMgr [protected]
a pointer to the entity manager that the base game entity is registered with
Definition at line 183 of file BaseGameEntity.h.
entityType BaseGameEntity::m_entityType [protected]
the entity type of the base game entity
Definition at line 207 of file BaseGameEntity.h.
int BaseGameEntity::m_ID [protected]
the value of the base game entity's ID
Definition at line 191 of file BaseGameEntity.h.
MessageManager* BaseGameEntity::m_messageMgr [protected]
a pointer to the message manager that the base game entity uses to send messages
Reimplemented in Rioter.
Definition at line 187 of file BaseGameEntity.h.
std::vector<int> BaseGameEntity::m_neighbourObstacleIDs [protected]
a vector of ineteger IDs for neighbour obstacles
Definition at line 235 of file BaseGameEntity.h.
std::vector<int> BaseGameEntity::m_neighbourPoliceIDs [protected]
a vector of integer IDs for neighbour police IDs
Definition at line 227 of file BaseGameEntity.h.
std::vector<int> BaseGameEntity::m_neighbourRioterIDs [protected]
a vector of integer IDs for neighbour rioters IDs
Definition at line 231 of file BaseGameEntity.h.
int BaseGameEntity::m_nextValidID = 0 [static, protected]
the value of the next valid ID to be used by the entity manager
the starting valid ID to be used
Definition at line 195 of file BaseGameEntity.h.
ngl::Vec3 BaseGameEntity::m_pos [protected]
the position vector in world space of the base game entity
Definition at line 211 of file BaseGameEntity.h.
bool BaseGameEntity::m_resetID [protected]
used to reset the IDs when the game is restarted
Definition at line 203 of file BaseGameEntity.h.
GameWorld* BaseGameEntity::m_world [protected]
a pointer to the world that the base game entity is contained in
Definition at line 179 of file BaseGameEntity.h.
The documentation for this class was generated from the following files:
BaseGameEntity.h
BaseGameEntity.cpp