YOURPROJECTNAMEGOESHERE: Rioter Class Reference
Rioter Class Reference
The base class for all rioters.
#include <Rioter.h>
Public Member Functions
Rioter (GameWorld *world, ngl::Obj *_mesh)
Rioter ctor.
~Rioter ()
Rioter dtor.
lua_State * getLuaState () const
Gets the lua state of the rioters.
void update (double timeElapsed, double currentTime)
Method to update the rioter at every tick.
void draw (ngl::Camera *cam, ngl::Mat4 mouseGlobalTX)
Method to draw the rioters.
void loadMatricesToShader (ngl::Camera *cam, ngl::Mat4 mouseGlobalTX)
Method to load the matrices of the rioter to the shader.
StateMachine< Rioter > * getStateMachine () const
Gets the state machine of the rioter.
void findTargetID (float _health)
Method to find a target to pursue.
bool handleMessage (const Message &_message)
Method to define how to handle messages.
void attack ()
Method to send message to attack (deliver damage to target).
void death ()
Method to send message if a rioter has died.
void findPathHome ()
Method to set the rioter on a path to an exit.
void protestCohesion (double weight)
Method to set the protest cohesion of the rioter.
void registerClass (lua_State *_L)
Method to register class, functions and properties to be used in lua.
float getPoliceInfluence () const
Gets the influence of the police.
ngl::Vec3 getProtestPos () const
Get the protest position.
void setProtestPos (ngl::Vec3 newPos)
Set the protest position.
Protected Attributes
MessageManager * m_messageMgr
Pointer to the message manager.
StateMachine< Rioter > * m_stateMachine
Pointer to the state machine.
ngl::Vec3 m_protestPos
Vector to contain the protest position.
float m_policeInfluence
Float to hold the amount of police influence.
Detailed Description
The base class for all rioters.
Author:
Faye Butler, Will Herbert
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 20 of file Rioter.h.
Constructor & Destructor Documentation
Rioter::Rioter (GameWorld * world, ngl::Obj * _mesh)
Rioter ctor.
Parameters:
[in] world,: Pointer to the gameworld
[in] _mesh,: Pointer to the obj mesh for a rioter
Definition at line 10 of file Rioter.cpp.
References Agent::L, BaseGameEntity::m_entityType, Agent::m_hopHeight, Agent::m_hopSpeed, Agent::m_mesh, m_policeInfluence, m_protestPos, m_stateMachine, SteeringBehaviour::ObstacleAvoidOn(), registerClass(), SteeringBehaviour::setWallAvoidWeight(), Vehicle::Steering(), typeRioter, and SteeringBehaviour::WallAvoidOn().
                                              : Agent(world)
{
    m_entityType = typeRioter;
    //m_gameworld = world;
    // Set up LUA state
    luaL_dofile(L, "lua/Rioter.lua");
    luaL_openlibs(L);
  // Set up LUA state
  luaL_dofile(L, "lua/Rioter.lua");
  luaL_openlibs(L);
  registerClass(L);
  luabridge::push(L, this);
  lua_setglobal(L, "rioter");
  // Set up state machine
  m_stateMachine = new StateMachine<Rioter>(this);
  // Set initial variables
  m_mesh = _mesh;
  m_hopHeight = 0.5;
  m_hopSpeed = 0.0;
  luabridge::LuaRef makeRioter = luabridge::getGlobal(L, "makeRioter");
  makeRioter();
  Vehicle::Steering()->WallAvoidOn();
  Vehicle::Steering()->setWallAvoidWeight(0.4);
  Vehicle::Steering()->ObstacleAvoidOn();
  m_policeInfluence = 0.0;
  m_protestPos = ngl::Vec3(0,0,0);
}
Rioter::~Rioter ()
Rioter dtor.
Definition at line 48 of file Rioter.cpp.
References Agent::L, and m_stateMachine.
{
  lua_close(L);
  delete m_stateMachine;
}
Member Function Documentation
void Rioter::attack ()
Method to send message to attack (deliver damage to target).
Definition at line 201 of file Rioter.cpp.
References BaseGameEntity::getID(), Agent::getTargetID(), Agent::m_damage, m_messageMgr, msgAttack, and MessageManager::sendMessage().
{
  m_messageMgr->sendMessage(this->getID(), this->getTargetID(), msgAttack, m_damage);
}
void Rioter::death ()
Method to send message if a rioter has died.
Definition at line 207 of file Rioter.cpp.
References BaseGameEntity::getID(), GameWorld::getNumberOfRioters(), GameWorld::getRioters(), m_messageMgr, BaseGameEntity::m_pos, BaseGameEntity::m_world, msgRioterDeath, and MessageManager::sendMessage().
{
  for (int i = 0; i < m_world->getNumberOfRioters(); i++)
  {
    ngl::Vec3 vecToRioter = m_world->getRioters()[i]->getPos() - m_pos;
    double distSqToRioter = vecToRioter.lengthSquared();
    double affectedRadius = 8.0;
    if (distSqToRioter < affectedRadius * affectedRadius)
    {
      m_messageMgr->sendMessage(this->getID(), m_world->getRioters()[i]->getID(), msgRioterDeath, 0.f);
    }
  }
}
void Rioter::draw (ngl::Camera * cam, ngl::Mat4 mouseGlobalTX)
Method to draw the rioters.
Parameters:
[in] cam,: the camera used in the scene
[in] mouseGlobalTX,: the global mouse position transformation matrix
Definition at line 89 of file Rioter.cpp.
References loadMatricesToShader(), and Agent::m_mesh.
{
  loadMatricesToShader(cam, mouseGlobalTX);
  m_mesh->draw();
}
void Rioter::findPathHome ()
Method to set the rioter on a path to an exit.
Find Path Home - finds the nearest exit for the rioter and sets a path to this.
Definition at line 241 of file Rioter.cpp.
References Vehicle::findNearestExit(), Vehicle::findPath(), GameWorld::getCellGraph(), CellGraph::getExitPoints(), Agent::m_hasPathHome, Agent::m_homePos, and BaseGameEntity::m_world.
{
  m_homePos = findNearestExit(m_world->getCellGraph()->getExitPoints());
  findPath(m_homePos);
  m_hasPathHome = true;
}
void Rioter::findTargetID (float _health) [virtual]
Method to find a target to pursue.
Find Target ID - find available target that has acceptable amount of health.
Parameters:
[in] _health,: the number to limit the search, if an agent is below this _health then it won't be found as a target
Implements Agent.
Definition at line 148 of file Rioter.cpp.
References EntityManager::getEntityFromID(), Agent::getHealth(), BaseGameEntity::getID(), BaseGameEntity::getNeighbourPoliceIDs(), BaseGameEntity::m_entityMgr, and Agent::setTargetID().
{
  std::vector<int> police = getNeighbourPoliceIDs();
  float currentHealth = -1;
  Agent* currentTarget = NULL;
  for (int i=0; i<police.size(); i++)
  {
    Agent* policeman = dynamic_cast<Agent*>(m_entityMgr->getEntityFromID(police[i]));
    if (policeman)
    {
      if (policeman->getHealth()> _health && policeman->getHealth()>currentHealth)
      {
        currentHealth = policeman->getHealth();
        currentTarget = policeman;
      }
    }
  }
  if (currentTarget == NULL)
  {
    setTargetID(-1);
  }
  else
  {
    int target = currentTarget->getID();
    setTargetID(target);
  }
}
lua_State* Rioter::getLuaState () const [inline]
Gets the lua state of the rioters.
Returns:
the current lua state
Definition at line 39 of file Rioter.h.
References Agent::L.
{ return L ; }
float Rioter::getPoliceInfluence () const [inline]
Gets the influence of the police.
Returns:
Float: the amount of police influence
Definition at line 111 of file Rioter.h.
References m_policeInfluence.
{return m_policeInfluence;}
ngl::Vec3 Rioter::getProtestPos () const [inline]
Get the protest position.
Returns:
Vec3: the vector of the protest position
Definition at line 117 of file Rioter.h.
References m_protestPos.
{return m_protestPos;}
StateMachine<Rioter>* Rioter::getStateMachine () const [inline]
Gets the state machine of the rioter.
Returns:
the rioters state machine
Definition at line 66 of file Rioter.h.
References m_stateMachine.
{ return m_stateMachine; }
bool Rioter::handleMessage (const Message & _message) [virtual]
Method to define how to handle messages.
Parameters:
[in] _messgae:message recieved by the rioter
Reimplemented from Agent.
Definition at line 178 of file Rioter.cpp.
References Message::m_message, Agent::m_morale, Agent::m_rage, msgAttack, msgPoliceDeath, and msgRioterDeath.
{
  switch(_message.m_message)
  {
  case msgRioterDeath:
    m_morale -= 5.f;
    m_rage += 30.f;
    return true;
    break;
  case msgPoliceDeath:
    m_morale -= 15.f;
    break;
  case msgAttack:
    return Agent::handleMessage(_message);
    break;
  default:
    std::cout<<"Rioter: Message type not defined"<<std::endl;
    return false;
    break;
  }
}
void Rioter::loadMatricesToShader (ngl::Camera * cam, ngl::Mat4 mouseGlobalTX)
Method to load the matrices of the rioter to the shader.
Parameters:
[in] cam,: the camera used for the scene
[in] mouseGlobalTX,: the global mouse position transformation matrix
Definition at line 96 of file Rioter.cpp.
References MovingEntity::getHeading(), Agent::getHealth(), BaseGameEntity::getPos(), Agent::getRage(), Agent::m_health, and Agent::m_hop.
{
  ngl::Material m(ngl::Colour(0.2f,0.2f,0.2f, 1.0), ngl::Colour(0.2775f,0.2775f,0.2775f, 1.0), ngl::Colour(0.77391f,0.77391f,0.77391f, 1.0));
  m.setSpecularExponent(5.f);
  m.setDiffuse(ngl::Colour(1.0f-(1-(getHealth()/100.0f)), 1.0f-(getRage()/100.0f)-(1-(getHealth()/100.0f)), 1.0f-(getRage()/100.0f)-(1-(getHealth()/100.0f)), 1.0f));
  m.loadToShader("material");
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  ngl::Mat3 normalMatrix;
  ngl::Mat4 M;
  ngl::Transformation trans;
  trans.setPosition(getPos().m_x,m_hop,getPos().m_z);
  ngl::Real rot = atan(getHeading().m_z/getHeading().m_x);
  rot = ((rot * 180)/M_PI);
  if(getHeading().m_x < 0)
  {
    rot = 180 + rot;
  }
  if(m_health <= 20.f)
  {
    trans.addPosition(0,0.3,0);
    trans.setRotation(90,-rot+90,0);
  }
  else
  {
    trans.setRotation(0,-rot+90,0);
  }
  M=trans.getMatrix()*mouseGlobalTX;
  MV=  M*cam->getViewMatrix();
  MVP= M*cam->getVPMatrix();
  normalMatrix=MV;
  normalMatrix.inverse();
  shader->setShaderParamFromMat4("MV",MV);
  shader->setShaderParamFromMat4("MVP",MVP);
  shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
  shader->setShaderParamFromMat4("M",M);
}
void Rioter::protestCohesion (double weight)
Method to set the protest cohesion of the rioter.
Protest Cohesion - correlates weight of the cohesion to how far away from the protest the rioter is.
Parameters:
[in] weight,: the weight to set the cohesion to
Definition at line 224 of file Rioter.cpp.
References m_protestPos, SteeringBehaviour::setSquadCohesionWeight(), Vehicle::setSquadCrosshair(), SteeringBehaviour::SquadCohesionOff(), SteeringBehaviour::SquadCohesionOn(), and Vehicle::Steering().
{
  if(weight <= 0.0)
  {
    Vehicle::Steering()->SquadCohesionOff();
  }
  else
  {
    Vehicle::setSquadCrosshair(m_protestPos);
    Vehicle::Steering()->setSquadCohesionWeight(weight);
    Vehicle::Steering()->SquadCohesionOn();
  }
}
void Rioter::registerClass (lua_State * _L)
Method to register class, functions and properties to be used in lua.
Register Class - exposes the functions and properties in Rioter.h to lua.
Parameters:
[in] _L,: the lua state
Definition at line 251 of file Rioter.cpp.
References attack(), death(), findPathHome(), getPoliceInfluence(), protestCohesion(), and Agent::registerLua().
{
  registerLua(_L);
  luabridge::getGlobalNamespace(_L)
    .deriveClass<Rioter, Agent>("Rioter")
      .addConstructor <void (*) (GameWorld*, ngl::Obj*)> ()
        .addFunction("attack", &Rioter::attack)
        .addFunction("death", &Rioter::death)
        .addFunction("protestCohesion", &Rioter::protestCohesion)
        .addFunction("getPoliceInfluence", &Rioter::getPoliceInfluence)
        .addFunction("findPathHome", &Rioter::findPathHome)
    .endClass();
}
void Rioter::setProtestPos (ngl::Vec3 newPos) [inline]
Set the protest position.
Parameters:
[in] newPos,: vector of the new protest position
Definition at line 123 of file Rioter.h.
References m_protestPos.
{m_protestPos = newPos;}
void Rioter::update (double timeElapsed, double currentTime) [virtual]
Method to update the rioter at every tick.
Update - updates the rioter with the time elapsed from the last tick.
Parameters:
[in] timeElapsed,: the time elapsed since the last tick
[in] currentTime,: the current time of the game
Implements Agent.
Definition at line 57 of file Rioter.cpp.
References SteeringBehaviour::addAllNeighbours(), SteeringBehaviour::addFriendlyNeighbours(), SteeringBehaviour::clearAllNeighbours(), SteeringBehaviour::clearFriendlyNeighbours(), EntityManager::getEntityFromID(), BaseGameEntity::getNeighbourPoliceIDs(), BaseGameEntity::getNeighbourRioterIDs(), Agent::getRage(), BaseGameEntity::m_entityMgr, Agent::m_hop, Agent::m_hopHeight, Agent::m_hopSpeed, BaseGameEntity::m_ID, BaseGameEntity::m_neighbourPoliceIDs, m_policeInfluence, Agent::m_rage, m_stateMachine, SteeringBehaviour::ObjectOverlapAvoidance(), Vehicle::Steering(), StateMachine< entityType >::update(), and SteeringBehaviour::WallOverlapAvoidance().
{
  Vehicle::Steering()->clearFriendlyNeighbours();
  Vehicle::Steering()->clearAllNeighbours();
  Vehicle::Steering()->addFriendlyNeighbours(getNeighbourRioterIDs());
  Vehicle::Steering()->addAllNeighbours(getNeighbourRioterIDs());
  Vehicle::Steering()->addAllNeighbours(getNeighbourPoliceIDs());
  Vehicle::Steering()->WallOverlapAvoidance();
  Vehicle::Steering()->ObjectOverlapAvoidance();
  Agent::update(timeElapsed, currentTime);
  m_stateMachine->update();
  // calculate influence of neighbouring police based on their rage
  int nearbyPolice = m_neighbourPoliceIDs.size();
  m_policeInfluence = 0.0;
  for (int i=0; i<nearbyPolice; i++)
  {
    Agent* policeman = dynamic_cast<Agent*>(m_entityMgr->getEntityFromID(m_neighbourPoliceIDs[i]));
    if (policeman)
    {
      m_policeInfluence += policeman->getRage();
    }
  }
  m_hopSpeed = m_rage/5.0;
  m_hop = (sin((currentTime*m_hopSpeed)+m_ID)*sin((currentTime*m_hopSpeed)+m_ID)*m_hopHeight);
}
Member Data Documentation
MessageManager* Rioter::m_messageMgr [protected]
Pointer to the message manager.
Reimplemented from BaseGameEntity.
Definition at line 129 of file Rioter.h.
float Rioter::m_policeInfluence [protected]
Float to hold the amount of police influence.
Definition at line 144 of file Rioter.h.
ngl::Vec3 Rioter::m_protestPos [protected]
Vector to contain the protest position.
Definition at line 139 of file Rioter.h.
StateMachine<Rioter>* Rioter::m_stateMachine [protected]
Pointer to the state machine.
Definition at line 134 of file Rioter.h.
The documentation for this class was generated from the following files:
Rioter.h
Rioter.cpp