YOURPROJECTNAMEGOESHERE: Squad Class Reference
Squad Class Reference
The class to define a squad of policemen.
#include <Squad.h>
Public Member Functions
Squad (GameWorld *world, int squadSize, ngl::Vec3 pos, float r, ngl::Obj *_mesh)
Squad ctor.
~Squad ()
Squad dtor.
void update (double timeElapsed, double currentTime)
Method to update the squad every tick.
void draw (ngl::Camera *cam, ngl::Mat4 mouseGlobalTX)
Method to draw the squad.
void drawTarget (ngl::Camera *cam, ngl::Mat4 mouseGlobalTX)
Method to draw the squad's target.
void loadMatricesToShader (ngl::Camera *cam, ngl::Mat4 mouseGlobalTX)
Method to load the matrices to the shader.
bool handleMessage (const Message &_message)
defines virtual function to determine how messages should be handled
void findClosestWalls (Squad *squad)
Reorders the vector of the walls in order of how close to the squad.
void formWall ()
Creates positions for each of the policeman to form a blockade using the closest walls vector.
int checkDeaths ()
Method to check if the policeman in the squad has died.
bool checkSelectionColour (const ngl::Vec3 colour)
Method to check if the colour selected matches the colour of a squad.
void selectionDraw (ngl::Camera *cam, ngl::Mat4 mouseGlobalTX)
Method to draw the squads with the selection colours Not loaded to the shader, just used for selection.
int getSquadSize () const
Gets the squad size.
void setSquadSize (const int _val)
Sets the squad size.
float getSquadRadius () const
Gets the radius of the squad.
void setSquadRadius (const float _val)
Sets the radius of the squad.
ngl::Colour getSquadColour () const
Gets the colour of the squad.
ngl::Colour getSquadSelectedColour () const
Gets the selected colour of the squad.
void setSquadColour (const ngl::Colour _val)
Sets the colour of the squad.
void setSquadSelectedColour (const ngl::Colour _val)
Sets the selected colour of the squad.
void setSquadDrawColour (const ngl::Colour _val)
Sets the draw colour of the squad.
std::vector< Police * > getSquadPolice () const
Gets the police in the squad.
void setTarget (const ngl::Vec3 _target)
Sets the target for the squad and police.
ngl::Vec3 getTarget () const
Gets the target for the squad.
void setSquadState (const char *_luaState, eSquadState _enumState)
Gets the state of the squad.
eSquadState getSquadState ()
Gets the state of the squad.
ngl::Vec3 averagePolicePos ()
Method to calculate the average police position.
void setPreviousState (eSquadState _state)
Sets the previous state of the squad.
eSquadState getPreviousState ()
Gets the previous state of the squad.
Private Attributes
int m_squadSize
Number of policemen in the squad.
float m_squadRadius
The radius of the squad.
ngl::Obj * m_mesh
Pointer to the obj mesh of a policeman.
ngl::Vec3 m_selectionColour
Vector for the selection colour.
std::vector< Police * > m_squadPolice
Vector to hold the police entities in the squad.
ngl::Colour m_squadColour
Vector for the squad colour.
ngl::Colour m_squadSelectedColour
Vector for the selected squad colour.
ngl::Colour m_squadDrawColour
Vector for the squad draw colour.
ngl::Vec3 m_target
Vector for the target of the squad.
std::vector< Police * > m_deadSquadPolice
Vector to hold the dead police entities in the squad.
std::vector< bool > m_policeArrived
Vector to hold a boolean of whether a policeman has arrived at the target.
bool m_allArrived
Boolean to say whether all the policemen have arrived.
bool m_generatedBlockade
Boolean to say whether the blockade positions have been generated.
bool m_inBlockade
Boolean to say whether the policeman are in the blockade.
std::vector< ngl::Vec3 > m_blockadePositions
Vector to hold the blockade position for each policeman.
std::vector< Wall > m_closestWalls
Vector to contain the walls, in order of how close they are to the squad.
eSquadState m_squadState
enum Squad State to hold what the current state of the squad is
eSquadState m_previousState
enum Squad State to hold what the previous state of the squad is
Static Private Attributes
static ngl::Vec3 s_nextSelectionColour = ngl::Vec3(0.0,0.0,0.0)
Vector for the next selection colour.
Detailed Description
The class to define a squad of policemen.
Author:
Faye Butler, Will Herbert & Emily Holt
Version:
1.0
Date:
Last revision 10/05/2015 Updated to comply with doxygen and NCCA coding standard
Definition at line 31 of file Squad.h.
Constructor & Destructor Documentation
Squad::Squad (GameWorld * world, int squadSize, ngl::Vec3 pos, float r, ngl::Obj * _mesh)
Squad ctor.
Parameters:
[in] world,: Pointer to the gameworld
[in] squadSize,: number of policemen in the squad
[in] pos,: inital position of the squad
[in] r,: radius of the squad
[in] _mesh,: pointer to the obj mesh used for a policeman
Definition at line 16 of file src/Squad.cpp.
References GameWorld::getCellGraph(), BaseGameEntity::getCurrentCellID(), EntityManager::getEntityFromID(), BaseGameEntity::getID(), CellGraph::initializeCells(), m_allArrived, BaseGameEntity::m_boundingRadius, BaseGameEntity::m_entityMgr, m_generatedBlockade, BaseGameEntity::m_ID, m_inBlockade, m_mesh, m_policeArrived, BaseGameEntity::m_pos, m_previousState, m_selectionColour, m_squadColour, m_squadPolice, m_squadRadius, m_squadSize, s_nextSelectionColour, BaseGameEntity::setBoudingRadius(), BaseGameEntity::setDetectionRadius(), BaseGameEntity::setPos(), Police::setSquadID(), Police::setSquadPos(), Police::setSquadRadius(), setSquadState(), and squadPatrol.
                                                                                :Vehicle(world, pos, ngl::Vec3(0,0,0), 0.0f, 1.0f, 10.0f,1.0f, 1.0f, 0.5f)
{
  m_allArrived = false;
  m_inBlockade = false;
  m_generatedBlockade = false;
  m_squadSize = squadSize;
  m_previousState = squadPatrol;
  m_squadColour = ngl::Colour(0.0f,0.5f,0.5f,1.0f);
  m_squadRadius = squadSize*m_boundingRadius;
  m_mesh = _mesh;
  for (int i = 0; i < squadSize; ++i)
  {
    Police* newPolice = new Police(world, m_mesh);
    newPolice->setBoudingRadius(m_boundingRadius);
    newPolice->setDetectionRadius(3.5f);
    newPolice->setPos(ngl::Vec3((((float)rand()/RAND_MAX)*m_squadRadius*2)-m_squadRadius+ m_pos.m_x, 0.0f, (((float)rand()/RAND_MAX)*m_squadRadius*2)-m_squadRadius+ m_pos.m_z));
    world->getCellGraph()->initializeCells(m_entityMgr->getEntityFromID(newPolice->getID()));
    while (newPolice->getCurrentCellID() < 0)
    {
      newPolice->setPos(ngl::Vec3((((float)rand()/RAND_MAX)*m_squadRadius*2)-m_squadRadius+ m_pos.m_x, 0.0f, (((float)rand()/RAND_MAX)*m_squadRadius*2)-m_squadRadius+ m_pos.m_z));
      world->getCellGraph()->initializeCells(m_entityMgr->getEntityFromID(newPolice->getID()));
    }
    newPolice->setSquadPos(m_pos);
    newPolice->setSquadRadius(m_squadRadius);
    newPolice->setSquadID(m_ID);
    m_squadPolice.push_back(newPolice);
    m_policeArrived.push_back(false);
  }
  setSquadState("patrol", squadPatrol);
  m_selectionColour = s_nextSelectionColour;
  s_nextSelectionColour.m_x += 0.1;
  if(s_nextSelectionColour.m_x >= 1)
  {
    s_nextSelectionColour.m_x = 0;
    s_nextSelectionColour.m_y += 0.1;
    if(s_nextSelectionColour.m_y >= 1)
    {
      s_nextSelectionColour.m_y = 0;
      s_nextSelectionColour.m_z += 0.1;
    }
  }
}
Squad::~Squad ()
Squad dtor.
Definition at line 67 of file src/Squad.cpp.
References m_deadSquadPolice, and m_squadPolice.
{
  BOOST_FOREACH(Police *p, m_squadPolice)
  {
      delete p;
  }
  m_squadPolice.clear();
  BOOST_FOREACH(Police *p, m_deadSquadPolice)
  {
      delete p;
  }
  m_deadSquadPolice.clear();
}
Member Function Documentation
ngl::Vec3 Squad::averagePolicePos ()
Method to calculate the average police position.
Average Police Pos - function to calculate the average position of the police in the squad.
Definition at line 84 of file src/Squad.cpp.
References BaseGameEntity::getPos(), m_squadPolice, and m_squadSize.
{
  ngl::Vec3 currentTotal =0;
  for (int i = 0; i< m_squadSize; i++)
  {
    Police* currentPolice = m_squadPolice[i];
    currentTotal += currentPolice->getPos();
  }
   currentTotal /= m_squadSize;
  return currentTotal;
}
int Squad::checkDeaths ()
Method to check if the policeman in the squad has died.
Check Deaths - function to check the number of police in the squad that are dead.
Returns:
Int: the number of deaths in the squad
Definition at line 340 of file src/Squad.cpp.
References Police::death(), Agent::getHealth(), m_deadSquadPolice, BaseGameEntity::m_entityMgr, m_squadPolice, m_squadSize, and EntityManager::removeEntity().
{
  int numberOfDeaths = 0;
  for(int i=0; i<m_squadSize; i++)
  {
    Police* currentPolice = m_squadPolice[i];
    if(currentPolice->getHealth()<=0)
    {
        currentPolice->death();
        m_entityMgr->removeEntity(dynamic_cast<BaseGameEntity*>(currentPolice));
        m_deadSquadPolice.push_back(currentPolice);
        m_squadPolice.erase(m_squadPolice.begin()+i);
        m_squadSize -= 1;
        numberOfDeaths++;
        i--;
    }
  }
  return numberOfDeaths;
}
bool Squad::checkSelectionColour (const ngl::Vec3 colour)
Method to check if the colour selected matches the colour of a squad.
Parameters:
[in] cam,: colour: vector to hold the colour selected
Returns:
Boolean: returns true if the colour matches a squad, false if it doesn't
Check Selection colour - checks if the selected colour matches the colour of a squad
returns true if it does, false if it doesn't
Definition at line 270 of file src/Squad.cpp.
References m_selectionColour.
{
  if(m_selectionColour.m_x >= colour.m_x-0.01f && m_selectionColour.m_x <= colour.m_x+0.01f &&
     m_selectionColour.m_y >= colour.m_y-0.01f && m_selectionColour.m_y <= colour.m_y+0.01f &&
     m_selectionColour.m_z >= colour.m_z-0.01f && m_selectionColour.m_z <= colour.m_z+0.01f)
  {
    return true;
  }
  else
  {
    return false;
  }
}
void Squad::draw (ngl::Camera * cam, ngl::Mat4 mouseGlobalTX)
Method to draw the squad.
Draw - calls the police draw and loads squad draws matrices to shader.
Parameters:
[in] cam,: the camera used in the scene
[in] mouseGlobalTX,: the global transform of the mouse position
Definition at line 183 of file src/Squad.cpp.
References Police::draw(), loadMatricesToShader(), m_squadPolice, m_squadRadius, and m_squadSize.
{
    for(unsigned int i=0; i<m_squadSize; ++i)
    {
      Police* currentPolice = m_squadPolice[i];
      currentPolice->draw(cam, mouseGlobalTX);
    }
  loadMatricesToShader(cam, mouseGlobalTX);
  ngl::VAOPrimitives::instance()->createDisk("squad",m_squadRadius,12);
  ngl::VAOPrimitives::instance()->draw("squad");
}
void Squad::drawTarget (ngl::Camera * cam, ngl::Mat4 mouseGlobalTX)
Method to draw the squad's target.
Draw Target - draws the target in the move state.
Parameters:
[in] cam,: the camera used in the scene
[in] mouseGlobalTX,: the global transform of the mouse position
Definition at line 200 of file src/Squad.cpp.
References m_squadDrawColour, m_squadState, m_target, and squadMove.
{
  if(m_squadState == squadMove)
  {
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    (*shader)["Phong"]->use();
    ngl::Material m(ngl::Colour(0.2f,0.2f,0.2f, 1.0), ngl::Colour(0.2775f,0.2775f,0.2775f, 1.0), ngl::Colour(0.77391f,0.77391f,0.77391f, 1.0));
    m.setSpecularExponent(5.f);
    m.setDiffuse(ngl::Colour(m_squadDrawColour.m_r+0.3f,m_squadDrawColour.m_g+0.3f,m_squadDrawColour.m_b+0.3f,m_squadDrawColour.m_a));
    m.loadToShader("material");
      ngl::Mat4 MV;
      ngl::Mat4 MVP;
      ngl::Mat3 normalMatrix;
      ngl::Mat4 M;
      ngl::Transformation trans;
      trans.setPosition(m_target.m_x, 0.005f, m_target.m_z);
      trans.setRotation(90.0,0.0,0.0);
    M=trans.getMatrix()*mouseGlobalTX;
    MV=  M*cam->getViewMatrix();
    MVP= M*cam->getVPMatrix();
    normalMatrix=MV;
    normalMatrix.inverse();
      shader->setShaderParamFromMat4("MVP",MVP);
      shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
    ngl::VAOPrimitives::instance()->createDisk("target",1.0,12);
    ngl::VAOPrimitives::instance()->draw("target");
  }
}
void Squad::findClosestWalls (Squad * squad)
Reorders the vector of the walls in order of how close to the squad.
Parameters:
[in] squad,: the squad to measure to the walls from
Closest Walls - this iterates through a vector of the closest walls to the squad and reorders it with the closest first, to be used in the blockade
Definition at line 381 of file src/Squad.cpp.
References Wall::end, BaseGameEntity::getCurrentCell(), Cell::getWalls(), m_closestWalls, BaseGameEntity::m_pos, and Wall::start.
{
  m_closestWalls.clear();
  std::vector<Wall> inWalls = squad->getCurrentCell().getWalls();
  std::vector<int> wallMemory;
  int numberOfWallsToCheck = inWalls.size();
  while (m_closestWalls.size() < numberOfWallsToCheck)
  {
    float shortestDist;
    Wall closestWall;
    int closestWallID = 0;
    bool isInMemory = false;
    for (int i = 0; i < numberOfWallsToCheck; i++ )
    {
      shortestDist = 10000000000.0f;
      isInMemory = false;
      for (std::vector<int>::iterator iter = wallMemory.begin(); iter != wallMemory.end(); ++iter)
      {
        if( *iter == i)
        {
          isInMemory = true;
          break;
        }
      }
      if(isInMemory == true){break;}
      Wall currentWall = inWalls[i];
      ngl::Vec3 currentCenter = (currentWall.start+currentWall.end)/2;
      ngl::Vec3 distance = (currentCenter-m_pos);
      if(distance.lengthSquared() < shortestDist)
      {
        shortestDist = distance.lengthSquared();
        closestWall = inWalls[i];
        closestWallID = i;
      }
    }
    wallMemory.push_back(closestWallID);
    m_closestWalls.push_back(closestWall);
  }
  inWalls.clear();
  wallMemory.clear();
}
void Squad::formWall ()
Creates positions for each of the policeman to form a blockade using the closest walls vector.
Form wall - used to form a blockade of policemen, taking the closest walls and cells it computes the positions based on how many police in the squad and their bounding radius
Definition at line 434 of file src/Squad.cpp.
References Wall::end, findClosestWalls(), m_blockadePositions, BaseGameEntity::m_boundingRadius, m_closestWalls, m_generatedBlockade, m_inBlockade, BaseGameEntity::m_pos, m_squadSize, Wall::normal, and Wall::start.
{
    m_inBlockade = false;
    int numberOfWallsToCheck =0;
    m_generatedBlockade = false;
    //check to make sure not already made
    if(m_generatedBlockade == false)
    {
      //update the closest walls vector
      findClosestWalls(this);
      numberOfWallsToCheck = m_closestWalls.size();
    }
    m_blockadePositions.clear();
    for(int i=0; i<numberOfWallsToCheck; i++)
    {
      if(m_generatedBlockade == false)
      {
          Wall currentWall = m_closestWalls[i];
          ngl::Vec3 currentNormal = currentWall.normal;
          ngl::Vec3 currentCenter = (currentWall.start+currentWall.end)/2;
          for(int j=0; j<numberOfWallsToCheck; j++)
          {
            //check not testing same wall against itself
            if(i!=j)
            {
              Wall testWall = m_closestWalls[j];
              ngl::Vec3 testNormal = testWall.normal;
              ngl::Vec3 testCenter = (testWall.start+testWall.end)/2;
              // if true this means two walls are facing each other
              if(currentNormal + testNormal == ngl::Vec3(0.0,0.0,0.0))
              {
                //if vertical line
                if(currentCenter.m_x - testCenter.m_x == 0)
                {
                  ngl::Vec3 distance = currentCenter - testCenter;
                  ngl::Vec3 upperCenter = ngl::Vec3(0.0,0.0,0.0);
                  //test which wall is the higher wall
                  if(currentCenter.m_z < testCenter.m_z)
                  {
                    upperCenter = currentCenter;
                  }
                  else if(currentCenter.m_z > testCenter.m_z)
                  {
                    upperCenter = testCenter;
                  }
                  float dist = distance.length();
                  float numberOf= dist/m_boundingRadius;
                  if(numberOf >= m_squadSize)
                  {
                    //calculate spacing for however many police in squad
                    float spacing = dist/(m_squadSize*2);
                    m_blockadePositions.clear();
                    for(int i =0; i< m_squadSize*2; i+=2)
                    {
                      //set position, the x value should be the middle of the squad as it is value that doesn't change
                      ngl::Vec3 position = ngl::Vec3(m_pos.m_x, 0.0, upperCenter.m_z +((i+1)*spacing));
                      m_blockadePositions.push_back(position);
                    }
                   }
                  m_generatedBlockade = true;
                  m_inBlockade = true;
                   break;
                  }
                else if(currentCenter.m_z - testCenter.m_z == 0)
                {
                  //if horizontal line
                  ngl::Vec3 distance = currentCenter - testCenter;
                  ngl::Vec3 leftCenter = ngl::Vec3(0.0,0.0,0.0);
                  //test which wall is to the left
                  if(currentCenter.m_x < testCenter.m_x)
                  {
                    leftCenter = currentCenter;
                  }
                  else if(currentCenter.m_x > testCenter.m_x)
                  {
                    leftCenter = testCenter;
                  }
                  float dist = distance.length();
                  float numberOf= dist/m_boundingRadius;
                  if(numberOf >= m_squadSize)
                  {
                    //calculate spacing for however many police in squad
                    float spacing = dist/(m_squadSize*2);
                    m_blockadePositions.clear();
                    for(int i =0; i< m_squadSize*2; i+=2)
                    {
                      //set position, the x value should be the middle of the squad as it is value that doesn't change
                      ngl::Vec3 position = ngl::Vec3(leftCenter.m_x +((i+1)*spacing), 0.0, m_pos.m_z);
                      m_blockadePositions.push_back(position);
                    }
                   }
                  m_generatedBlockade = true;
                  m_inBlockade = true;
                  break;
                }
                else
                {
                  m_generatedBlockade = false;
                  m_inBlockade = false;
                  std::cout<<" CANT FORM WALL "<<std::endl;
                }
               }
              else
              {
                m_generatedBlockade = false;
                m_inBlockade = false;
               std::cout<<" CANT FORM WALL"<<std::endl;
              }
            }
          }
        }
      }
}
eSquadState Squad::getPreviousState () [inline]
Gets the previous state of the squad.
Returns:
eSquadSate: returns the previous enum squad state
Definition at line 213 of file Squad.h.
References m_previousState.
{return m_previousState;}
ngl::Colour Squad::getSquadColour () const [inline]
Gets the colour of the squad.
Returns:
Colour: vector of the colour of the squad
Definition at line 140 of file Squad.h.
References m_squadColour.
{ return m_squadColour; }
std::vector<Police*> Squad::getSquadPolice () const [inline]
Gets the police in the squad.
Returns:
Vector: returns a vector that contains the police entities in the squad
Definition at line 171 of file Squad.h.
References m_squadPolice.
{return m_squadPolice;}
float Squad::getSquadRadius () const [inline]
Gets the radius of the squad.
Returns:
Float: the size of the radius of the squad
Definition at line 128 of file Squad.h.
References m_squadRadius.
{ return m_squadRadius; }
ngl::Colour Squad::getSquadSelectedColour () const [inline]
Gets the selected colour of the squad.
Returns:
Colour: vector of the selected colour of the squad
Definition at line 146 of file Squad.h.
References m_squadSelectedColour.
{ return m_squadSelectedColour; }
int Squad::getSquadSize () const [inline]
Gets the squad size.
Returns:
Int: the number of policeman in the squad
Definition at line 116 of file Squad.h.
References m_squadSize.
{ return m_squadSize; }
eSquadState Squad::getSquadState () [inline]
Gets the state of the squad.
Returns:
eSquadSate: returns the enum squad state
Definition at line 196 of file Squad.h.
References m_squadState.
{ return m_squadState; }
ngl::Vec3 Squad::getTarget () const [inline]
Gets the target for the squad.
Returns:
Vec3: returns the target position
Definition at line 183 of file Squad.h.
References m_target.
{return m_target;}
bool Squad::handleMessage (const Message & _message) [virtual]
defines virtual function to determine how messages should be handled
Parameters:
[in] _messgae:message recieved by the squad
Reimplemented from Vehicle.
Definition at line 361 of file src/Squad.cpp.
References Message::m_message, and msgAttack.
{
  switch(_message.m_message)
  {
  case msgAttack:
    return true;
    break;
  default:
    std::cout<<"Squad: Message type not defined"<<std::endl;
    return false;
    break;
  }
}
void Squad::loadMatricesToShader (ngl::Camera * cam, ngl::Mat4 mouseGlobalTX)
Method to load the matrices to the shader.
Parameters:
[in] cam,: the camera used in the scene
[in] mouseGlobalTX,: the global transform of the mouse position
Definition at line 237 of file src/Squad.cpp.
References BaseGameEntity::m_pos, and m_squadColour.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    (*shader)["Phong"]->use();
  ngl::Material m(ngl::Colour(0.2f,0.2f,0.2f, 1.0), ngl::Colour(0.2775f,0.2775f,0.2775f, 1.0), ngl::Colour(0.77391f,0.77391f,0.77391f, 1.0));
  m.setSpecularExponent(5.f);
  m.setDiffuse(ngl::Colour(m_squadColour));
  m.loadToShader("material");
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  ngl::Mat3 normalMatrix;
  ngl::Mat4 M;
  ngl::Transformation trans;
  trans.setPosition(m_pos.m_x, 0.004, m_pos.m_z);
  trans.setRotation(90.0,15.0,0.0);
  M=trans.getMatrix()*mouseGlobalTX;
  MV=  M*cam->getViewMatrix();
  MVP= M*cam->getVPMatrix();
  normalMatrix=MV;
  normalMatrix.inverse();
  shader->setShaderParamFromMat4("MVP",MVP);
  shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
}
void Squad::selectionDraw (ngl::Camera * cam, ngl::Mat4 mouseGlobalTX)
Method to draw the squads with the selection colours Not loaded to the shader, just used for selection.
Selection Draw - this draws the squad colours as used for the colour selection (this is not actually loaded to the shader).
Parameters:
[in] cam,: the camera used in the scene
[in] mouseGlobalTX,: the global transform of the mouse position
Definition at line 287 of file src/Squad.cpp.
References BaseGameEntity::m_pos, m_selectionColour, and m_squadRadius.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  (*shader)["nglColourShader"]->use();
  shader->setShaderParam4f("Colour", m_selectionColour.m_x, m_selectionColour.m_y,m_selectionColour.m_z, 1);
  ngl::Transformation t;
  t.setPosition(m_pos.m_x, 0.3, m_pos.m_z);
  t.setRotation(90.0,0.0,0.0);
  ngl::Mat4 M;
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  M=t.getMatrix()*mouseGlobalTX;
  MV=  M*cam->getViewMatrix();
  MVP= M*cam->getVPMatrix();
  shader->setShaderParamFromMat4("MVP",MVP);
  ngl::VAOPrimitives::instance()->createDisk("squad",m_squadRadius,120);
  ngl::VAOPrimitives::instance()->draw("squad");
}
void Squad::setPreviousState (eSquadState _state) [inline]
Sets the previous state of the squad.
Returns:
eSquadSate: returns the previous enum squad state
Definition at line 207 of file Squad.h.
References m_previousState.
{m_previousState = _state;}
void Squad::setSquadColour (const ngl::Colour _val) [inline]
Sets the colour of the squad.
Parameters:
[in] _val,: the vector to set the colour of the squad to
Definition at line 152 of file Squad.h.
References m_squadColour.
{ m_squadColour = _val; }
void Squad::setSquadDrawColour (const ngl::Colour _val) [inline]
Sets the draw colour of the squad.
Parameters:
[in] _val,: the vector to set the draw colour of the squad to
Definition at line 165 of file Squad.h.
References m_squadDrawColour.
{ m_squadDrawColour = _val; }
void Squad::setSquadRadius (const float _val) [inline]
Sets the radius of the squad.
Parameters:
[in] _val,: the number to set the radius of the squad
Definition at line 134 of file Squad.h.
References m_squadRadius.
{ m_squadRadius = _val; }
void Squad::setSquadSelectedColour (const ngl::Colour _val) [inline]
Sets the selected colour of the squad.
Parameters:
[in] _val,: the vector to set the selected colour of the squad to
Definition at line 159 of file Squad.h.
References m_squadSelectedColour.
{ m_squadSelectedColour = _val; }
void Squad::setSquadSize (const int _val) [inline]
Sets the squad size.
Parameters:
[in] _val,: number to set how many policeman in the squad
Definition at line 122 of file Squad.h.
References m_squadSize.
{ m_squadSize = _val; }
void Squad::setSquadState (const char * _luaState, eSquadState _enumState)
Gets the state of the squad.
Set Squad State - used to change the squad state to the eSquadState in lua.
Parameters:
[in] _luaState,: the lua state to change to
[in] _enumState,: the enum squad state
Definition at line 568 of file src/Squad.cpp.
References StateMachine< entityType >::changeState(), Police::getStateMachine(), m_squadPolice, m_squadSize, and m_squadState.
{
  m_squadState = _enumState;
  for(unsigned int i=0; i<m_squadSize; ++i)
  {
    Police* currentPolice = m_squadPolice[i];
    currentPolice->getStateMachine()->changeState(_luaState);
  }
}
void Squad::setTarget (const ngl::Vec3 _target)
Sets the target for the squad and police.
Set Target - sets the previous state of the squad when it enters move, and finds a path to the target.
Parameters:
[in] _target,: vector position of the target
Definition at line 315 of file src/Squad.cpp.
References Vehicle::findPath(), m_allArrived, m_inBlockade, m_policeArrived, BaseGameEntity::m_pos, m_previousState, m_squadPolice, m_squadRadius, m_squadSize, m_squadState, m_target, Police::setIsMoving(), Police::setSquadPos(), Police::setSquadRadius(), and squadMove.
{
  if(m_squadState != squadMove)
  {
    m_previousState = m_squadState;
  }
  m_target = _target;
  for(unsigned int i=0; i<m_squadSize; ++i)
  {
    Police* currentPolice = m_squadPolice[i];
    currentPolice->setSquadPos(m_pos);
    currentPolice->setSquadRadius(m_squadRadius);
    currentPolice->findPath(_target);
    currentPolice->setIsMoving(true);
    m_policeArrived[i] = false;
  }
  m_allArrived = false;
  m_inBlockade = false;
  m_squadState = squadMove;
}
void Squad::update (double timeElapsed, double currentTime)
Method to update the squad every tick.
Update - updates the police within the squad, according to what state they are in if in state move, then police are set to moving (lua state) if in state wall, form wall is called and crosshairs are set to individual blockade positions
Definition at line 101 of file src/Squad.cpp.
References averagePolicePos(), formWall(), BaseGameEntity::getPos(), m_allArrived, m_blockadePositions, m_generatedBlockade, m_policeArrived, BaseGameEntity::m_pos, m_previousState, m_squadPolice, m_squadRadius, m_squadSize, m_squadState, m_target, Police::setBlockadePos(), Vehicle::setCrosshair(), Police::setIsMoving(), Police::setSquadPos(), Police::setSquadRadius(), squadMove, squadWall, and Police::update().
{
  // squad checks
  // SQUAD MOVE
  if(m_squadState == squadMove )
  {
    m_pos = averagePolicePos();
    // check if all police have arrived- break if one hasn't
    m_allArrived = true;
    for(unsigned int i=0; i<m_squadSize; ++i)
    {
       Police* currentPolice = m_squadPolice[i];
       currentPolice->setIsMoving(false);
       if(m_policeArrived[i]==false)
       {
         //set to moving, sets the police to lua state move
         m_allArrived = false;
         currentPolice->setIsMoving(true);
         break;
       }
     }
    //switch out of move if police have ALL arrived
    if(m_allArrived == true)
    {
      m_squadState = m_previousState;
    }
  }
  // SQUAD WALL
  else if(m_squadState == squadWall)
  {
    this->formWall();
  }
  // individual police loop
  for(unsigned int i=0; i<m_squadSize; ++i)
  {
    Police* currentPolice = m_squadPolice[i];
    currentPolice->setSquadPos(m_pos);
    currentPolice->setSquadRadius(m_squadRadius);
    // MOVE
    if(m_squadState == squadMove)
    {
      if ((currentPolice->getPos() - m_target).lengthSquared()<= 4)
      {
        m_policeArrived[i] = true;
        currentPolice->setIsMoving(false);
      }
    }
    else
    {
      //WALL
      if (m_generatedBlockade == false)
      {
        currentPolice->setCrosshair(m_pos);
      }
      currentPolice->setIsMoving(false);
    }
    // WALL
    if(m_squadState == squadWall && m_generatedBlockade == true)
    {
      currentPolice->setBlockadePos(m_blockadePositions[i]);
    }
    else if(m_squadState != squadWall)
    {
      currentPolice->setBlockadePos(NULL);
    }
    //finally update the police
    currentPolice->update(timeElapsed, currentTime);
  }
}
Member Data Documentation
bool Squad::m_allArrived [private]
Boolean to say whether all the policemen have arrived.
Definition at line 281 of file Squad.h.
std::vector<ngl::Vec3> Squad::m_blockadePositions [private]
Vector to hold the blockade position for each policeman.
Definition at line 296 of file Squad.h.
std::vector<Wall> Squad::m_closestWalls [private]
Vector to contain the walls, in order of how close they are to the squad.
Definition at line 301 of file Squad.h.
std::vector<Police*> Squad::m_deadSquadPolice [private]
Vector to hold the dead police entities in the squad.
Definition at line 271 of file Squad.h.
bool Squad::m_generatedBlockade [private]
Boolean to say whether the blockade positions have been generated.
Definition at line 286 of file Squad.h.
bool Squad::m_inBlockade [private]
Boolean to say whether the policeman are in the blockade.
Definition at line 291 of file Squad.h.
ngl::Obj* Squad::m_mesh [private]
Pointer to the obj mesh of a policeman.
Definition at line 230 of file Squad.h.
std::vector<bool> Squad::m_policeArrived [private]
Vector to hold a boolean of whether a policeman has arrived at the target.
Definition at line 276 of file Squad.h.
eSquadState Squad::m_previousState [private]
enum Squad State to hold what the previous state of the squad is
Definition at line 311 of file Squad.h.
ngl::Vec3 Squad::m_selectionColour [private]
Vector for the selection colour.
Definition at line 235 of file Squad.h.
ngl::Colour Squad::m_squadColour [private]
Vector for the squad colour.
Definition at line 250 of file Squad.h.
ngl::Colour Squad::m_squadDrawColour [private]
Vector for the squad draw colour.
Definition at line 261 of file Squad.h.
std::vector<Police*> Squad::m_squadPolice [private]
Vector to hold the police entities in the squad.
Definition at line 245 of file Squad.h.
float Squad::m_squadRadius [private]
The radius of the squad.
Definition at line 225 of file Squad.h.
ngl::Colour Squad::m_squadSelectedColour [private]
Vector for the selected squad colour.
Definition at line 256 of file Squad.h.
int Squad::m_squadSize [private]
Number of policemen in the squad.
Definition at line 220 of file Squad.h.
eSquadState Squad::m_squadState [private]
enum Squad State to hold what the current state of the squad is
Definition at line 306 of file Squad.h.
ngl::Vec3 Squad::m_target [private]
Vector for the target of the squad.
Definition at line 266 of file Squad.h.
ngl::Vec3 Squad::s_nextSelectionColour = ngl::Vec3(0.0,0.0,0.0) [static, private]
Vector for the next selection colour.
Definition at line 240 of file Squad.h.
The documentation for this class was generated from the following files:
Squad.h
src/Squad.cpp